Repository hazelcast/hazelcast, pull requests merged in 2018-02, with the labels that each got.

#12297 Removed encryption doc from ChannelInboundHandler
  hazelcast/src/main/java/com/hazelcast/internal/networking/ChannelInboundHandler.java
Labels: Team: Core, Type: Cleanup

#12312 Log in MapLoaderTest.testSenderAndBackupTerminates_AfterInitialLoad
  hazelcast/src/test/java/com/hazelcast/map/impl/mapstore/MapLoaderTest.java
Labels: Team: Core

#12296 DefaultNodeContext super minor cleanup
  hazelcast/src/main/java/com/hazelcast/instance/DefaultNodeContext.java
Labels: Team: Core, Type: Cleanup

#12305 Fixed deserialization of merge operations
  hazelcast/src/main/java/com/hazelcast/cache/impl/operation/CacheMergeOperation.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/operation/CacheMergeOperationFactory.java
  hazelcast/src/main/java/com/hazelcast/collection/impl/collection/operations/CollectionMergeOperation.java
  hazelcast/src/main/java/com/hazelcast/collection/impl/queue/operations/QueueMergeOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/MergeOperationFactory.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/operation/MergeOperation.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/operation/MergeOperationFactory.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/operations/MergeOperation.java
Labels: Team: Core, Type: Perf. Defect

#12319 Introduced a Protocols.PROTOCOL_LENGTH constant
  hazelcast/src/main/java/com/hazelcast/nio/Protocols.java
  hazelcast/src/main/java/com/hazelcast/nio/tcp/MemberChannelInitializer.java
Labels: Team: Core, Type: Cleanup

#11713 Minor doc fix in WaitSet
  hazelcast/src/main/java/com/hazelcast/spi/impl/operationparker/impl/WaitSet.java
Labels: Team: Core, Type: Cleanup

#12288 Rename read write handler to pipeline
  hazelcast/src/main/java/com/hazelcast/internal/diagnostics/OverloadedConnectionsPlugin.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioChannel.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioEventLoopGroup.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioInboundPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioOutboundPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioThread.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/iobalancer/IOBalancer.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/iobalancer/LoadImbalance.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/NioThreadAbstractTest.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/iobalancer/IOBalancerStressTest.java
  hazelcast/src/test/java/com/hazelcast/nio/tcp/PacketDecoderTest.java
  hazelcast/src/test/java/com/hazelcast/nio/tcp/TcpIpConnection_AbstractTransferStressTest.java
Labels: Team: Core, Type: Cleanup

#12283 Forbid shutting down member via console on Management Center
  hazelcast/src/main/java/com/hazelcast/console/ConsoleApp.java
  hazelcast/src/main/java/com/hazelcast/internal/management/ConsoleCommandHandler.java
  hazelcast/src/test/java/com/hazelcast/internal/management/ConsoleCommandRequestTest.java
Labels: Team: Integration, Type: Defect

#12291 Added map.delete method for console app
  hazelcast-client/src/main/java/com/hazelcast/client/console/ClientConsoleApp.java
  hazelcast/src/main/java/com/hazelcast/console/ConsoleApp.java
  hazelcast/src/test/java/com/hazelcast/console/ConsoleAppTest.java
Labels: Team: Integration

#12276 Fixed ommited timeToLiveSeconds value
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/dynamicconfig/AddMapConfigMessageTask.java
  hazelcast/src/test/java/com/hazelcast/internal/dynamicconfig/DynamicConfigTest.java
Labels: Team: Core, Type: Defect

#12292 [BACKPORT] Fixed ommited timeToLiveSeconds value
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/dynamicconfig/AddMapConfigMessageTask.java
  hazelcast/src/test/java/com/hazelcast/internal/dynamicconfig/DynamicConfigTest.java
Labels: Team: Core, Type: Defect

#12329 Added IOUtil debug method for bytebuffers
  hazelcast/src/main/java/com/hazelcast/nio/IOUtil.java
Labels: Team: Core, Type: Enhancement

#12327 [BACKPORT] Text connection send buffer not correctly sized
  hazelcast/src/main/java/com/hazelcast/nio/tcp/MemberChannelInitializer.java
Labels: Team: Client, Team: Core, Type: Defect

#12326 The text connection send buffer not correctly sized
  hazelcast/src/main/java/com/hazelcast/nio/tcp/MemberChannelInitializer.java
Labels: Team: Client, Team: Core, Type: Defect

#12304 Fix failing IScheduledExecutor GetAllScheduledFutures
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/DistributedScheduledExecutorService.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorContainer.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorPartition.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledTaskDescriptor.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/operations/AbstractGetAllScheduledOperation.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/MutatingOperation.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/ScheduledExecutorSplitBrainTest.java
Labels: Team: Core, Type: Defect, Type: Test-Failure

#12325 Removed superfluous IOUtil IOExceptions
  hazelcast/src/main/java/com/hazelcast/nio/IOUtil.java
Labels: Team: Core, Type: Cleanup

#12328 [BACKPORT] Forbid shutting down member via console on Management Center
  hazelcast/src/main/java/com/hazelcast/console/ConsoleApp.java
  hazelcast/src/main/java/com/hazelcast/internal/management/ConsoleCommandHandler.java
  hazelcast/src/test/java/com/hazelcast/internal/management/ConsoleCommandRequestTest.java
Labels: Backport, Team: Integration, Type: Defect

#12242 Fix indexed query consistency during migration
  hazelcast/src/main/java/com/hazelcast/map/impl/MapMigrationAwareService.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/MapReplicationStateHolder.java
  hazelcast/src/main/java/com/hazelcast/query/impl/Indexes.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/batching/PartitionAwareCallableBatchingRunnable.java
Labels: Team: Core

#12321 SplitBrainMergePolicy design improvements
  hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java
  hazelcast/src/main/java/com/hazelcast/collection/impl/collection/CollectionContainer.java
  hazelcast/src/main/java/com/hazelcast/collection/impl/queue/QueueContainer.java
  hazelcast/src/main/java/com/hazelcast/concurrent/atomiclong/AtomicLongContainer.java
  hazelcast/src/main/java/com/hazelcast/concurrent/atomicreference/AtomicReferenceContainer.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/DefaultRecordStore.java
  hazelcast/src/main/java/com/hazelcast/multimap/impl/MultiMapContainer.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/record/AbstractReplicatedRecordStore.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/ArrayRingbuffer.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferContainer.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferService.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorContainer.java
  hazelcast/src/main/java/com/hazelcast/spi/SplitBrainMergePolicy.java
  hazelcast/src/main/java/com/hazelcast/spi/merge/AbstractMergePolicy.java
  hazelcast/src/main/java/com/hazelcast/spi/merge/HyperLogLogMergePolicy.java
  hazelcast/src/test/java/com/hazelcast/concurrent/atomiclong/AtomicLongSplitBrainTest.java
  hazelcast/src/test/java/com/hazelcast/concurrent/atomicreference/AtomicReferenceSplitBrainTest.java
  hazelcast/src/test/java/com/hazelcast/instance/HazelcastManagedContextTest.java
  hazelcast/src/test/java/com/hazelcast/instance/ManagedContextInstanceAwareTest.java
  hazelcast/src/test/java/com/hazelcast/ringbuffer/impl/RingbufferContainerSerializationTest.java
  hazelcast/src/test/java/com/hazelcast/ringbuffer/impl/RingbufferContainerTest.java
  hazelcast/src/test/java/com/hazelcast/spi/merge/AbstractSplitBrainMergePolicyTest.java
  hazelcast/src/test/java/com/hazelcast/test/SplitBrainTestSupport.java
Labels: Team: Core, Type: Defect, Type: Enhancement

#12331 Moved client side query cache test to map impl package
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/querycache/ClientEvictionTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/querycache/ClientQueryCacheBasicTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/querycache/ClientQueryCacheClientContextTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/querycache/ClientQueryCacheConfigTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/querycache/ClientQueryCacheCreateDestroyTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/querycache/ClientQueryCacheDestroyResourcesTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/querycache/ClientQueryCacheEventHandlingTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/querycache/ClientQueryCacheEventLostListenerTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/querycache/ClientQueryCacheIndexTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/querycache/ClientQueryCacheListenerTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/querycache/ClientQueryCacheMemoryLeakTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/querycache/ClientQueryCacheMethodsWithPredicateTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/querycache/ClientQueryCacheRecoveryUponEventLossTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/querycache/ClientQueryCacheSimpleStressTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/querycache/ClientQueryCacheTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/querycache/ClientQueryCacheXmlConfigWithWildcardTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/querycache/subscriber/TestClientSubscriberContext.java
Labels: Team: Core

#12322 Removed interface SplitBrainAwareDataContainer
  hazelcast/src/main/java/com/hazelcast/cache/impl/ICacheRecordStore.java
  hazelcast/src/main/java/com/hazelcast/cardinality/impl/CardinalityEstimatorContainer.java
  hazelcast/src/main/java/com/hazelcast/collection/impl/collection/CollectionContainer.java
  hazelcast/src/main/java/com/hazelcast/collection/impl/queue/QueueContainer.java
  hazelcast/src/main/java/com/hazelcast/concurrent/atomiclong/AtomicLongContainer.java
  hazelcast/src/main/java/com/hazelcast/concurrent/atomiclong/operations/MergeOperation.java
  hazelcast/src/main/java/com/hazelcast/concurrent/atomicreference/AtomicReferenceContainer.java
  hazelcast/src/main/java/com/hazelcast/concurrent/atomicreference/operations/MergeOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/DefaultRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/RecordStore.java
  hazelcast/src/main/java/com/hazelcast/multimap/impl/MultiMapContainer.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/record/AbstractReplicatedRecordStore.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/record/ReplicatedRecordStore.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferContainer.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorContainer.java
  hazelcast/src/main/java/com/hazelcast/spi/SplitBrainAwareDataContainer.java
  hazelcast/src/main/java/com/hazelcast/spi/merge/SplitBrainEntryViews.java
  hazelcast/src/test/java/com/hazelcast/replicatedmap/impl/record/LazyIteratorTest.java
Labels: Team: Core, Type: Enhancement

#12324 Removed ClientMessageHandlerImpl
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientChannelInitializer.java
  hazelcast-client/src/test/java/com/hazelcast/client/test/TestClientRegistry.java
  hazelcast/src/main/java/com/hazelcast/client/ClientEngine.java
  hazelcast/src/main/java/com/hazelcast/client/impl/ClientEngineImpl.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/util/ClientMessageDecoder.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/util/ClientMessageHandler.java
  hazelcast/src/main/java/com/hazelcast/nio/tcp/ClientMessageHandlerImpl.java
  hazelcast/src/main/java/com/hazelcast/nio/tcp/MemberChannelInitializer.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/ClientMessageSplitAndBuildTest.java
  hazelcast/src/test/java/com/hazelcast/nio/tcp/ClientMessageDecoderTest.java
Labels: Team: Client, Team: Core, Type: Cleanup

#12265 Introduces new built-in quorum functions
  hazelcast-spring/src/main/java/com/hazelcast/spring/HazelcastConfigBeanDefinitionParser.java
  hazelcast-spring/src/main/resources/hazelcast-spring-3.10.xsd
  hazelcast-spring/src/test/java/com/hazelcast/spring/TestFullApplicationContext.java
  hazelcast-spring/src/test/resources/com/hazelcast/spring/fullConfig-applicationContext-hazelcast.xml
  hazelcast/src/main/java/com/hazelcast/config/AbstractXmlConfigHelper.java
  hazelcast/src/main/java/com/hazelcast/config/ConfigXmlGenerator.java
  hazelcast/src/main/java/com/hazelcast/config/ProbabilisticQuorumConfigBuilder.java
  hazelcast/src/main/java/com/hazelcast/config/QuorumConfig.java
  hazelcast/src/main/java/com/hazelcast/config/QuorumConfigBuilder.java
  hazelcast/src/main/java/com/hazelcast/config/RecentlyActiveQuorumConfigBuilder.java
  hazelcast/src/main/java/com/hazelcast/config/XmlConfigBuilder.java
  hazelcast/src/main/java/com/hazelcast/instance/AbstractMember.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/fd/ClusterFailureDetectorType.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/fd/PhiAccrualClusterFailureDetector.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/fd/PingFailureDetector.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterHeartbeatManager.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/operations/HeartbeatOp.java
  hazelcast/src/main/java/com/hazelcast/quorum/HeartbeatAware.java
  hazelcast/src/main/java/com/hazelcast/quorum/PingAware.java
  hazelcast/src/main/java/com/hazelcast/quorum/QuorumFunction.java
  hazelcast/src/main/java/com/hazelcast/quorum/impl/AbstractPingAwareQuorumFunction.java
  hazelcast/src/main/java/com/hazelcast/quorum/impl/MemberCountQuorumFunction.java
  hazelcast/src/main/java/com/hazelcast/quorum/impl/ProbabilisticQuorumFunction.java
  hazelcast/src/main/java/com/hazelcast/quorum/impl/QuorumImpl.java
  hazelcast/src/main/java/com/hazelcast/quorum/impl/QuorumServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/quorum/impl/RecentlyActiveQuorumFunction.java
  hazelcast/src/main/java/com/hazelcast/spi/properties/GroupProperty.java
  hazelcast/src/main/java/com/hazelcast/spi/properties/HazelcastProperties.java
  hazelcast/src/main/resources/hazelcast-config-3.10.xsd
  hazelcast/src/test/java/com/hazelcast/config/ConfigCompatibilityChecker.java
  hazelcast/src/test/java/com/hazelcast/config/ConfigXmlGeneratorTest.java
  hazelcast/src/test/java/com/hazelcast/config/XMLConfigBuilderTest.java
  hazelcast/src/test/java/com/hazelcast/internal/cluster/fd/ClusterFailureDetectorTest.java
  hazelcast/src/test/java/com/hazelcast/internal/cluster/fd/PingFailureDetectorTest.java
  hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/MembershipFailureTest.java
  hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/MembershipFailureTest_withTCP.java
  hazelcast/src/test/java/com/hazelcast/quorum/QuorumTest.java
  hazelcast/src/test/java/com/hazelcast/quorum/impl/AbstractQuorumFunctionTest.java
  hazelcast/src/test/java/com/hazelcast/quorum/impl/ProbabilisticQuorumFunctionTest.java
  hazelcast/src/test/java/com/hazelcast/quorum/impl/RecentlyActiveQuorumFunctionTest.java
  hazelcast/src/test/java/com/hazelcast/test/starter/HazelcastAPIDelegatingClassloader.java
  hazelcast/src/test/java/com/hazelcast/test/starter/HazelcastProxyFactory.java
  hazelcast/src/test/java/com/hazelcast/test/starter/ProxyInvocationHandler.java
  hazelcast/src/test/resources/hazelcast-fullconfig.xml
Labels: Team: Core, Type: Enhancement

#12290 Cleanup of EvictionTest
  hazelcast/src/test/java/com/hazelcast/map/EvictionTest.java
Labels: Team: Core, Type: Cleanup, Type: Defect

#12333 ConsoleApp - String handling improvements
  hazelcast/src/main/java/com/hazelcast/console/ConsoleApp.java
  hazelcast/src/main/java/com/hazelcast/internal/management/ConsoleCommandHandler.java
  hazelcast/src/main/java/com/hazelcast/util/StringUtil.java
  hazelcast/src/test/java/com/hazelcast/util/StringUtilTest.java
Labels: Team: Core, Team: Integration, Type: Defect

#12277 Minor NioChannelWriter.poll simplification
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioOutboundPipeline.java
Labels: Estimation: S, Priority: Low, Source: Internal, Type: Cleanup

#12332 Revert "Added TLS host verification support."
  hazelcast-client/src/main/java/com/hazelcast/client/config/XmlClientConfigBuilder.java
  hazelcast-client/src/main/resources/hazelcast-client-config-3.10.xsd
  hazelcast-client/src/main/resources/hazelcast-client-full.xml
  hazelcast-client/src/test/java/com/hazelcast/client/config/XmlClientConfigBuilderTest.java
  hazelcast-spring/src/main/java/com/hazelcast/spring/AbstractHazelcastBeanDefinitionParser.java
  hazelcast-spring/src/main/java/com/hazelcast/spring/HazelcastClientBeanDefinitionParser.java
  hazelcast-spring/src/main/java/com/hazelcast/spring/HazelcastConfigBeanDefinitionParser.java
  hazelcast-spring/src/main/resources/hazelcast-spring-3.10.xsd
  hazelcast-spring/src/test/java/com/hazelcast/spring/TestClientNetworkConfig.java
  hazelcast-spring/src/test/java/com/hazelcast/spring/TestFullApplicationContext.java
  hazelcast-spring/src/test/resources/com/hazelcast/spring/clientNetworkConfig-applicationContext.xml
  hazelcast-spring/src/test/resources/com/hazelcast/spring/fullConfig-applicationContext-hazelcast.xml
  hazelcast/src/main/java/com/hazelcast/config/ConfigXmlGenerator.java
  hazelcast/src/main/java/com/hazelcast/config/HostVerificationConfig.java
  hazelcast/src/main/java/com/hazelcast/config/SSLConfig.java
  hazelcast/src/main/java/com/hazelcast/config/XmlConfigBuilder.java
  hazelcast/src/main/java/com/hazelcast/nio/ssl/TlsHostVerifier.java
  hazelcast/src/main/resources/hazelcast-config-3.10.xsd
  hazelcast/src/test/java/com/hazelcast/config/ConfigCompatibilityChecker.java
  hazelcast/src/test/java/com/hazelcast/config/ConfigXmlGeneratorTest.java
  hazelcast/src/test/java/com/hazelcast/config/HostVerificationConfigTest.java
  hazelcast/src/test/java/com/hazelcast/config/XMLConfigBuilderTest.java
Labels: Team: Core

#12338 Minor client connection cleanup
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnection.java
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/DefaultClientConnectionStrategy.java
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/HeartbeatManager.java
Labels: Team: Client, Type: Cleanup

#12315 Fix Flake ID backpressure test
  hazelcast-client/src/test/java/com/hazelcast/client/flakeidgen/impl/FlakeIdGenerator_ClientBackpressureTest.java
  hazelcast/src/test/java/com/hazelcast/flakeidgen/impl/FlakeIdGenerator_AbstractBackpressureTest.java
  hazelcast/src/test/java/com/hazelcast/flakeidgen/impl/FlakeIdGenerator_MemberBackpressureTest.java
Labels: Team: Core, Type: Test-Failure

#12302 [#10885] Fix ClientStateListenerTest.testClientReconnecModeOffDisconn…
  hazelcast-client/src/test/java/com/hazelcast/client/util/ClientStateListenerTest.java
Labels: DR3, Team: Client

#12339 The ClientChannelInitializer reuses the ClientMessageEncoder
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientChannelInitializer.java
Labels: Team: Client, Type: Cleanup

#12340 Moved ClientMessageEncoder
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientChannelInitializer.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/util/ClientMessageEncoder.java
  hazelcast/src/main/java/com/hazelcast/nio/tcp/MemberChannelInitializer.java
  hazelcast/src/test/java/com/hazelcast/client/impl/protocol/util/ClientMessageDecoderTest.java
  hazelcast/src/test/java/com/hazelcast/client/impl/protocol/util/ClientMessageEncoderTest.java
Labels: Team: Client, Type: Cleanup

#12343 [#10885] Fix ClientStateListenerTest.testClientReconnecModeOffDisconn…
  hazelcast-client/src/test/java/com/hazelcast/client/util/ClientStateListenerTest.java
Labels: Backport, Team: Client, Type: Defect

#11789 Convert merging member to lite-member before start of split brain healing
  hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/CacheOperationProvider.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/CachePartitionSegment.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/CacheSplitBrainHandlerService.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/DefaultOperationProvider.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/operation/CacheMergeOperation.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterMergeTask.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/MembershipManager.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/operations/PromoteLiteMemberOp.java
  hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/invalidation/Invalidator.java
  hazelcast/src/main/java/com/hazelcast/map/impl/EntryViews.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapSplitBrainHandlerService.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/AbstractRecordStore.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/InvokeOnPartitions.java
  hazelcast/src/test/java/com/hazelcast/cache/merge/CacheSplitBrainTest.java
  hazelcast/src/test/java/com/hazelcast/cache/merge/LegacyCacheSplitBrainTest.java
  hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/MemberListJoinVersionTest.java
  hazelcast/src/test/java/com/hazelcast/map/merge/MapSplitBrainStressTest.java
  hazelcast/src/test/java/com/hazelcast/replicatedmap/merge/LegacyReplicatedMapSplitBrainTest.java
  hazelcast/src/test/java/com/hazelcast/replicatedmap/merge/ReplicatedMapSplitBrainTest.java
Labels: Team: Core, Type: Cleanup

#12349 Covariance of projection output in EventJournal
  hazelcast-client/src/main/java/com/hazelcast/client/cache/impl/ClientCacheProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxy.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/journal/CacheEventJournalReadOperation.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/journal/CacheEventJournalReadResultSetImpl.java
  hazelcast/src/main/java/com/hazelcast/journal/EventJournalReader.java
  hazelcast/src/main/java/com/hazelcast/map/impl/journal/MapEventJournalReadOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/journal/MapEventJournalReadResultSetImpl.java
  hazelcast/src/main/java/com/hazelcast/map/impl/proxy/MapProxyImpl.java
Labels: Type: Defect

#12354 Upgraded JMH version to a more recent one
  pom.xml
Labels: Type: Cleanup

#12179 return narrow return type at spring HazelcastCache#getNativeCache
  hazelcast-spring/src/main/java/com/hazelcast/spring/cache/HazelcastCache.java
Labels: Team: Core, Team: Integration

#12355 Changed JMH version from 1.20 to 1.16 due to java 6
  pom.xml
Labels: Type: Defect

#12347 Added merge policies to ConfigValidator
  hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxyUtil.java
  hazelcast/src/main/java/com/hazelcast/collection/impl/collection/AbstractCollectionProxyImpl.java
  hazelcast/src/main/java/com/hazelcast/collection/impl/queue/QueueProxyImpl.java
  hazelcast/src/main/java/com/hazelcast/collection/impl/queue/QueueProxySupport.java
  hazelcast/src/main/java/com/hazelcast/collection/impl/queue/QueueService.java
  hazelcast/src/main/java/com/hazelcast/concurrent/atomiclong/AtomicLongService.java
  hazelcast/src/main/java/com/hazelcast/concurrent/atomicreference/AtomicReferenceService.java
  hazelcast/src/main/java/com/hazelcast/internal/config/ConfigValidator.java
  hazelcast/src/main/java/com/hazelcast/multimap/impl/MultiMapProxySupport.java
  hazelcast/src/main/java/com/hazelcast/multimap/impl/MultiMapService.java
  hazelcast/src/main/java/com/hazelcast/multimap/impl/ObjectMultiMapProxy.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapProxy.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapService.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferService.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/DistributedScheduledExecutorService.java
  hazelcast/src/test/java/com/hazelcast/internal/config/AbstractConfigValidatorMergePolicyTest.java
  hazelcast/src/test/java/com/hazelcast/internal/config/ConfigValidationMergePolicyAtomicLongTest.java
  hazelcast/src/test/java/com/hazelcast/internal/config/ConfigValidationMergePolicyAtomicReferenceTest.java
  hazelcast/src/test/java/com/hazelcast/internal/config/ConfigValidationMergePolicyCacheTest.java
  hazelcast/src/test/java/com/hazelcast/internal/config/ConfigValidationMergePolicyIntegrationTest.java
  hazelcast/src/test/java/com/hazelcast/internal/config/ConfigValidationMergePolicyListTest.java
  hazelcast/src/test/java/com/hazelcast/internal/config/ConfigValidationMergePolicyMapTest.java
  hazelcast/src/test/java/com/hazelcast/internal/config/ConfigValidationMergePolicyMultiMapTest.java
  hazelcast/src/test/java/com/hazelcast/internal/config/ConfigValidationMergePolicyQueueTest.java
  hazelcast/src/test/java/com/hazelcast/internal/config/ConfigValidationMergePolicyReplicatedMapTest.java
  hazelcast/src/test/java/com/hazelcast/internal/config/ConfigValidationMergePolicyRingbufferTest.java
  hazelcast/src/test/java/com/hazelcast/internal/config/ConfigValidationMergePolicyScheduledExecutorTest.java
  hazelcast/src/test/java/com/hazelcast/internal/config/ConfigValidationMergePolicySetTest.java
  hazelcast/src/test/java/com/hazelcast/internal/config/ConfigValidatorTest.java
Labels: Team: Core, Type: Enhancement

#12317 Added flake id generator stats
  hazelcast-client/src/main/java/com/hazelcast/client/impl/ClientDynamicClusterConfig.java
  hazelcast-spring/src/main/resources/hazelcast-spring-3.10.xsd
  hazelcast-spring/src/test/java/com/hazelcast/spring/TestFullApplicationContext.java
  hazelcast-spring/src/test/resources/com/hazelcast/spring/fullConfig-applicationContext-hazelcast.xml
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/dynamicconfig/AddFlakeIdGeneratorConfigMessageTask.java
  hazelcast/src/main/java/com/hazelcast/config/ConfigXmlGenerator.java
  hazelcast/src/main/java/com/hazelcast/config/FlakeIdGeneratorConfig.java
  hazelcast/src/main/java/com/hazelcast/config/FlakeIdGeneratorConfigReadOnly.java
  hazelcast/src/main/java/com/hazelcast/config/XmlConfigBuilder.java
  hazelcast/src/main/java/com/hazelcast/flakeidgen/impl/FlakeIdGeneratorProxy.java
  hazelcast/src/main/java/com/hazelcast/flakeidgen/impl/FlakeIdGeneratorService.java
  hazelcast/src/main/java/com/hazelcast/internal/management/TimedMemberStateFactory.java
  hazelcast/src/main/java/com/hazelcast/monitor/LocalFlakeIdGeneratorStats.java
  hazelcast/src/main/java/com/hazelcast/monitor/MemberState.java
  hazelcast/src/main/java/com/hazelcast/monitor/impl/LocalFlakeIdGeneratorStatsImpl.java
  hazelcast/src/main/java/com/hazelcast/monitor/impl/MemberStateImpl.java
  hazelcast/src/main/resources/hazelcast-config-3.10.xsd
  hazelcast/src/main/resources/hazelcast-default.xml
  hazelcast/src/main/resources/hazelcast-full-example.xml
  hazelcast/src/test/java/com/hazelcast/config/ConfigCompatibilityChecker.java
  hazelcast/src/test/java/com/hazelcast/config/ConfigXmlGeneratorTest.java
  hazelcast/src/test/java/com/hazelcast/config/XMLConfigBuilderTest.java
  hazelcast/src/test/java/com/hazelcast/flakeidgen/impl/FlakeIdGeneratorProxyTest.java
  hazelcast/src/test/java/com/hazelcast/flakeidgen/impl/FlakeIdGenerator_MemberIntegrationTest.java
  hazelcast/src/test/java/com/hazelcast/internal/dynamicconfig/DynamicConfigTest.java
  hazelcast/src/test/java/com/hazelcast/monitor/impl/MemberStateImplTest.java
  hazelcast/src/test/resources/hazelcast-fullconfig.xml
Labels: Type: Enhancement

#12357 [BACKPORT] Remove outdated warnings regarding TTL from IMap's javadoc
  hazelcast/src/main/java/com/hazelcast/core/IMap.java
  hazelcast/src/test/java/com/hazelcast/map/EvictionTest.java
Labels: Team: Core, Type: Enhancement

#12359 Do not resolve Cache KV types while creating cache proxy
  hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/operation/CacheCreateConfigOperation.java
Labels: Team: Core, Type: Defect

#12364 Improved backup testing utils
  hazelcast/src/test/java/com/hazelcast/cache/CacheTestUtil.java
  hazelcast/src/test/java/com/hazelcast/cardinality/CardinalityEstimatorTestUtil.java
  hazelcast/src/test/java/com/hazelcast/collection/impl/CollectionTestUtil.java
  hazelcast/src/test/java/com/hazelcast/concurrent/ConcurrencyTestUtil.java
  hazelcast/src/test/java/com/hazelcast/concurrent/atomiclong/AtomicLongSplitBrainTest.java
  hazelcast/src/test/java/com/hazelcast/concurrent/atomicreference/AtomicReferenceSplitBrainTest.java
  hazelcast/src/test/java/com/hazelcast/map/MapTestUtil.java
  hazelcast/src/test/java/com/hazelcast/multimap/MultiMapTestUtil.java
  hazelcast/src/test/java/com/hazelcast/replicatedmap/merge/ReplicatedMapSplitBrainTest.java
  hazelcast/src/test/java/com/hazelcast/ringbuffer/RingbufferSplitBrainTest.java
  hazelcast/src/test/java/com/hazelcast/ringbuffer/RingbufferTestUtil.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/ScheduledExecutorSplitBrainTest.java
Labels: Team: Core, Type: Enhancement

#12365 Add support for -beta-x suffix when parsing hazelcast version
  hazelcast/src/main/java/com/hazelcast/util/StringUtil.java
  hazelcast/src/test/java/com/hazelcast/instance/BuildInfoProviderTest.java
  hazelcast/src/test/java/com/hazelcast/util/StringUtilTest.java
  hazelcast/src/test/java/com/hazelcast/version/MemberVersionTest.java
Labels: Team: Core, Type: Enhancement

#12360 Add group password information to member logs
  hazelcast/src/main/java/com/hazelcast/instance/Node.java
Labels: Team: Core

#12381 MembershipFailureTest: Bad test fixed
  hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/MembershipFailureTest.java
Labels: Team: Core, Type: Defect

#12380 Refine contract of MapClearedListener
  hazelcast/src/main/java/com/hazelcast/map/listener/MapClearedListener.java
  hazelcast/src/test/java/com/hazelcast/multimap/MultiMapListenerTest.java
Labels: Interface: IMap, Interface: MultiMap, Team: Core, Type: Defect

#12366 [#4356] Fix RepartitioningStressTest
  hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/RepartitioningStressTest.java
Labels: DR3, Team: Core, Type: Test-Failure

#12377 ConfigCheck: Remove branch 3.8 compatibility branch
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ConfigCheck.java
  hazelcast/src/test/java/com/hazelcast/cluster/ConfigCheckTest.java
Labels: Team: Core, Type: Enhancement

#12386 Cancel AuthTimeoutTask
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java
Labels: Team: Client, Type: Defect

#12387 Cancel AuthTimeoutTask
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java
Labels: Backport, Team: Client, Type: Defect

#12383 Fix backpressure test
  hazelcast/src/test/java/com/hazelcast/flakeidgen/impl/FlakeIdGenerator_AbstractBackpressureTest.java
Labels: Interface: FlakeIDGenerator, Team: Core, Type: Test-Failure

#12293 Fix MapListenerTest
  hazelcast/src/test/java/com/hazelcast/core/standalone/LongRunningTest.java
  hazelcast/src/test/java/com/hazelcast/map/MapListenerTest.java
  hazelcast/src/test/java/com/hazelcast/map/impl/eviction/PluggableMemoryInfoAccessorTest.java
  hazelcast/src/test/java/com/hazelcast/map/standalone/SimpleMapTest.java
  hazelcast/src/test/java/com/hazelcast/replicatedmap/standalone/SimpleReplicatedMapTest.java
Labels: Team: Core, Type: Test-Failure

#12395 Bad test fixed: Invocation_OnBackupLeftTest
  hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/Invocation_OnBackupLeftTest.java
Labels: Team: Core, Type: Defect

#12393 Improve operation descriptor of slow operation detector
  hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/slowoperationdetector/SlowOperationLog.java
Labels: Team: Core, Type: Enhancement

#12391 Fix event journal replication
  hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/CachePartitionSegment.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/ICacheRecordStore.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/journal/RingbufferCacheEventJournalImpl.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/operation/CachePutAllBackupOperation.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/operation/CachePutBackupOperation.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/operation/CacheReplicationOperation.java
  hazelcast/src/main/java/com/hazelcast/journal/EventJournal.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapServiceContextImpl.java
  hazelcast/src/main/java/com/hazelcast/map/impl/journal/RingbufferMapEventJournalImpl.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/DefaultRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/RecordStore.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/operations/MergeOperation.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/operations/ReplicationOperation.java
  hazelcast/src/test/java/com/hazelcast/cache/impl/journal/AdvancedCacheJournalTest.java
  hazelcast/src/test/java/com/hazelcast/map/impl/journal/AdvancedMapJournalTest.java
Labels: Team: Core, Type: Defect

#12400 Introduce hazelcast.test.additionalJvmArguments Maven property
  pom.xml
Labels: Type: Enhancement

#12389 Remove unused fields in ConfigCheck. Fixes FindBugs findings.
  hazelcast/src/main/java/com/hazelcast/instance/Node.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ConfigCheck.java
  hazelcast/src/test/java/com/hazelcast/cluster/ConfigCheckTest.java
Labels: Team: Core, Type: Cleanup

#12392 Event journal cleanup
  hazelcast-client/src/main/java/com/hazelcast/client/cache/impl/ClientCacheProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java
  hazelcast-client/src/test/java/com/hazelcast/client/cache/ClientBasicCacheJournalTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/cache/ClientCacheEventJournalBasicTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/ClientMapEventJournalBasicTest.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxy.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/journal/CacheEventJournal.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/journal/CacheEventJournalReadOperation.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/journal/CacheEventJournalSubscribeOperation.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/journal/DeserializingEventJournalCacheEvent.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/journal/InternalEventJournalCacheEvent.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/cache/CacheEventJournalSubscribeTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/MapEventJournalSubscribeTask.java
  hazelcast/src/main/java/com/hazelcast/config/Config.java
  hazelcast/src/main/java/com/hazelcast/internal/journal/EventJournal.java
  hazelcast/src/main/java/com/hazelcast/internal/journal/EventJournalDataSerializerHook.java
  hazelcast/src/main/java/com/hazelcast/internal/journal/EventJournalInitialSubscriberState.java
  hazelcast/src/main/java/com/hazelcast/internal/journal/EventJournalReadOperation.java
  hazelcast/src/main/java/com/hazelcast/internal/journal/EventJournalReader.java
  hazelcast/src/main/java/com/hazelcast/internal/journal/package-info.java
  hazelcast/src/main/java/com/hazelcast/map/impl/journal/DeserializingEventJournalMapEvent.java
  hazelcast/src/main/java/com/hazelcast/map/impl/journal/InternalEventJournalMapEvent.java
  hazelcast/src/main/java/com/hazelcast/map/impl/journal/MapEventJournal.java
  hazelcast/src/main/java/com/hazelcast/map/impl/journal/MapEventJournalReadOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/journal/MapEventJournalSubscribeOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/proxy/MapProxyImpl.java
  hazelcast/src/main/java/com/hazelcast/map/journal/package-info.java
  hazelcast/src/main/resources/META-INF/services/com.hazelcast.DataSerializerHook
  hazelcast/src/test/java/com/hazelcast/cache/impl/journal/BasicCacheJournalTest.java
  hazelcast/src/test/java/com/hazelcast/cache/impl/journal/CacheEventJournalBasicTest.java
  hazelcast/src/test/java/com/hazelcast/cache/impl/journal/CacheEventJournalBounceTest.java
  hazelcast/src/test/java/com/hazelcast/cache/impl/journal/EventJournalCacheDataStructureAdapter.java
  hazelcast/src/test/java/com/hazelcast/cache/impl/journal/EventJournalCacheEventAdapter.java
  hazelcast/src/test/java/com/hazelcast/journal/AbstractEventJournalBasicTest.java
  hazelcast/src/test/java/com/hazelcast/journal/AbstractEventJournalBounceTest.java
  hazelcast/src/test/java/com/hazelcast/journal/EventJournalDataStructureAdapter.java
  hazelcast/src/test/java/com/hazelcast/journal/EventJournalEventAdapter.java
  hazelcast/src/test/java/com/hazelcast/journal/EventJournalTestContext.java
  hazelcast/src/test/java/com/hazelcast/journal/NewValueIncrementingProjection.java
  hazelcast/src/test/java/com/hazelcast/journal/NewValueParityPredicate.java
  hazelcast/src/test/java/com/hazelcast/journal/TruePredicate.java
  hazelcast/src/test/java/com/hazelcast/map/impl/journal/BasicMapJournalTest.java
  hazelcast/src/test/java/com/hazelcast/map/impl/journal/EventJournalMapDataStructureAdapter.java
  hazelcast/src/test/java/com/hazelcast/map/impl/journal/EventJournalMapEventAdapter.java
  hazelcast/src/test/java/com/hazelcast/map/impl/journal/MapEventJournalBasicTest.java
  hazelcast/src/test/java/com/hazelcast/map/impl/journal/MapEventJournalBounceTest.java
Labels: Team: Core, Type: Enhancement

#12404 Relax LoggingScheduledExecutorTest test timeout
  hazelcast/src/test/java/com/hazelcast/util/executor/LoggingScheduledExecutorTest.java
Labels: Team: Core, Type: Test-Failure

#12410 Fix invalid stats on IScheduledExecutor
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorContainer.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledTaskStatisticsImpl.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/TaskRunner.java
Labels: Team: Core, Type: Defect

#12397 Relax IScheduledExecutor stats_manyRepetitionsTask assertions
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorContainer.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledTaskDescriptor.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/ScheduledExecutorServiceSlowTest.java
Labels: Team: Core, Type: Test-Failure

#12408 Use eventual assertions for backups in map & cache split-healing tests
  hazelcast/src/test/java/com/hazelcast/cache/CacheTestUtil.java
  hazelcast/src/test/java/com/hazelcast/cache/merge/CacheSplitBrainTest.java
  hazelcast/src/test/java/com/hazelcast/map/MapTestUtil.java
  hazelcast/src/test/java/com/hazelcast/map/merge/LegacyMapSplitBrainTest.java
  hazelcast/src/test/java/com/hazelcast/map/merge/MapSplitBrainTest.java
  hazelcast/src/test/java/com/hazelcast/test/TestTaskExecutorUtil.java
  hazelcast/src/test/java/com/hazelcast/test/backup/BackupAccessor.java
  hazelcast/src/test/java/com/hazelcast/test/backup/TestBackupUtils.java
Labels: Interface: IMap, Team: Core, Type: Defect

#12411 Rename Maven property hazelcast.test.additionalJvmArguments to extraVmArgs
  pom.xml
Labels: Type: Enhancement

#12394 Add clientVersion to statistics
  hazelcast-client/src/main/java/com/hazelcast/client/impl/statistics/Statistics.java
  hazelcast-client/src/test/java/com/hazelcast/client/statistics/ClientStatisticsTest.java
Labels: Team: Client, Team: Integration, Type: Enhancement

#12382 ExecutorQuorumWriteTest: Tests more resilient against JVM hiccups
  hazelcast-client/src/test/java/com/hazelcast/client/quorum/executor/ClientExecutorQuorumWriteTest.java
  hazelcast/src/test/java/com/hazelcast/quorum/executor/ExecutorQuorumWriteTest.java
Labels: Interface: IExecutor, Team: Core, Type: Defect

#12413 Aggregate tests in MultiMap Quorum Test Ignored
  hazelcast/src/test/java/com/hazelcast/quorum/multimap/MultiMapQuorumReadTest.java
Labels: Interface: MultiMap, Team: Core, Type: Defect

#12416 [BACKPORT] Add clientVersion to statistics
  hazelcast-client/src/main/java/com/hazelcast/client/impl/statistics/Statistics.java
  hazelcast-client/src/test/java/com/hazelcast/client/statistics/ClientStatisticsTest.java
Labels: Team: Client, Team: Integration, Type: Enhancement

#12337 Cover MergePolicy for replicatedmap in ConfigXmlGeneratorTest
  hazelcast/src/test/java/com/hazelcast/config/ConfigXmlGeneratorTest.java
Labels: Team: Core, Type: Enhancement

#12406 Fix MemberListJoinVersionTest
  hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/MemberListJoinVersionTest.java
Labels: Team: Core

#12388 Add warning to IMap.replace() which may return false even if the operation finishes successfully
  hazelcast/src/main/java/com/hazelcast/core/IMap.java
Labels: Interface: IMap, Team: Core, Type: Enhancement

#12421 Assert Evictor is running in partition threads
  hazelcast/src/main/java/com/hazelcast/map/impl/eviction/EvictorImpl.java
Labels: Team: Core

#10416 Eliminate unconditional waiting in node join/shutdown
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/AbstractJoiner.java
  hazelcast/src/test/java/com/hazelcast/test/mocknetwork/MockJoiner.java
Labels: Team: Core, Type: Enhancement

#12426 Pipeline has now own error handler
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioEventLoopGroup.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioInboundPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioOutboundPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioThread.java
Labels: Team: Core, Type: Cleanup

#12399 Write IMap javadoc on expiration and eviction
  hazelcast/src/main/java/com/hazelcast/core/IMap.java
Labels: Team: Core, Team: Documentation, Type: Enhancement

#12422 Filter throwable peeling in MessageTask exception handling
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/AbstractMessageTask.java
Labels: Team: Client, Team: Core, Type: Defect

#12439 Minor renames in Channel
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnection.java
  hazelcast/src/main/java/com/hazelcast/internal/diagnostics/OverloadedConnectionsPlugin.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/AbstractChannel.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/Channel.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioChannel.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioEventLoopGroup.java
  hazelcast/src/main/java/com/hazelcast/nio/tcp/TcpIpConnection.java
  hazelcast/src/main/java/com/hazelcast/nio/tcp/TcpIpConnectionManager.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/iobalancer/IOBalancerStressTest.java
  hazelcast/src/test/java/com/hazelcast/nio/tcp/PacketDecoderTest.java
  hazelcast/src/test/java/com/hazelcast/nio/tcp/TcpIpConnection_AbstractTransferStressTest.java
Labels: Team: Core, Type: Cleanup

#12435 Create proxies of a client on cluster back when cluster restarted
  hazelcast-client/src/main/java/com/hazelcast/client/impl/HazelcastClientInstanceImpl.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/ProxyManager.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClusterListenerSupport.java
  hazelcast-client/src/test/java/com/hazelcast/client/proxy/DistributedObjectListenerTest.java
  hazelcast/src/test/java/com/hazelcast/map/mapstore/MapLoaderTest.java
Labels: Team: Client, Type: Defect

#12370 Map&Cache SplitBrainHandlerService unifications
  hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/CacheMergeRunnable.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/CacheSplitBrainHandlerService.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/ICacheRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapMergeRunnable.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapServiceContextImpl.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapSplitBrainHandlerService.java
  hazelcast/src/main/java/com/hazelcast/map/impl/PartitionContainer.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractMergeRunnable.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractSplitBrainHandlerService.java
  hazelcast/src/test/java/com/hazelcast/map/merge/MapSplitBrainTest.java
Labels: Interface: ICache, Interface: IMap, Team: Core, Type: Enhancement

#12442 Fixes typo in group-password related log message.
  hazelcast/src/main/java/com/hazelcast/instance/Node.java
Labels: Team: Core

#12430 Fix TxnPollOperation afterRun() null-check bug
  hazelcast/src/main/java/com/hazelcast/collection/impl/txnqueue/operations/TxnPollOperation.java
  hazelcast/src/test/java/com/hazelcast/collection/impl/txnqueue/TransactionQueueTest.java
Labels: Interface: IQueue, Team: Core, Type: Defect

#12436 Quorum clean up
  hazelcast/src/main/java/com/hazelcast/quorum/QuorumFunction.java
  hazelcast/src/main/java/com/hazelcast/quorum/impl/AbstractPingAwareQuorumFunction.java
  hazelcast/src/main/java/com/hazelcast/quorum/impl/ProbabilisticQuorumFunction.java
  hazelcast/src/main/java/com/hazelcast/quorum/impl/QuorumImpl.java
  hazelcast/src/main/java/com/hazelcast/quorum/impl/QuorumServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/quorum/impl/RecentlyActiveQuorumFunction.java
  hazelcast/src/test/java/com/hazelcast/quorum/QuorumTest.java
Labels: Team: Core, Type: Cleanup, Type: Defect

#12427 Renamed NioPipeline ioThread to owner.
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioInboundPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioOutboundPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioThread.java
Labels: Team: Core, Type: Cleanup

#12428 Change some private/protected constructors to public to extend them on hazelcast-jet-spring module
  hazelcast-spring/src/main/java/com/hazelcast/spring/HazelcastClientBeanDefinitionParser.java
  hazelcast-spring/src/main/java/com/hazelcast/spring/HazelcastConfigBeanDefinitionParser.java
Labels: Source: Internal, Team: Core, Type: Enhancement

#12448 Publish spring test-jars to maven
  hazelcast-spring/pom.xml
Labels: Source: Internal, Team: Core, Type: Enhancement

#12445 Minor IO cleanup
  hazelcast/src/main/java/com/hazelcast/internal/networking/AbstractChannel.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/Channel.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/ChannelCloseListener.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/ChannelErrorHandler.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/OutboundFrame.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/ChannelInboundHandlerWithCounters.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/MigratablePipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioChannel.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioEventLoopGroup.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioInboundPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioOutboundPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioThread.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/SelectorOptimizer.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/iobalancer/IOBalancer.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/iobalancer/LoadMigrationStrategy.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/iobalancer/LoadTracker.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/package-info.java
  hazelcast/src/main/java/com/hazelcast/nio/IOUtil.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/iobalancer/IOBalancerStressTest.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/iobalancer/LoadMigrationStrategyTest.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/iobalancer/LoadTrackerTest.java
Labels: Type: Cleanup

#12451 Set interrupted flag back on catching InterruptedExceptions
  hazelcast-client/src/main/java/com/hazelcast/client/cache/impl/AbstractClientInternalCacheProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/console/ClientConsoleApp.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientLockProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientMultiMapProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientQueueProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientSemaphoreProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/txn/ClientTxnQueueProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/ProxyManager.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientExecutionServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractInternalCacheProxy.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/executorservice/AbstractExecutorServiceCancelMessageTask.java
  hazelcast/src/main/java/com/hazelcast/collection/impl/queue/QueueProxyImpl.java
  hazelcast/src/main/java/com/hazelcast/collection/impl/txnqueue/TransactionalQueueProxy.java
  hazelcast/src/main/java/com/hazelcast/concurrent/lock/LockProxySupport.java
  hazelcast/src/main/java/com/hazelcast/concurrent/semaphore/SemaphoreProxy.java
  hazelcast/src/main/java/com/hazelcast/console/ConsoleApp.java
  hazelcast/src/main/java/com/hazelcast/console/SimulateLoadTask.java
  hazelcast/src/main/java/com/hazelcast/flakeidgen/impl/FlakeIdGeneratorProxy.java
  hazelcast/src/main/java/com/hazelcast/instance/HazelcastInstanceFactory.java
  hazelcast/src/main/java/com/hazelcast/instance/Node.java
  hazelcast/src/main/java/com/hazelcast/internal/ascii/TextCommandServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/AbstractJoiner.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/MulticastJoiner.java
  hazelcast/src/main/java/com/hazelcast/internal/diagnostics/HealthMonitor.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/InternalPartitionServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/PartitionReplicaStateChecker.java
  hazelcast/src/main/java/com/hazelcast/map/impl/LocalMapStatsProvider.java
  hazelcast/src/main/java/com/hazelcast/multimap/impl/MultiMapService.java
  hazelcast/src/main/java/com/hazelcast/nio/tcp/TcpIpAcceptor.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapProxy.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/DelegatingScheduledFutureStripper.java
  hazelcast/src/main/java/com/hazelcast/spi/discovery/multicast/impl/MulticastDiscoverySender.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/executionservice/impl/BasicCompletableFuture.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/executionservice/impl/ExecutionServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/slowoperationdetector/SlowOperationDetector.java
  hazelcast/src/main/java/com/hazelcast/transaction/impl/xa/XAResourceImpl.java
  hazelcast/src/main/java/com/hazelcast/util/executor/StripedExecutor.java
Labels: Team: Core, Type: Defect

#12454 Renamed NioPipeline.publish to publishMetrics
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioEventLoopGroup.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioInboundPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioOutboundPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioPipeline.java
Labels: Type: Cleanup

#12450 Socket interceptor was executed on acceptor thread
  hazelcast/src/main/java/com/hazelcast/nio/tcp/TcpIpAcceptor.java
Labels: Team: Core, Type: Defect
