Repository hazelcast/hazelcast, pull requests merged in 2018-11, with the labels that each got.

#14074 MetricsRegistry shutdown executor now
  hazelcast/src/main/java/com/hazelcast/internal/metrics/impl/MetricsRegistryImpl.java
Labels: Team: Core, Team: QuSP, Type: Enhancement

#14072 Added toString method to Evictor implementations to use for diagnosin…
  hazelcast/src/main/java/com/hazelcast/map/impl/eviction/Evictor.java
  hazelcast/src/main/java/com/hazelcast/map/impl/eviction/EvictorImpl.java
Labels: Type: Enhancement

#14040 Added static imports QueryEngineImpl
  hazelcast/src/main/java/com/hazelcast/map/impl/query/QueryEngineImpl.java
Labels: Module: Query, Type: Cleanup

#14076 Remove @Beta from missed ScheduledExecutor classes
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/ScheduledTaskHandler.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/ScheduledTaskStatistics.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/TaskUtils.java
Labels: Team: Core, Type: Enhancement

#14067 Made isAvailable private and removed it from Near Cache contract
  hazelcast/src/main/java/com/hazelcast/internal/nearcache/NearCache.java
  hazelcast/src/main/java/com/hazelcast/internal/nearcache/NearCacheRecordStore.java
  hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/DefaultNearCache.java
  hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/store/AbstractNearCacheRecordStore.java
  hazelcast/src/test/java/com/hazelcast/internal/nearcache/NearCacheTestSupport.java
  hazelcast/src/test/java/com/hazelcast/internal/nearcache/NearCacheTestUtils.java
Labels: Module: Near Cache, Team: Core, Type: Enhancement

#14079 Minor cleanup in HeartbeatManager
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/HeartbeatManager.java
Labels: Team: Client, Type: Cleanup

#14085 Skip serializing DiscoveryStrategyFactory
  hazelcast/src/main/java/com/hazelcast/config/DiscoveryStrategyConfig.java
Labels: Module: WAN, Team: Core, Type: Test-Failure, in progress

#14090 Fix misleading master response handling log
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterJoinManager.java
Labels: Team: Core, Type: Cleanup

#14066 Refactored eviction checker
  hazelcast/src/main/java/com/hazelcast/map/impl/eviction/EvictionChecker.java
  hazelcast/src/test/java/com/hazelcast/map/EvictionMaxSizePolicyTest.java
Labels: Team: Core, Type: Cleanup, Type: Enhancement

#14080 Allow dynamically adding WAN publisher configuration
  hazelcast/src/main/java/com/hazelcast/internal/ascii/rest/HttpPostCommandProcessor.java
  hazelcast/src/main/java/com/hazelcast/internal/management/ManagementDataSerializerHook.java
  hazelcast/src/main/java/com/hazelcast/internal/management/events/EventMetadata.java
  hazelcast/src/main/java/com/hazelcast/internal/management/events/WanConfigurationExtendedEvent.java
  hazelcast/src/main/java/com/hazelcast/internal/management/operation/AddWanConfigLegacyOperation.java
  hazelcast/src/main/java/com/hazelcast/wan/WanReplicationService.java
  hazelcast/src/main/java/com/hazelcast/wan/impl/WanReplicationServiceImpl.java
Labels: Module: WAN, Team: Core, Type: Enhancement, in progress

#14101 Removed getStaleReadDetector and doEvictionIfRequired methods
  hazelcast-client/src/test/java/com/hazelcast/client/cache/impl/nearcache/invalidation/ClientCacheInvalidationMemberAddRemoveTest.java
  hazelcast/src/main/java/com/hazelcast/internal/nearcache/NearCacheRecordStore.java
  hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/DefaultNearCache.java
  hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/store/AbstractNearCacheRecordStore.java
  hazelcast/src/test/java/com/hazelcast/internal/nearcache/NearCacheRecordStoreTest.java
  hazelcast/src/test/java/com/hazelcast/internal/nearcache/NearCacheTestSupport.java
  hazelcast/src/test/java/com/hazelcast/map/impl/nearcache/invalidation/MemberMapReconciliationTest.java
Labels: Module: Near Cache, Team: Core, Type: Cleanup

#13801 Remove 3.9 RU compat: Merge policy
  hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/HazelcastServerCacheManager.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/cache/CacheCreateConfigMessageTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/dynamicconfig/AddMapConfigMessageTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/dynamicconfig/AddReplicatedMapConfigMessageTask.java
  hazelcast/src/main/java/com/hazelcast/internal/config/MergePolicyValidator.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapRemoteService.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/merge/AbstractContainerMerger.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/merge/AbstractMergeRunnable.java
  hazelcast/src/test/java/com/hazelcast/internal/config/MergePolicyValidatorTest.java
Labels: Team: Core, Type: Cleanup

#13800 Remove 3.9 RU compat: Config & Quorum
  hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java
  hazelcast/src/main/java/com/hazelcast/cardinality/impl/CardinalityEstimatorService.java
  hazelcast/src/main/java/com/hazelcast/collection/impl/list/ListService.java
  hazelcast/src/main/java/com/hazelcast/collection/impl/set/SetService.java
  hazelcast/src/main/java/com/hazelcast/concurrent/atomiclong/AtomicLongService.java
  hazelcast/src/main/java/com/hazelcast/concurrent/atomicreference/AtomicReferenceService.java
  hazelcast/src/main/java/com/hazelcast/concurrent/countdownlatch/CountDownLatchService.java
  hazelcast/src/main/java/com/hazelcast/concurrent/semaphore/SemaphoreService.java
  hazelcast/src/main/java/com/hazelcast/config/CardinalityEstimatorConfig.java
  hazelcast/src/main/java/com/hazelcast/config/CollectionConfig.java
  hazelcast/src/main/java/com/hazelcast/config/DurableExecutorConfig.java
  hazelcast/src/main/java/com/hazelcast/config/ExecutorConfig.java
  hazelcast/src/main/java/com/hazelcast/config/MapConfig.java
  hazelcast/src/main/java/com/hazelcast/config/MultiMapConfig.java
  hazelcast/src/main/java/com/hazelcast/config/QueueConfig.java
  hazelcast/src/main/java/com/hazelcast/config/ReplicatedMapConfig.java
  hazelcast/src/main/java/com/hazelcast/config/RingbufferConfig.java
  hazelcast/src/main/java/com/hazelcast/config/ScheduledExecutorConfig.java
  hazelcast/src/main/java/com/hazelcast/config/SemaphoreConfig.java
  hazelcast/src/main/java/com/hazelcast/durableexecutor/impl/DistributedDurableExecutorService.java
  hazelcast/src/main/java/com/hazelcast/executor/impl/DistributedExecutorService.java
  hazelcast/src/main/java/com/hazelcast/multimap/impl/MultiMapService.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapService.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferService.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/DistributedScheduledExecutorService.java
  hazelcast/src/test/java/com/hazelcast/quorum/QuorumRollingUpgradeTest.java
Labels: Module: Config, Team: Core, Type: Cleanup

#14114 Fix NodeShutdownEventsTest
  hazelcast/src/test/java/com/hazelcast/cluster/NodeShutdownEventsTest.java
Labels: Team: Core, Type: Cleanup

#14117 Fixed expected message string
  hazelcast/src/test/java/com/hazelcast/internal/ascii/RestTest.java
Labels: Module: WAN, Team: Core, Type: Test-Failure

#14103 [BACKPORT] Add serialization support for WAN configuration classes
  hazelcast-client/src/main/java/com/hazelcast/client/config/ClientAwsConfig.java
  hazelcast/src/main/java/com/hazelcast/config/AliasedDiscoveryConfig.java
  hazelcast/src/main/java/com/hazelcast/config/AwsConfig.java
  hazelcast/src/main/java/com/hazelcast/config/AzureConfig.java
  hazelcast/src/main/java/com/hazelcast/config/ConfigDataSerializerHook.java
  hazelcast/src/main/java/com/hazelcast/config/DiscoveryConfig.java
  hazelcast/src/main/java/com/hazelcast/config/DiscoveryStrategyConfig.java
  hazelcast/src/main/java/com/hazelcast/config/EurekaConfig.java
  hazelcast/src/main/java/com/hazelcast/config/GcpConfig.java
  hazelcast/src/main/java/com/hazelcast/config/KubernetesConfig.java
  hazelcast/src/main/java/com/hazelcast/config/WanPublisherConfig.java
  hazelcast/src/main/java/com/hazelcast/config/WanReplicationConfig.java
  hazelcast/src/main/java/com/hazelcast/internal/management/operation/AddWanConfigLegacyOperation.java
  hazelcast/src/test/java/com/hazelcast/config/AliasedDiscoveryConfigUtilsTest.java
Labels: Backport, Module: WAN, Team: Core, Type: Enhancement

#14095 Closing all connections when heartbeat timeout
  hazelcast-client/src/test/java/com/hazelcast/client/heartbeat/ClientHeartbeatTest.java
  hazelcast/src/main/java/com/hazelcast/client/impl/ClientHeartbeatMonitor.java
Labels: Team: Client, Type: Defect

#14096 Closing all connections when heartbeat timeout
  hazelcast-client/src/test/java/com/hazelcast/client/heartbeat/ClientHeartbeatTest.java
  hazelcast/src/main/java/com/hazelcast/client/impl/ClientHeartbeatMonitor.java
Labels: Team: Client, Type: Defect

#14121 Counted long max-value as infinity.
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/AbstractEvictableRecordStore.java
  hazelcast/src/test/java/com/hazelcast/internal/eviction/AbstractExpirationManagerTest.java
  hazelcast/src/test/java/com/hazelcast/internal/eviction/MapExpirationManagerTest.java
Labels: Module: IMap, Team: Core, Type: Defect

#14129 Reduce complexity of handling QC map-wide events
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/SubscriberAccumulatorHandler.java
Labels: Module: IMap, Team: Core, Type: Test-Failure

#14115 PartitionServiceMBean#getActivePartitionCount hostname mismatch
  hazelcast/src/main/java/com/hazelcast/internal/jmx/PartitionServiceMBean.java
Labels: Team: Core, Type: Enhancement

#14120 [BACKPORT] PartitionServiceMBean#getActivePartitionCount hostname mismatch
  hazelcast/src/main/java/com/hazelcast/internal/jmx/PartitionServiceMBean.java
Labels: Backport, Team: Core, Type: Enhancement

#14132 No need to trigger partition table initialization if cluster startup is not completed
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/InternalPartitionServiceImpl.java
Labels: Team: Core, Type: Enhancement

#14130 [BACKPORT] Prevented unneeded task creation
  hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/AbstractEvictableRecordStore.java
  hazelcast/src/test/java/com/hazelcast/internal/eviction/AbstractExpirationManagerTest.java
  hazelcast/src/test/java/com/hazelcast/internal/eviction/CacheExpirationManagerTest.java
  hazelcast/src/test/java/com/hazelcast/internal/eviction/MapExpirationManagerTest.java
Labels: Module: ICache, Module: IMap, Team: Core

#14134 [BACKPORT] Reduce complexity of handling QC map-wide events (#14129)
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/SubscriberAccumulatorHandler.java
Labels: Backport, Module: IMap, Team: Core, Type: Test-Failure

#14128 Defined expiration interval by setting lower bound to zero and upper …
  hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java
  hazelcast/src/test/java/com/hazelcast/internal/eviction/CacheExpirationManagerTest.java
Labels: Module: ICache, Team: Core

#14133 Changes that allow Jet to react to cluster state changes
  hazelcast/src/main/java/com/hazelcast/instance/DefaultNodeContext.java
  hazelcast/src/main/java/com/hazelcast/instance/DefaultNodeExtension.java
  hazelcast/src/main/java/com/hazelcast/instance/Node.java
  hazelcast/src/main/java/com/hazelcast/instance/NodeExtension.java
  hazelcast/src/main/java/com/hazelcast/instance/NodeExtensionFactory.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterStateChange.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterStateManager.java
  hazelcast/src/test/java/com/hazelcast/test/compatibility/SamplingNodeExtension.java
  hazelcast/src/test/java/com/hazelcast/test/mocknetwork/MockNodeContext.java
Labels: Source: Jet, Team: Core, Type: Enhancement

#14139 Return status of WAN config add from REST API
  hazelcast/src/main/java/com/hazelcast/internal/ascii/rest/HttpPostCommandProcessor.java
  hazelcast/src/main/java/com/hazelcast/util/JsonUtil.java
  hazelcast/src/main/java/com/hazelcast/wan/AddWanConfigResult.java
  hazelcast/src/main/java/com/hazelcast/wan/WanReplicationService.java
  hazelcast/src/main/java/com/hazelcast/wan/impl/WanReplicationServiceImpl.java
Labels: Module: WAN, Team: Core, Type: Enhancement

#14077 Always cache field and method getters
  hazelcast/src/main/java/com/hazelcast/query/impl/getters/EvictableGetterCache.java
  hazelcast/src/main/java/com/hazelcast/query/impl/getters/Extractors.java
  hazelcast/src/main/java/com/hazelcast/query/impl/getters/FieldGetter.java
  hazelcast/src/main/java/com/hazelcast/query/impl/getters/MethodGetter.java
  hazelcast/src/main/java/com/hazelcast/query/impl/getters/ReflectionHelper.java
  hazelcast/src/main/java/com/hazelcast/util/SampleableConcurrentHashMap.java
  hazelcast/src/test/java/com/hazelcast/query/impl/getters/EvictableGetterCacheTest.java
Labels: Module: IMap, Module: Query, Team: Core, Type: Perf. Defect, in progress

#14160 [BACKPORT] Always cache field and method getters
  hazelcast/src/main/java/com/hazelcast/query/impl/getters/EvictableGetterCache.java
  hazelcast/src/main/java/com/hazelcast/query/impl/getters/Extractors.java
  hazelcast/src/main/java/com/hazelcast/query/impl/getters/FieldGetter.java
  hazelcast/src/main/java/com/hazelcast/query/impl/getters/MethodGetter.java
  hazelcast/src/main/java/com/hazelcast/query/impl/getters/ReflectionHelper.java
  hazelcast/src/main/java/com/hazelcast/util/SampleableConcurrentHashMap.java
  hazelcast/src/test/java/com/hazelcast/query/impl/getters/EvictableGetterCacheTest.java
Labels: Backport, Module: IMap, Module: Query, Team: Core, Type: Perf. Defect

#14157 Avoid Eclipse compiler problems with generic type determination by specifying the type parameter
  hazelcast-client/src/main/java/com/hazelcast/client/config/ClientAliasedDiscoveryConfigUtils.java
Labels: Team: Core, Type: Cleanup

#14014 Single util method for all get config classes.
  hazelcast-client/src/main/java/com/hazelcast/client/config/ClientConfig.java
  hazelcast-client/src/main/java/com/hazelcast/client/config/ClientReliableTopicConfig.java
  hazelcast-client/src/main/java/com/hazelcast/client/impl/clientside/DefaultClientExtension.java
  hazelcast-client/src/test/java/com/hazelcast/client/config/ClientConfigTest.java
  hazelcast/src/main/java/com/hazelcast/config/AbstractBasicConfig.java
  hazelcast/src/main/java/com/hazelcast/config/CacheSimpleConfig.java
  hazelcast/src/main/java/com/hazelcast/config/CardinalityEstimatorConfig.java
  hazelcast/src/main/java/com/hazelcast/config/CollectionConfig.java
  hazelcast/src/main/java/com/hazelcast/config/Config.java
  hazelcast/src/main/java/com/hazelcast/config/CountDownLatchConfig.java
  hazelcast/src/main/java/com/hazelcast/config/DurableExecutorConfig.java
  hazelcast/src/main/java/com/hazelcast/config/ExecutorConfig.java
  hazelcast/src/main/java/com/hazelcast/config/FlakeIdGeneratorConfig.java
  hazelcast/src/main/java/com/hazelcast/config/JobTrackerConfig.java
  hazelcast/src/main/java/com/hazelcast/config/LockConfig.java
  hazelcast/src/main/java/com/hazelcast/config/MapConfig.java
  hazelcast/src/main/java/com/hazelcast/config/MultiMapConfig.java
  hazelcast/src/main/java/com/hazelcast/config/NamedConfig.java
  hazelcast/src/main/java/com/hazelcast/config/NearCacheConfig.java
  hazelcast/src/main/java/com/hazelcast/config/PNCounterConfig.java
  hazelcast/src/main/java/com/hazelcast/config/QueueConfig.java
  hazelcast/src/main/java/com/hazelcast/config/QuorumConfig.java
  hazelcast/src/main/java/com/hazelcast/config/ReliableTopicConfig.java
  hazelcast/src/main/java/com/hazelcast/config/ReplicatedMapConfig.java
  hazelcast/src/main/java/com/hazelcast/config/RingbufferConfig.java
  hazelcast/src/main/java/com/hazelcast/config/ScheduledExecutorConfig.java
  hazelcast/src/main/java/com/hazelcast/config/SemaphoreConfig.java
  hazelcast/src/main/java/com/hazelcast/config/TopicConfig.java
  hazelcast/src/main/java/com/hazelcast/internal/config/ConfigUtils.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapRemoteService.java
  hazelcast/src/test/java/com/hazelcast/internal/config/ConfigUtilsTest.java
Labels: Module: Config, Team: Client, Team: Core, Type: Defect

#14136 Handle HazelcastClientOfflineException in reliable topic
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientReliableMessageRunner.java
  hazelcast-client/src/test/java/com/hazelcast/client/topic/ClientReliableTopicTest.java
  hazelcast/src/main/java/com/hazelcast/topic/impl/reliable/MessageRunner.java
Labels: Module: ITopic, Team: Client, Type: Defect

#14137 Handle HazelcastClientOfflineException in reliable topic
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientReliableMessageRunner.java
  hazelcast-client/src/test/java/com/hazelcast/client/topic/ClientReliableTopicTest.java
  hazelcast/src/main/java/com/hazelcast/topic/impl/reliable/MessageRunner.java
Labels: Backport, Team: Client, Type: Defect

#14163 Single util method for all get config classes.
  hazelcast-client/src/main/java/com/hazelcast/client/config/ClientConfig.java
  hazelcast-client/src/main/java/com/hazelcast/client/config/ClientReliableTopicConfig.java
  hazelcast-client/src/main/java/com/hazelcast/client/impl/clientside/DefaultClientExtension.java
  hazelcast-client/src/test/java/com/hazelcast/client/config/ClientConfigTest.java
  hazelcast/src/main/java/com/hazelcast/config/AbstractBasicConfig.java
  hazelcast/src/main/java/com/hazelcast/config/CacheSimpleConfig.java
  hazelcast/src/main/java/com/hazelcast/config/CardinalityEstimatorConfig.java
  hazelcast/src/main/java/com/hazelcast/config/CollectionConfig.java
  hazelcast/src/main/java/com/hazelcast/config/Config.java
  hazelcast/src/main/java/com/hazelcast/config/CountDownLatchConfig.java
  hazelcast/src/main/java/com/hazelcast/config/DurableExecutorConfig.java
  hazelcast/src/main/java/com/hazelcast/config/ExecutorConfig.java
  hazelcast/src/main/java/com/hazelcast/config/FlakeIdGeneratorConfig.java
  hazelcast/src/main/java/com/hazelcast/config/JobTrackerConfig.java
  hazelcast/src/main/java/com/hazelcast/config/LockConfig.java
  hazelcast/src/main/java/com/hazelcast/config/MapConfig.java
  hazelcast/src/main/java/com/hazelcast/config/MultiMapConfig.java
  hazelcast/src/main/java/com/hazelcast/config/NamedConfig.java
  hazelcast/src/main/java/com/hazelcast/config/NearCacheConfig.java
  hazelcast/src/main/java/com/hazelcast/config/PNCounterConfig.java
  hazelcast/src/main/java/com/hazelcast/config/QueueConfig.java
  hazelcast/src/main/java/com/hazelcast/config/QuorumConfig.java
  hazelcast/src/main/java/com/hazelcast/config/ReliableTopicConfig.java
  hazelcast/src/main/java/com/hazelcast/config/ReplicatedMapConfig.java
  hazelcast/src/main/java/com/hazelcast/config/RingbufferConfig.java
  hazelcast/src/main/java/com/hazelcast/config/ScheduledExecutorConfig.java
  hazelcast/src/main/java/com/hazelcast/config/SemaphoreConfig.java
  hazelcast/src/main/java/com/hazelcast/config/TopicConfig.java
  hazelcast/src/main/java/com/hazelcast/internal/config/ConfigUtils.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapRemoteService.java
  hazelcast/src/test/java/com/hazelcast/internal/config/ConfigUtilsTest.java
Labels: Backport, Module: Config, Team: Client, Team: Core

#14165 Removed 3.10 RU compatibility check
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterStateManager.java
Labels: Team: Core, Type: Cleanup

#14062 Reverting "Avoid using default truststores"
  hazelcast/src/main/java/com/hazelcast/nio/ssl/SSLEngineFactorySupport.java
  hazelcast/src/test/java/com/hazelcast/nio/ssl/BasicSSLContextFactoryTest.java
Labels: Team: Client, Team: Core

#14063 Reverting "Avoid using default truststores"
  hazelcast/src/main/java/com/hazelcast/nio/ssl/SSLEngineFactorySupport.java
  hazelcast/src/test/java/com/hazelcast/nio/ssl/BasicSSLContextFactoryTest.java
Labels: Team: Client, Team: Core

#14116 [3.11.1] Add possibility to disable scripting on members.
  hazelcast/src/main/java/com/hazelcast/internal/management/TimedMemberState.java
  hazelcast/src/main/java/com/hazelcast/internal/management/TimedMemberStateFactory.java
  hazelcast/src/main/java/com/hazelcast/internal/management/operation/ScriptExecutorOperation.java
  hazelcast/src/main/java/com/hazelcast/spi/properties/GroupProperty.java
  hazelcast/src/test/java/com/hazelcast/internal/management/ScriptingProtectionTest.java
  hazelcast/src/test/java/com/hazelcast/internal/management/TimedMemberStateIntegrationTest.java
  hazelcast/src/test/java/com/hazelcast/internal/management/TimedMemberStateTest.java
Labels: Team: Core, Team: Integration, Type: Enhancement

#14170 Upgrade JaCoCo plugin to support Java 11
  pom.xml
Labels: Team: QuSP

#14161 Clean up statistics
  hazelcast-client/src/main/java/com/hazelcast/client/impl/statistics/Statistics.java
Labels: Team: Client, Type: Cleanup

#14169 Removed unused method
  hazelcast/src/main/java/com/hazelcast/cache/impl/eviction/CacheClearExpiredRecordsTask.java
  hazelcast/src/main/java/com/hazelcast/internal/eviction/ClearExpiredRecordsTask.java
  hazelcast/src/main/java/com/hazelcast/map/impl/eviction/MapClearExpiredRecordsTask.java
Labels: Team: Core, Type: Cleanup

#14138 [BACKPORT] Changes that allow Jet to react to cluster state changes
  hazelcast/src/main/java/com/hazelcast/instance/DefaultNodeContext.java
  hazelcast/src/main/java/com/hazelcast/instance/DefaultNodeExtension.java
  hazelcast/src/main/java/com/hazelcast/instance/Node.java
  hazelcast/src/main/java/com/hazelcast/instance/NodeExtension.java
  hazelcast/src/main/java/com/hazelcast/instance/NodeExtensionFactory.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterStateChange.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterStateManager.java
  hazelcast/src/test/java/com/hazelcast/test/compatibility/SamplingNodeExtension.java
  hazelcast/src/test/java/com/hazelcast/test/mocknetwork/MockNodeContext.java
Labels: Backport, Team: Core, Type: Enhancement

#14179 Test Hazelcast factory: allow custom node extension priorities
  hazelcast/src/test/java/com/hazelcast/test/TestHazelcastInstanceFactory.java
  hazelcast/src/test/java/com/hazelcast/test/mocknetwork/MockNodeContext.java
  hazelcast/src/test/java/com/hazelcast/test/mocknetwork/TestNodeRegistry.java
Labels: Source: Jet, Type: Enhancement

#14158 Allow exceptions inside delegated executors to escape
  hazelcast/src/main/java/com/hazelcast/spi/impl/executionservice/impl/DelegateAndSkipOnConcurrentExecutionDecorator.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/ScheduledExecutorServiceBasicTest.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/ScheduledExecutorServiceTestSupport.java
Labels: Team: Core, Type: Enhancement

#14180 Backport of #14179
  hazelcast/src/test/java/com/hazelcast/test/TestHazelcastInstanceFactory.java
  hazelcast/src/test/java/com/hazelcast/test/mocknetwork/MockNodeContext.java
  hazelcast/src/test/java/com/hazelcast/test/mocknetwork/TestNodeRegistry.java
Labels: Backport, Source: Jet, Type: Enhancement

#14181 [BACKPORT] Allow exceptions inside delegated executors to escape (#14158)
  hazelcast/src/main/java/com/hazelcast/spi/impl/executionservice/impl/DelegateAndSkipOnConcurrentExecutionDecorator.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/ScheduledExecutorServiceBasicTest.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/ScheduledExecutorServiceTestSupport.java
Labels: Team: Core, Type: Enhancement

#14159 Increase test timeout to avoid false positive failures
  hazelcast/src/test/java/com/hazelcast/map/ExpirationTimeTest.java
Labels: Team: Core, Type: Test-Failure

#14184 Doc enhancements for IScheduledExec for errors during periodic tasks
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/IScheduledExecutorService.java
Labels: Team: Core, Type: Enhancement

#14189 [BACKPORT] Doc enhancements for IScheduledExec for errors during periodic tasks
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/IScheduledExecutorService.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/ScheduledTaskHandler.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/ScheduledTaskStatistics.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/TaskUtils.java
Labels: Team: Core, Type: Enhancement

#13978 fix handling of rest urls
  hazelcast/src/main/java/com/hazelcast/internal/ascii/rest/HttpCommand.java
  hazelcast/src/main/java/com/hazelcast/internal/ascii/rest/HttpDeleteCommandProcessor.java
  hazelcast/src/main/java/com/hazelcast/internal/ascii/rest/HttpGetCommandProcessor.java
  hazelcast/src/main/java/com/hazelcast/internal/ascii/rest/HttpHeadCommandProcessor.java
  hazelcast/src/main/java/com/hazelcast/internal/ascii/rest/HttpPostCommandProcessor.java
  hazelcast/src/test/java/com/hazelcast/internal/ascii/HTTPCommunicator.java
  hazelcast/src/test/java/com/hazelcast/internal/ascii/RestTest.java
Labels: Team: Client, Type: Defect

#14112 [Backport] Fix a bug causing partition table to be modified while PASSIVE
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/InternalPartitionServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/MigrationManager.java
  hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/NoMigrationClusterStateTest.java
  hazelcast/src/test/java/com/hazelcast/internal/partition/impl/FrozenPartitionTableTest.java
Labels: Backport, Team: Core, Type: Defect

#14111 Fix a bug causing partition table to be modified while PASSIVE
  hazelcast/src/main/java/com/hazelcast/cluster/ClusterState.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/InternalPartitionServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/MigrationManager.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/MigrationThread.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/PartitionReplicaManager.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/PublishPartitionRuntimeStateTask.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/operation/PartitionReplicaSyncRequest.java
  hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/NoMigrationClusterStateTest.java
  hazelcast/src/test/java/com/hazelcast/internal/partition/impl/FrozenPartitionTableTest.java
Labels: Team: Core, Type: Defect

#14164 [FORWARD-PORT] Return status of WAN config add from REST API (#14139)
  hazelcast/src/main/java/com/hazelcast/internal/ascii/rest/HttpPostCommandProcessor.java
  hazelcast/src/main/java/com/hazelcast/util/JsonUtil.java
  hazelcast/src/main/java/com/hazelcast/wan/AddWanConfigResult.java
  hazelcast/src/main/java/com/hazelcast/wan/WanReplicationService.java
  hazelcast/src/main/java/com/hazelcast/wan/impl/WanReplicationServiceImpl.java
Labels: Module: WAN, Team: Core, Type: Enhancement
