Repository hazelcast/hazelcast, pull requests merged in 2018-07, with the labels that each got.

#13394 Fixed SplitBrainMergePolicyProvider for ExpirationTimeMergePolicy
  hazelcast/src/main/java/com/hazelcast/spi/merge/SplitBrainMergePolicyProvider.java
  hazelcast/src/test/java/com/hazelcast/spi/merge/SplitBrainMergePolicyProviderTest.java
Labels: Team: Core, Type: Defect

#13395 Backport fixed split brain merge policy provider for expiration time merge policy
  hazelcast/src/main/java/com/hazelcast/spi/merge/SplitBrainMergePolicyProvider.java
  hazelcast/src/test/java/com/hazelcast/spi/merge/SplitBrainMergePolicyProviderTest.java
Labels: Backport, Team: Core, Type: Defect

#13380 Added load event listening capability to client side added listener
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/ClientEntryLoadedListenerTest.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapListenerAdapter.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapListenerAdaptors.java
  hazelcast/src/main/java/com/hazelcast/map/impl/event/MapEventPublisherImpl.java
  hazelcast/src/test/java/com/hazelcast/map/impl/MapListenerAdapterTest.java
Labels: Team: Client, Team: Core, Type: Defect

#13411 DefaultSerializationServiceBuilder no longer ignores useNativeByteOrder
  hazelcast/src/main/java/com/hazelcast/config/SerializationConfig.java
  hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/DefaultSerializationServiceBuilder.java
  hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/DefaultSerializationServiceBuilderTest.java
Labels: Team: Core, Type: Defect

#13404 Fix possible infinite loop in ReplicatedMapProxy
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapProxy.java
Labels: Team: Core, Type: Defect

#13414 [BACKPORT] Register PN counter service in permission factory
  hazelcast/src/main/java/com/hazelcast/security/permission/ActionConstants.java
Labels: Backport, Team: Core, Type: Defect

#13407 Initialize query cache config only once at construction phase
  hazelcast-client/src/main/java/com/hazelcast/client/impl/querycache/subscriber/ClientQueryCacheConfigurator.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/querycache/ClientQueryCacheListenerTest.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/QueryCacheConfigurator.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/AbstractInternalQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/AbstractQueryCacheEndToEndConstructor.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/DefaultQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/NodeQueryCacheConfigurator.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/QueryCacheFactory.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/QueryCacheRequest.java
  hazelcast/src/test/java/com/hazelcast/map/impl/querycache/QueryCacheListenerTest.java
Labels: Team: Core, Type: Defect

#13413 Register PN counter service in permission factory
  hazelcast/src/main/java/com/hazelcast/security/permission/ActionConstants.java
Labels: Team: Core, Type: Defect

#13416 Clear schedulers for ttl upon clear of replicated-map otherwise memory leaks
  hazelcast-client/src/test/java/com/hazelcast/client/replicatedmap/ClientReplicatedMapTest.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/record/AbstractBaseReplicatedRecordStore.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/record/AbstractReplicatedRecordStore.java
  hazelcast/src/main/java/com/hazelcast/util/scheduler/SecondsBasedEntryTaskScheduler.java
  hazelcast/src/test/java/com/hazelcast/replicatedmap/ReplicatedMapTtlTest.java
Labels: Interface: ReplicatedMap, Team: Core, Type: Defect

#13418 [FORWARD-PORT] Clear schedulers for ttl upon clear of replicated-map otherwise memor…
  hazelcast-client/src/test/java/com/hazelcast/client/replicatedmap/ClientReplicatedMapTest.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/record/AbstractBaseReplicatedRecordStore.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/record/AbstractReplicatedRecordStore.java
  hazelcast/src/main/java/com/hazelcast/util/scheduler/SecondsBasedEntryTaskScheduler.java
  hazelcast/src/test/java/com/hazelcast/replicatedmap/ReplicatedMapTtlTest.java
Labels: Interface: ReplicatedMap, Team: Core, Type: Defect

#13417 [FORWARD-PORT] Initialize query cache config only once at construction phase
  hazelcast-client/src/main/java/com/hazelcast/client/impl/querycache/subscriber/ClientQueryCacheConfigurator.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/querycache/ClientQueryCacheListenerTest.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/QueryCacheConfigurator.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/AbstractInternalQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/AbstractQueryCacheEndToEndConstructor.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/DefaultQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/NodeQueryCacheConfigurator.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/QueryCacheFactory.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/QueryCacheRequest.java
  hazelcast/src/test/java/com/hazelcast/map/impl/querycache/QueryCacheListenerTest.java
Labels: Interface: IMap, Team: Core, Type: Defect

#13420 Give access to group and serialization config over client instance
  hazelcast-client/src/main/java/com/hazelcast/client/impl/clientside/ClientDynamicClusterConfig.java
  hazelcast-client/src/test/java/com/hazelcast/client/config/ClientConfigTest.java
  hazelcast/src/test/java/com/hazelcast/client/test/Employee.java
Labels: Team: Client, Type: Enhancement

#13421 Give access to group and serialization config over client instance
  hazelcast-client/src/main/java/com/hazelcast/client/impl/ClientDynamicClusterConfig.java
  hazelcast-client/src/test/java/com/hazelcast/client/config/ClientConfigTest.java
  hazelcast/src/test/java/com/hazelcast/client/test/Employee.java
Labels: Backport, Team: Client, Type: Enhancement

#13422 Cancel scheduled replicated map entries to prevent memory leaks.
  hazelcast-client/src/test/java/com/hazelcast/client/replicatedmap/ClientReplicatedMapTest.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/record/AbstractBaseReplicatedRecordStore.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/record/AbstractReplicatedRecordStore.java
  hazelcast/src/test/java/com/hazelcast/replicatedmap/ReplicatedMapTtlTest.java
Labels: Interface: ReplicatedMap, Team: Core, Type: Defect

#13424 Exclude from parallel timeout-test to keep noise to the min
  hazelcast-client/src/test/java/com/hazelcast/client/ClientTimeoutTest.java
Labels: Team: Core, Type: Test-Failure

#13426 add custom credentials for non java clients
  hazelcast/src/test/java/com/hazelcast/client/test/CustomCredentials.java
  hazelcast/src/test/java/com/hazelcast/client/test/PortableFactory.java
Labels: Type: Enhancement

#13429 Fix unstable test due to different count of op threads
  hazelcast/src/test/java/com/hazelcast/map/MapSetTTLBackupTest.java
Labels: Team: Core, Type: Test-Failure

#13430 Use assert eventually for a latch based test that failed due to noise
  hazelcast/src/test/java/com/hazelcast/collection/impl/queue/QueueListenerTest.java
Labels: Team: Core, Type: Test-Failure

#13319 Java 9+ related - Add automatic module name to core and client JARs Manifests
  hazelcast-build-utils/src/main/java/com/hazelcast/buildutils/HazelcastManifestTransformer.java
  hazelcast-client/pom.xml
  hazelcast/pom.xml
Labels: Team: Client, Team: Core, Type: Enhancement

#13314 [FORWARD-PORT] Separate WAN event diagnostics per publisher
  hazelcast/src/main/java/com/hazelcast/map/impl/MapReplicationSupportingService.java
  hazelcast/src/main/java/com/hazelcast/map/impl/wan/MapReplicationRemove.java
  hazelcast/src/main/java/com/hazelcast/map/impl/wan/MapReplicationUpdate.java
  hazelcast/src/main/java/com/hazelcast/monitor/LocalWanPublisherStats.java
  hazelcast/src/main/java/com/hazelcast/monitor/impl/LocalWanPublisherStatsImpl.java
  hazelcast/src/main/java/com/hazelcast/util/MapUtil.java
  hazelcast/src/main/java/com/hazelcast/wan/ReplicationEventObject.java
  hazelcast/src/main/java/com/hazelcast/wan/WanReplicationService.java
  hazelcast/src/main/java/com/hazelcast/wan/impl/DistributedServiceWanEventCounters.java
  hazelcast/src/main/java/com/hazelcast/wan/impl/WanEventCounterContainer.java
  hazelcast/src/main/java/com/hazelcast/wan/impl/WanEventCounters.java
  hazelcast/src/main/java/com/hazelcast/wan/impl/WanReplicationServiceImpl.java
Labels: Module: WAN, Team: Core, Type: Enhancement

#13434 add ability to set custom url endpoint for internal testing of hazelcast.cloud
  hazelcast-client/src/main/java/com/hazelcast/client/impl/HazelcastClientInstanceImpl.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/discovery/HazelcastCloudAddressProvider.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/discovery/HazelcastCloudAddressTranslator.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/discovery/HazelcastCloudDiscovery.java
  hazelcast-client/src/test/java/com/hazelcast/client/spi/impl/discovery/HazelcastCloudConfigTest.java
Labels: Backport, Team: Client, Type: Enhancement

#13432 add ability to set custom url endpoint for internal testing of hazelcast.cloud
  hazelcast-client/src/main/java/com/hazelcast/client/impl/HazelcastClientInstanceImpl.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/discovery/HazelcastCloudAddressProvider.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/discovery/HazelcastCloudAddressTranslator.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/discovery/HazelcastCloudDiscovery.java
  hazelcast-client/src/test/java/com/hazelcast/client/spi/impl/discovery/HazelcastCloudConfigTest.java
Labels: Team: Client, Type: Enhancement

#13433 add ability to set custom url endpoint for internal testing of hazelcast.cloud
  hazelcast-client/src/main/java/com/hazelcast/client/impl/clientside/HazelcastClientInstanceImpl.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/discovery/HazelcastCloudAddressProvider.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/discovery/HazelcastCloudAddressTranslator.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/discovery/HazelcastCloudDiscovery.java
  hazelcast-client/src/test/java/com/hazelcast/client/spi/impl/discovery/HazelcastCloudConfigTest.java
Labels: Team: Client, Type: Enhancement

#13425 [FORWARD-PORT] Cancel scheduled replicated map entries to prevent memory leaks.
  hazelcast-client/src/test/java/com/hazelcast/client/replicatedmap/ClientReplicatedMapTest.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/record/AbstractBaseReplicatedRecordStore.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/record/AbstractReplicatedRecordStore.java
  hazelcast/src/test/java/com/hazelcast/replicatedmap/ReplicatedMapTtlTest.java
Labels: Team: Core, Type: Defect

#13436 Add RuntimeAvailableProcessorsRule
  hazelcast/src/test/java/com/hazelcast/map/MapSetTTLBackupTest.java
  hazelcast/src/test/java/com/hazelcast/test/environment/RuntimeAvailableProcessorsRule.java
Labels: Team: Core, Type: Enhancement

#13438 Fixed tests with missing @RunWith or @Category annotations
  hazelcast/src/test/java/com/hazelcast/cluster/MulticastDeserializationTest.java
  hazelcast/src/test/java/com/hazelcast/internal/metrics/MetricsUtilTest.java
  hazelcast/src/test/java/com/hazelcast/internal/metrics/impl/ProbeBuilderImplTest.java
Labels: Type: Test-Failure

#13313 [FORWARD-PORT] Add stop state to WAN publisher
  hazelcast-spring/src/main/java/com/hazelcast/spring/HazelcastConfigBeanDefinitionParser.java
  hazelcast-spring/src/main/resources/hazelcast-spring-3.11.xsd
  hazelcast-spring/src/test/java/com/hazelcast/spring/TestFullApplicationContext.java
  hazelcast-spring/src/test/resources/com/hazelcast/spring/fullConfig-applicationContext-hazelcast.xml
  hazelcast/src/main/java/com/hazelcast/config/ConfigXmlGenerator.java
  hazelcast/src/main/java/com/hazelcast/config/WANQueueFullBehavior.java
  hazelcast/src/main/java/com/hazelcast/config/WanPublisherConfig.java
  hazelcast/src/main/java/com/hazelcast/config/WanPublisherState.java
  hazelcast/src/main/java/com/hazelcast/config/XmlConfigBuilder.java
  hazelcast/src/main/java/com/hazelcast/internal/jmx/InstanceMBean.java
  hazelcast/src/main/java/com/hazelcast/internal/jmx/WanPublisherMBean.java
  hazelcast/src/main/java/com/hazelcast/monitor/LocalWanPublisherStats.java
  hazelcast/src/main/java/com/hazelcast/monitor/impl/LocalWanPublisherStatsImpl.java
  hazelcast/src/main/java/com/hazelcast/wan/WanReplicationService.java
  hazelcast/src/main/java/com/hazelcast/wan/impl/WanReplicationServiceImpl.java
  hazelcast/src/main/resources/hazelcast-config-3.11.xsd
  hazelcast/src/main/resources/hazelcast-full-example.xml
  hazelcast/src/test/java/com/hazelcast/config/ConfigCompatibilityChecker.java
  hazelcast/src/test/java/com/hazelcast/config/ConfigXmlGeneratorTest.java
  hazelcast/src/test/java/com/hazelcast/config/XMLConfigBuilderTest.java
  hazelcast/src/test/java/com/hazelcast/internal/jmx/MBeanDataHolder.java
  hazelcast/src/test/java/com/hazelcast/monitor/impl/LocalWanPublisherStatsTest.java
  hazelcast/src/test/java/com/hazelcast/monitor/impl/LocalWanStatsImplTest.java
  hazelcast/src/test/resources/hazelcast-fullconfig.xml
Labels: Team: Core, Type: Enhancement

#13442 Increase timings to min chance of hiccup failure & moved to slow test
  hazelcast/src/test/java/com/hazelcast/map/BasicMapTest.java
Labels: Team: Core, Type: Test-Failure

#13440 [Java 9] ignore new StackTraceElement fields in tests
  hazelcast/src/test/java/com/hazelcast/client/impl/protocol/codec/StackTraceElementCodecTest.java
Labels: Team: Core, Type: Test-Failure

#13316 MonitoredThread deleted
  hazelcast/src/main/java/com/hazelcast/internal/management/MonitoredThread.java
Labels: Team: Integration, Type: Cleanup

#13445 During cluster-state change, trigger repartitioning only when needed
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/InternalPartitionServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/MigrationManager.java
Labels: Team: Core, Type: Defect

#13446 During cluster-state change, trigger repartitioning only when needed
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/InternalPartitionServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/MigrationManager.java
Labels: Backport, Team: Core, Type: Defect

#13443 [Java 9] Add modulepath specific tests - testing Hazelcast in modularized environment.
  checkstyle/suppressions.xml
  modulepath-tests/pom.xml
  modulepath-tests/src/main/java/module-info.java
  modulepath-tests/src/test/java/com/hazelcast/test/modulepath/SmokeModulePathTest.java
  pom.xml
Labels: Team: Core, Type: Enhancement

#13452 Javadoc typos and clarifications
  hazelcast/src/main/java/com/hazelcast/core/IMap.java
  hazelcast/src/main/java/com/hazelcast/internal/management/ManagementCenterService.java
  hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/PortablePositionNavigator.java
  hazelcast/src/main/java/com/hazelcast/query/extractor/ValueReader.java
  hazelcast/src/main/java/com/hazelcast/query/impl/BaseIndexStore.java
Labels: Interface: IMap, Team: Core, Type: Enhancement

#13441 Added HazelcastStarterConstructor annotation to HazelcastStarter
  hazelcast/src/test/java/com/hazelcast/test/starter/HazelcastProxyFactory.java
  hazelcast/src/test/java/com/hazelcast/test/starter/HazelcastStarterConstructor.java
  hazelcast/src/test/java/com/hazelcast/test/starter/HazelcastStarterUtils.java
  hazelcast/src/test/java/com/hazelcast/test/starter/ProxyInvocationHandler.java
  hazelcast/src/test/java/com/hazelcast/test/starter/ReflectionUtils.java
  hazelcast/src/test/java/com/hazelcast/test/starter/constructor/AbstractConfigConstructor.java
  hazelcast/src/test/java/com/hazelcast/test/starter/constructor/AbstractStarterObjectConstructor.java
  hazelcast/src/test/java/com/hazelcast/test/starter/constructor/AddressConstructor.java
  hazelcast/src/test/java/com/hazelcast/test/starter/constructor/ConfigConstructor.java
  hazelcast/src/test/java/com/hazelcast/test/starter/constructor/DataAwareEntryEventConstructor.java
  hazelcast/src/test/java/com/hazelcast/test/starter/constructor/EntryEventConstructor.java
  hazelcast/src/test/java/com/hazelcast/test/starter/constructor/EnumConstructor.java
  hazelcast/src/test/java/com/hazelcast/test/starter/constructor/GreaterLessPredicateConstructor.java
  hazelcast/src/test/java/com/hazelcast/test/starter/constructor/LifecycleEventConstructor.java
  hazelcast/src/test/java/com/hazelcast/test/starter/constructor/MapEventConstructor.java
  hazelcast/src/test/java/com/hazelcast/test/starter/constructor/VersionConstructor.java
  hazelcast/src/test/java/com/hazelcast/test/starter/constructor/test/ConfigConstructorTest.java
Labels: Type: Enhancement

#13458 Fix Java 6 compiler issue in Json_Test
  hazelcast/src/test/java/com/hazelcast/internal/json/Json_Test.java
Labels: Team: Core, Type: Test-Failure

#13455 Fix broken ClientInvocationFuture from completeExceptionally changes
  hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientInvocationFuture.java
  hazelcast-client/src/test/java/com/hazelcast/client/spi/impl/ClientInvocationFutureTest.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractInvocationFuture.java
Labels: Team: Core, Type: Test-Failure

#13461 Add ClientFutureInvocation test for chaining callbacks
  hazelcast-client/src/test/java/com/hazelcast/client/spi/impl/ClientInvocationFutureTest.java
Labels: Team: Core

#13468 Moved org.reflections dependency to root pom.xml
  hazelcast/pom.xml
  pom.xml
Labels: Team: Core, Type: Test-Failure

#13164 Remove maxJoinTimeMillis from logs when node is shutting down
  hazelcast/src/main/java/com/hazelcast/instance/Node.java
Labels: Team: Core

#13444 Adds forced eviction and cleanup for per record hd expiry policies
  hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java
  hazelcast/src/test/java/com/hazelcast/cache/CacheBasicAbstractTest.java
Labels: Type: Critical, Type: Test-Failure

#13467 [BACKPORT] Use getOrPutSynchronized while creating repairing handler
  hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/invalidation/RepairingTask.java
Labels: Team: Core, Type: Defect

#13447 [FORWARD PORT] Added stopping WAN replication from MC
  hazelcast/src/main/java/com/hazelcast/internal/management/operation/ChangeWanStateOperation.java
  hazelcast/src/main/java/com/hazelcast/internal/management/request/ChangeWanStateRequest.java
  hazelcast/src/main/java/com/hazelcast/monitor/impl/LocalWanPublisherStatsImpl.java
  hazelcast/src/test/java/com/hazelcast/internal/management/ChangeWanStateRequestTest.java
Labels: Team: Integration, Type: Enhancement

#13479 Added framelength to Packet.toString.
  hazelcast/src/main/java/com/hazelcast/nio/Packet.java
Labels: Team: Core

#13281 WAN persist option
  hazelcast-spring/src/main/java/com/hazelcast/spring/HazelcastConfigBeanDefinitionParser.java
  hazelcast-spring/src/main/resources/hazelcast-spring-3.11.xsd
  hazelcast-spring/src/test/java/com/hazelcast/spring/TestFullApplicationContext.java
  hazelcast-spring/src/test/resources/com/hazelcast/spring/fullConfig-applicationContext-hazelcast.xml
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/dynamicconfig/AddMapConfigMessageTask.java
  hazelcast/src/main/java/com/hazelcast/config/ConfigXmlGenerator.java
  hazelcast/src/main/java/com/hazelcast/config/MapConfig.java
  hazelcast/src/main/java/com/hazelcast/config/WanConsumerConfig.java
  hazelcast/src/main/java/com/hazelcast/config/WanReplicationRef.java
  hazelcast/src/main/java/com/hazelcast/config/XmlConfigBuilder.java
  hazelcast/src/main/resources/hazelcast-config-3.11.xsd
  hazelcast/src/test/java/com/hazelcast/config/XMLConfigBuilderTest.java
  hazelcast/src/test/java/com/hazelcast/config/helpers/CacheConfigHelper.java
  hazelcast/src/test/resources/hazelcast-fullconfig.xml
Labels: Module: WAN, Team: Core, Type: Enhancement

#13457 [BACKPORT] Use user code deployment for custom attribute extractors
  hazelcast-client/src/test/java/com/hazelcast/client/usercodedeployment/ClientUserCodeDeploymentTest.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapContainer.java
  hazelcast/src/test/java/usercodedeployment/CapitalizatingFirstnameExtractor.java
  hazelcast/src/test/java/usercodedeployment/Person.java
Labels: Backport, Team: Core, Type: Defect

#13474 Clear indexes while collecting merge tasks
  hazelcast/src/main/java/com/hazelcast/map/impl/MapMigrationAwareService.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapSplitBrainHandlerService.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/MapReplicationStateHolder.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/AbstractInternalQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/DefaultRecordStore.java
  hazelcast/src/main/java/com/hazelcast/query/impl/Indexes.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/merge/AbstractSplitBrainHandlerService.java
  hazelcast/src/test/java/com/hazelcast/map/impl/RecordStoreTest.java
  hazelcast/src/test/java/com/hazelcast/map/merge/NoIndexLossAfterSplitBrainHealTest.java
Labels: Team: Core, Type: Defect

#13481 Added onRecordStoreDestroy flag to destroy hd indexes
  hazelcast/src/main/java/com/hazelcast/map/impl/MapServiceContext.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapServiceContextImpl.java
  hazelcast/src/main/java/com/hazelcast/map/impl/PartitionContainer.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/DefaultRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/RecordStore.java
Labels: Team: Core, Type: Defect

#13484 Improve NativeMemoryConfig javadoc
  hazelcast/src/main/java/com/hazelcast/config/NativeMemoryConfig.java
Labels: Module: Config, Type: Enhancement

#13485 Introduce GracefulShutdownAwareService
  hazelcast/src/main/java/com/hazelcast/crdt/CRDTReplicationMigrationService.java
  hazelcast/src/main/java/com/hazelcast/instance/Node.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/InternalPartitionService.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/InternalPartitionServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/spi/GracefulShutdownAwareService.java
Labels: Team: Core, Type: Enhancement

#13488 Ignore VersionedInCurrentVersionTest on JDKs 6 and 7
  hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/VersionedInCurrentVersionTest.java
  hazelcast/src/test/java/com/hazelcast/test/HazelcastTestSupport.java
Labels: Type: Test-Failure

#13489 Ignore VersionedInCurrentVersionTest on JDKs 6 and 7
  hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/VersionedInCurrentVersionTest.java
  hazelcast/src/test/java/com/hazelcast/test/HazelcastTestSupport.java
Labels: Type: Test-Failure

#13491 Prepared tests for CompatibilityTest enhancement
  hazelcast/src/test/java/com/hazelcast/cache/CacheBasicAbstractTest.java
  hazelcast/src/test/java/com/hazelcast/map/MapSetTTLBackupTest.java
Labels: Type: Cleanup, Type: Test-Failure

#13459 Cleanup of Node field access
  hazelcast/src/main/java/com/hazelcast/instance/HazelcastInstanceImpl.java
  hazelcast/src/main/java/com/hazelcast/instance/MemberImpl.java
  hazelcast/src/main/java/com/hazelcast/instance/Node.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/InternalPartitionService.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/InternalPartitionServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/MigrationManager.java
  hazelcast/src/test/java/com/hazelcast/internal/partition/TestPartitionUtils.java
  hazelcast/src/test/java/com/hazelcast/test/HazelcastTestSupport.java
Labels: Type: Cleanup, Type: Enhancement

#13483 Remove group property "hazelcast.mc.max.visible.instance.count"
  hazelcast-spring/src/main/resources/hazelcast-spring-3.11.xsd
  hazelcast/src/main/java/com/hazelcast/internal/management/TimedMemberStateFactory.java
  hazelcast/src/main/java/com/hazelcast/spi/properties/GroupProperty.java
  hazelcast/src/test/java/com/hazelcast/internal/management/TimedMemberStateIntegrationTest.java
Labels: Team: Integration, Type: Enhancement

#13494 getTask connection to MC uses HTTP POST method
  hazelcast/src/main/java/com/hazelcast/internal/management/ManagementCenterService.java
  hazelcast/src/test/java/com/hazelcast/internal/management/MancenterServlet.java
Labels: Team: Integration

#13477 Simplify the check in isAfterVectorClock
  hazelcast/src/main/java/com/hazelcast/cluster/impl/VectorClock.java
Labels: Team: Client, Team: Core, Type: Enhancement

#13466 Add merkle tree configuration
  hazelcast-client/src/main/java/com/hazelcast/client/impl/clientside/ClientDynamicClusterConfig.java
  hazelcast-spring/src/main/java/com/hazelcast/spring/HazelcastConfigBeanDefinitionParser.java
  hazelcast-spring/src/main/resources/hazelcast-spring-3.11.xsd
  hazelcast-spring/src/test/java/com/hazelcast/spring/TestFullApplicationContext.java
  hazelcast-spring/src/test/resources/com/hazelcast/spring/fullConfig-applicationContext-hazelcast.xml
  hazelcast/src/main/java/com/hazelcast/config/Config.java
  hazelcast/src/main/java/com/hazelcast/config/ConfigDataSerializerHook.java
  hazelcast/src/main/java/com/hazelcast/config/ConfigXmlGenerator.java
  hazelcast/src/main/java/com/hazelcast/config/ConsistencyCheckStrategy.java
  hazelcast/src/main/java/com/hazelcast/config/MerkleTreeConfig.java
  hazelcast/src/main/java/com/hazelcast/config/WanPublisherConfig.java
  hazelcast/src/main/java/com/hazelcast/config/WanSyncConfig.java
  hazelcast/src/main/java/com/hazelcast/config/XmlConfigBuilder.java
  hazelcast/src/main/java/com/hazelcast/config/XmlElements.java
  hazelcast/src/main/java/com/hazelcast/internal/dynamicconfig/ClusterWideConfigurationService.java
  hazelcast/src/main/java/com/hazelcast/internal/dynamicconfig/ConfigurationService.java
  hazelcast/src/main/java/com/hazelcast/internal/dynamicconfig/DynamicConfigurationAwareConfig.java
  hazelcast/src/main/java/com/hazelcast/internal/dynamicconfig/EmptyConfigurationService.java
  hazelcast/src/main/resources/hazelcast-config-3.11.xsd
  hazelcast/src/main/resources/hazelcast-default.xml
  hazelcast/src/main/resources/hazelcast-full-example.xml
  hazelcast/src/test/java/com/hazelcast/config/ConfigCompatibilityChecker.java
  hazelcast/src/test/java/com/hazelcast/config/ConfigXmlGeneratorTest.java
  hazelcast/src/test/java/com/hazelcast/config/XMLConfigBuilderTest.java
  hazelcast/src/test/resources/hazelcast-fullconfig.xml
Labels: Module: Config, Module: WAN, Team: Core, Type: Enhancement
