Repository hazelcast/hazelcast, pull requests merged in 2018-08, with the labels that each got.

#13507 Used cached event types
  hazelcast/src/main/java/com/hazelcast/cache/CacheEventType.java
Labels: Interface: ICache, Team: Core, Type: Enhancement

#13514 Handled null wanReplicationConfig
  hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapContainer.java
Labels: Module: WAN, Team: Core

#13480 [FORWARD-PORT] Clear indexes while collecting stores
  hazelcast/src/main/java/com/hazelcast/map/impl/MapMigrationAwareService.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapServiceContext.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapServiceContextImpl.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapSplitBrainHandlerService.java
  hazelcast/src/main/java/com/hazelcast/map/impl/PartitionContainer.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/MapReplicationStateHolder.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/AbstractInternalQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/DefaultRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/RecordStore.java
  hazelcast/src/main/java/com/hazelcast/query/impl/Indexes.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/merge/AbstractSplitBrainHandlerService.java
  hazelcast/src/test/java/com/hazelcast/map/impl/RecordStoreTest.java
  hazelcast/src/test/java/com/hazelcast/map/merge/NoIndexLossAfterSplitBrainHealTest.java
Labels: Team: Core, Type: Defect

#13516 Fixes not compiling CacheExpirationTest
  hazelcast/src/test/java/com/hazelcast/cache/eviction/CacheExpirationTest.java
Labels: Team: Core

#13518 Adds unintentionally removed MapExpirationManager primaryDrivesEvicti…
  hazelcast/src/test/java/com/hazelcast/internal/eviction/MapExpirationManagerTest.java
Labels: Team: Core, Type: Enhancement

#13379 Provide a way to force service name serialization
  hazelcast/src/main/java/com/hazelcast/cache/impl/operation/CacheMergeOperation.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/operation/CachePutAllBackupOperation.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/operation/CachePutAllOperation.java
  hazelcast/src/main/java/com/hazelcast/spi/Operation.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationBackupHandler.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/operations/Backup.java
  hazelcast/src/test/java/com/hazelcast/spi/OperationSerializationTest.java
Labels: Interface: ICache, Module: Rolling Upgrade, Team: Core, Type: Defect, Type: Test-Failure

#13522 fix bug in javadoc. Ttl returns millisecond
  hazelcast/src/main/java/com/hazelcast/core/EntryView.java
Labels: Team: Core, Type: Defect

#13523 fix bug in javadoc. Ttl returns millisecond
  hazelcast/src/main/java/com/hazelcast/core/EntryView.java
Labels: Backport, Team: Core, Type: Defect

#13526 Set default value to false for persist-wan-replicated-data
  hazelcast-spring/src/main/resources/hazelcast-spring-3.11.xsd
  hazelcast/src/main/resources/hazelcast-config-3.11.xsd
  hazelcast/src/test/java/com/hazelcast/config/XMLConfigBuilderTest.java
Labels: Module: WAN, Team: Core, Type: Defect

#13502 Send hot restart backup directory to MC
  hazelcast/src/main/java/com/hazelcast/hotrestart/HotRestartService.java
  hazelcast/src/main/java/com/hazelcast/hotrestart/NoOpHotRestartService.java
  hazelcast/src/main/java/com/hazelcast/internal/management/TimedMemberStateFactory.java
  hazelcast/src/main/java/com/hazelcast/monitor/HotRestartState.java
  hazelcast/src/main/java/com/hazelcast/monitor/impl/HotRestartStateImpl.java
  hazelcast/src/test/java/com/hazelcast/hotrestart/NoopHotRestartServicesTest.java
  hazelcast/src/test/java/com/hazelcast/monitor/impl/HotRestartStateImplTest.java
  hazelcast/src/test/java/com/hazelcast/monitor/impl/MemberStateImplTest.java
Labels: Team: Integration, Type: Enhancement

#13535 [Java 9] Exclude HazelcastOSGiIntegrationTest from running on newer Java versions
  pom.xml
Labels: Team: Core, Type: Test-Failure

#13541 [IBM JDK] #13534 fix package lookup in Byte Buddy
  hazelcast/src/test/java/com/hazelcast/test/starter/HazelcastProxyFactory.java
  hazelcast/src/test/java/com/hazelcast/util/ServiceLoaderTest.java
  pom.xml
Labels: Team: Core, Type: Test-Failure

#13542 Do not use -SNAPSHOT version of Hazelcast in a test
  hazelcast/src/test/java/com/hazelcast/test/starter/constructor/test/MergePolicyProviderConstructorTest.java
Labels: Team: Core, Type: Defect, Type: Test-Failure

#13543 [BACKPORT 3.10.x] Fixes package lookup in Bytebuddy on IBM JDK
  hazelcast/src/test/java/com/hazelcast/test/starter/HazelcastProxyFactory.java
  hazelcast/src/test/java/com/hazelcast/util/ServiceLoaderTest.java
  pom.xml
Labels: Team: Core, Type: Test-Failure

#13453 Adding data structure config at runtime should not fail unless equal …
  hazelcast/src/main/java/com/hazelcast/internal/dynamicconfig/DynamicConfigurationAwareConfig.java
  hazelcast/src/test/java/com/hazelcast/internal/dynamicconfig/DynamicConfigSmokeTest.java
Labels: Team: Core, Type: Defect

#13462 Introduce extention points for JMX & Rest on EE
  hazelcast/src/main/java/com/hazelcast/instance/DefaultNodeExtension.java
  hazelcast/src/main/java/com/hazelcast/instance/HazelcastInstanceImpl.java
  hazelcast/src/main/java/com/hazelcast/instance/Node.java
  hazelcast/src/main/java/com/hazelcast/instance/NodeExtension.java
  hazelcast/src/main/java/com/hazelcast/internal/ascii/TextCommandService.java
  hazelcast/src/main/java/com/hazelcast/internal/ascii/TextCommandServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/internal/ascii/rest/HttpCommandProcessor.java
  hazelcast/src/main/java/com/hazelcast/internal/jmx/HazelcastMBean.java
  hazelcast/src/main/java/com/hazelcast/internal/jmx/ManagementService.java
  hazelcast/src/main/java/com/hazelcast/monitor/NodeState.java
  hazelcast/src/main/java/com/hazelcast/monitor/impl/NodeStateImpl.java
  hazelcast/src/test/java/com/hazelcast/internal/ascii/HTTPCommunicator.java
  hazelcast/src/test/java/com/hazelcast/test/compatibility/SamplingNodeExtension.java
Labels: Team: Core, Type: Enhancement

#13545 Upgrade failsafe plugin version to work with Java 10+
  pom.xml
Labels: Team: Core, Type: Test-Failure

#13530 Generate near cache invalidation upon expiration
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/ClientMapNearCacheInvalidationTest.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/AbstractEvictableRecordStore.java
  hazelcast/src/test/java/com/hazelcast/map/impl/nearcache/MapNearCacheInvalidationTest.java
  hazelcast/src/test/java/com/hazelcast/map/impl/nearcache/NearCacheTest.java
Labels: Interface: IMap, Team: Core, Type: Defect

#13476 Preparing Merkle tree IMap integration in OS
  hazelcast/src/main/java/com/hazelcast/map/impl/MapContainer.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapServiceContext.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapServiceContextImpl.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/AbstractRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/CompositeRecordStoreMutationObserver.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/DefaultRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/EventJournalUpdaterRecordStoreMutationObserver.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/RecordStoreMutationObserver.java
Labels: Interface: IMap, Team: Core, Type: Enhancement

#13556 Remove WAN consistency periodic check config
  hazelcast-spring/src/main/resources/hazelcast-spring-3.11.xsd
  hazelcast-spring/src/test/java/com/hazelcast/spring/TestFullApplicationContext.java
  hazelcast-spring/src/test/resources/com/hazelcast/spring/fullConfig-applicationContext-hazelcast.xml
  hazelcast/src/main/java/com/hazelcast/config/ConfigXmlGenerator.java
  hazelcast/src/main/java/com/hazelcast/config/WanSyncConfig.java
  hazelcast/src/main/java/com/hazelcast/config/XmlConfigBuilder.java
  hazelcast/src/main/resources/hazelcast-config-3.11.xsd
  hazelcast/src/main/resources/hazelcast-full-example.xml
  hazelcast/src/test/java/com/hazelcast/config/ConfigCompatibilityChecker.java
  hazelcast/src/test/java/com/hazelcast/config/ConfigXmlGeneratorTest.java
  hazelcast/src/test/java/com/hazelcast/config/XMLConfigBuilderTest.java
  hazelcast/src/test/resources/hazelcast-fullconfig.xml
Labels: Module: Config, Module: WAN, Team: Core

#13549 Fix OS metrics on IBM Java 8 and Java 9+
  hazelcast/src/main/java/com/hazelcast/internal/metrics/metricsets/OperatingSystemMetricSet.java
  hazelcast/src/test/java/com/hazelcast/internal/metrics/metricsets/OperatingSystemMetricSetTest.java
  pom.xml
Labels: Team: Core

#13571 Fix NPE if map is configured with undefined WAN replication
  hazelcast/src/main/java/com/hazelcast/map/impl/MapContainer.java
Labels: Interface: IMap, Team: Core, Type: Defect

#13567 Re-introduce setAccessible call to OperatingSystemMetricSet
  hazelcast/src/main/java/com/hazelcast/internal/metrics/metricsets/OperatingSystemMetricSet.java
  hazelcast/src/test/java/com/hazelcast/internal/metrics/impl/TestMetricsReader.java
  hazelcast/src/test/java/com/hazelcast/internal/metrics/metricsets/OperatingSystemMetricSetTest.java
  pom.xml
Labels: Type: Test-Failure

#13579 Use proper operation provider in MapIndexLifecycleTest
  hazelcast/src/test/java/com/hazelcast/map/MapIndexLifecycleTest.java
  hazelcast/src/test/java/com/hazelcast/test/HazelcastTestSupport.java
Labels: Team: Core, Type: Test-Failure

#13555 Revert "Generate near cache invalidation upon expiration"
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/ClientMapNearCacheInvalidationTest.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/AbstractEvictableRecordStore.java
  hazelcast/src/test/java/com/hazelcast/map/impl/nearcache/MapNearCacheInvalidationTest.java
  hazelcast/src/test/java/com/hazelcast/map/impl/nearcache/NearCacheTest.java
Labels: Interface: IMap, Team: Core

#13584 Introduced indexes builder
  hazelcast/src/main/java/com/hazelcast/map/impl/MapContainer.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapServiceContext.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapServiceContextImpl.java
  hazelcast/src/main/java/com/hazelcast/map/impl/PartitionContainer.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/AbstractInternalQueryCache.java
  hazelcast/src/main/java/com/hazelcast/monitor/impl/GlobalIndexesStats.java
  hazelcast/src/main/java/com/hazelcast/monitor/impl/GlobalPerIndexStats.java
  hazelcast/src/main/java/com/hazelcast/query/impl/DefaultIndexProvider.java
  hazelcast/src/main/java/com/hazelcast/query/impl/IndexHeapMemoryCostUtil.java
  hazelcast/src/main/java/com/hazelcast/query/impl/IndexProvider.java
  hazelcast/src/main/java/com/hazelcast/query/impl/Indexes.java
  hazelcast/src/test/java/com/hazelcast/query/impl/IndexTest.java
  hazelcast/src/test/java/com/hazelcast/query/impl/IndexesTest.java
Labels: Interface: IMap, Team: Core, Type: Enhancement

#13562 remove unnecessary extending of Distributed Object
  hazelcast/src/main/java/com/hazelcast/core/MultiMap.java
Labels: Type: Cleanup

#13248 Client Exponential Connection Retry
  checkstyle/suppressions.xml
  hazelcast-client/src/main/java/com/hazelcast/client/config/ClientConnectionStrategyConfig.java
  hazelcast-client/src/main/java/com/hazelcast/client/config/ConnectionRetryConfig.java
  hazelcast-client/src/main/java/com/hazelcast/client/config/XmlClientConfigBuilder.java
  hazelcast-client/src/main/java/com/hazelcast/client/connection/ClientConnectionStrategy.java
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClusterConnector.java
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/DefaultClientConnectionStrategy.java
  hazelcast-client/src/main/java/com/hazelcast/client/util/ClientStateListener.java
  hazelcast-client/src/main/resources/hazelcast-client-config-3.11.xsd
  hazelcast-client/src/main/resources/hazelcast-client-full.xml
  hazelcast-client/src/test/java/com/hazelcast/client/config/XmlClientConfigBuilderTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/connection/nio/ClusterConnectionRetryTest.java
  hazelcast-spring/src/main/java/com/hazelcast/spring/HazelcastClientBeanDefinitionParser.java
  hazelcast-spring/src/main/resources/hazelcast-spring-3.11.xsd
  hazelcast-spring/src/test/java/com/hazelcast/spring/TestClientApplicationContext.java
  hazelcast-spring/src/test/resources/com/hazelcast/spring/node-client-applicationContext-hazelcast.xml
Labels: Team: Client, Type: Enhancement

#13574 Add Merkle tree Management Center endpoint
  hazelcast/src/main/java/com/hazelcast/internal/management/ManagementCenterService.java
  hazelcast/src/main/java/com/hazelcast/internal/management/operation/WanCheckConsistencyOperation.java
  hazelcast/src/main/java/com/hazelcast/internal/management/request/ConsoleRequestConstants.java
  hazelcast/src/main/java/com/hazelcast/internal/management/request/WanCheckConsistencyRequest.java
  hazelcast/src/main/java/com/hazelcast/monitor/LocalWanPublisherStats.java
  hazelcast/src/main/java/com/hazelcast/monitor/impl/LocalWanPublisherStatsImpl.java
  hazelcast/src/main/java/com/hazelcast/wan/WanReplicationService.java
  hazelcast/src/main/java/com/hazelcast/wan/impl/WanReplicationServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/wan/merkletree/ConsistencyCheckResult.java
  hazelcast/src/test/java/com/hazelcast/internal/management/WanCheckConsistencyRequestTest.java
Labels: Team: Core, Type: Enhancement

#13593 Unified partition cleaning methods
  hazelcast/src/main/java/com/hazelcast/map/impl/MapMigrationAwareService.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapServiceContext.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapServiceContextImpl.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/RecordStore.java
Labels: Team: Core, Type: Enhancement

#13598 Configurable map eviction batch size
  hazelcast/src/main/java/com/hazelcast/map/impl/MapContainer.java
  hazelcast/src/main/java/com/hazelcast/map/impl/eviction/EvictorImpl.java
  hazelcast/src/main/java/com/hazelcast/spi/properties/GroupProperty.java
  hazelcast/src/test/java/com/hazelcast/map/EvictionMaxSizePolicyTest.java
  hazelcast/src/test/java/com/hazelcast/map/EvictionTest.java
Labels: Interface: IMap, Type: Enhancement

#13224 moved parameter creation part into another method at PhoneHome - related to OEM changes
  hazelcast/src/main/java/com/hazelcast/instance/DefaultNodeExtension.java
  hazelcast/src/main/java/com/hazelcast/instance/Node.java
  hazelcast/src/main/java/com/hazelcast/instance/NodeExtension.java
  hazelcast/src/main/java/com/hazelcast/util/PhoneHome.java
  hazelcast/src/test/java/com/hazelcast/test/compatibility/SamplingNodeExtension.java
  hazelcast/src/test/java/com/hazelcast/util/PhoneHomeTest.java
Labels: Team: Integration, Type: Enhancement

#13386 [BACKPORT] moved parameter creation part into another method at PhoneHome - related to OEM changes
  hazelcast/src/main/java/com/hazelcast/instance/DefaultNodeExtension.java
  hazelcast/src/main/java/com/hazelcast/instance/Node.java
  hazelcast/src/main/java/com/hazelcast/instance/NodeExtension.java
  hazelcast/src/main/java/com/hazelcast/util/PhoneHome.java
  hazelcast/src/test/java/com/hazelcast/test/compatibility/SamplingNodeExtension.java
  hazelcast/src/test/java/com/hazelcast/util/PhoneHomeTest.java
Labels: Team: Integration, Type: Enhancement

#13601 Revert "Exceptional responses"
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/IExecutorDelegatingFuture.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientInvocation.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientInvocationFuture.java
  hazelcast-client/src/main/java/com/hazelcast/client/util/ClientDelegatingFuture.java
  hazelcast-client/src/test/java/com/hazelcast/client/spi/impl/ClientInvocationFutureTest.java
  hazelcast/src/main/java/com/hazelcast/durableexecutor/impl/operations/RetrieveAndDisposeResultOperation.java
  hazelcast/src/main/java/com/hazelcast/durableexecutor/impl/operations/RetrieveResultOperation.java
  hazelcast/src/main/java/com/hazelcast/executor/impl/CancellableDelegatingFuture.java
  hazelcast/src/main/java/com/hazelcast/internal/util/LocalRetryableExecution.java
  hazelcast/src/main/java/com/hazelcast/spi/InternalCompletableFuture.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractInvocationFuture.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/InboundResponseHandler.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFuture.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/InvokeOnPartitions.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationRunnerImpl.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/operations/PartitionIteratingOperation.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/responses/ErrorResponse.java
  hazelcast/src/main/java/com/hazelcast/util/executor/CompletedFuture.java
  hazelcast/src/main/java/com/hazelcast/util/executor/DelegatingFuture.java
  hazelcast/src/test/java/com/hazelcast/concurrent/atomicreference/AtomicReferenceAbstractTest.java
  hazelcast/src/test/java/com/hazelcast/internal/partition/MigrationAwareServiceEventTest.java
  hazelcast/src/test/java/com/hazelcast/spi/impl/AbstractInvocationFuture_AbstractTest.java
  hazelcast/src/test/java/com/hazelcast/spi/impl/AbstractInvocationFuture_AndThenTest.java
  hazelcast/src/test/java/com/hazelcast/spi/impl/AbstractInvocationFuture_GetSafely.java
  hazelcast/src/test/java/com/hazelcast/spi/impl/AbstractInvocationFuture_JoinTest.java
  hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InboundResponseHandler_NotifyTest.java
  hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/OperationRunnerImplTest.java
  hazelcast/src/test/java/com/hazelcast/util/executor/DelegatingFutureTest.java
Labels: Team: Core

#13501 Introduced system property to provide backward
  hazelcast-client/src/test/java/com/hazelcast/client/map/ClientEntryLoadedListenerTest.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapContainer.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/DefaultRecordStore.java
  hazelcast/src/main/java/com/hazelcast/query/impl/Indexes.java
  hazelcast/src/main/java/com/hazelcast/spi/properties/GroupProperty.java
  hazelcast/src/test/java/com/hazelcast/map/EntryLoadedListenerCompatibleModeTest.java
  hazelcast/src/test/java/com/hazelcast/map/EntryLoadedListenerTest.java
  hazelcast/src/test/java/com/hazelcast/map/InterceptorTest.java
  hazelcast/src/test/java/com/hazelcast/map/impl/mapstore/LoadAllTest.java
  hazelcast/src/test/java/com/hazelcast/map/impl/mapstore/MapStoreTest.java
Labels: Team: Core

#13595 Fixes test that does not respect ByteOrder overrides
  hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/DefaultSerializationServiceBuilderTest.java
Labels: Team: Core, Type: Test-Failure

#13591 JCache automatic expiration tests improvement
  hazelcast/src/test/java/com/hazelcast/cache/CacheBasicAbstractTest.java
  hazelcast/src/test/java/com/hazelcast/cache/eviction/CacheExpirationTest.java
  hazelcast/src/test/java/com/hazelcast/internal/eviction/AbstractExpirationManagerTest.java
  hazelcast/src/test/java/com/hazelcast/internal/eviction/CacheExpirationManagerTest.java
  hazelcast/src/test/java/com/hazelcast/internal/eviction/MapExpirationManagerTest.java
Labels: Team: Core

#13606 Minor TaskScheduler JavaDoc improvement
  hazelcast/src/main/java/com/hazelcast/spi/TaskScheduler.java
Labels: Team: Core, Type: Enhancement

#13178 Hint at possible compatibility issue when serialization exception occurs
  hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationRunnerImpl.java
Labels: Module: Rolling Upgrade, Team: Core, Type: Enhancement

#13603 Renaming in networking
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientPlainChannelInitializer.java
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientProtocolEncoder.java
  hazelcast-client/src/main/java/com/hazelcast/client/impl/clientside/HazelcastClientInstanceImpl.java
  hazelcast-client/src/test/java/com/hazelcast/client/test/TestClientRegistry.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/util/ClientMessageDecoder.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/util/ClientMessageEncoder.java
  hazelcast/src/main/java/com/hazelcast/instance/DefaultNodeContext.java
  hazelcast/src/main/java/com/hazelcast/instance/DefaultNodeExtension.java
  hazelcast/src/main/java/com/hazelcast/instance/NodeExtension.java
  hazelcast/src/main/java/com/hazelcast/internal/diagnostics/NetworkingImbalancePlugin.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/Channel.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/ChannelErrorHandler.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/ChannelHandler.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/ChannelOption.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/ChannelOptions.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/InboundHandler.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/InboundPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/Networking.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/OutboundFrame.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/OutboundHandler.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/OutboundPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/InboundHandlerWithCounters.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioChannel.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioChannelOptions.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioInboundPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioNetworking.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioOutboundPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/package-info.java
  hazelcast/src/main/java/com/hazelcast/nio/IOService.java
  hazelcast/src/main/java/com/hazelcast/nio/NodeIOService.java
  hazelcast/src/main/java/com/hazelcast/nio/ascii/TextDecoder.java
  hazelcast/src/main/java/com/hazelcast/nio/ascii/TextEncoder.java
  hazelcast/src/main/java/com/hazelcast/nio/tcp/PacketDecoder.java
  hazelcast/src/main/java/com/hazelcast/nio/tcp/PacketEncoder.java
  hazelcast/src/main/java/com/hazelcast/nio/tcp/PlainChannelInitializer.java
  hazelcast/src/main/java/com/hazelcast/nio/tcp/ProtocolDecoder.java
  hazelcast/src/main/java/com/hazelcast/nio/tcp/ProtocolEncoder.java
  hazelcast/src/main/java/com/hazelcast/nio/tcp/TcpIpConnection.java
  hazelcast/src/main/java/com/hazelcast/nio/tcp/TcpIpConnectionManager.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/AbstractChannelTest.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/SelectNow_NioNetworkingFactory.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/SelectNow_TcpIpConnectionManager_ConnectMemberTest.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/SelectNow_TcpIpConnection_BasicTest.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/SelectNow_TcpIpConnection_TransferStressTest.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/SelectWithSelectorFix_NioNetworkingFactory.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/SelectWithSelectorFix_TcpIpConnectionManager_ConnectMemberTest.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/SelectWithSelectorFix_TcpIpConnection_BasicTest.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/SelectWithSelectorFix_TcpIpConnection_TransferStressTest.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/Select_NioNetworkingFactory.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/Select_TcpIpConnectionManager_ConnectMemberTest.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/Select_TcpIpConnection_BasicTest.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/Select_TcpIpConnection_TransferStressTest.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/iobalancer/IOBalancerMemoryLeakTest.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/iobalancer/IOBalancerStressTest.java
  hazelcast/src/test/java/com/hazelcast/nio/tcp/MockIOService.java
  hazelcast/src/test/java/com/hazelcast/nio/tcp/NetworkingFactory.java
  hazelcast/src/test/java/com/hazelcast/nio/tcp/TcpIpConnection_AbstractTest.java
  hazelcast/src/test/java/com/hazelcast/test/compatibility/SamplingNodeExtension.java
Labels: Type: Cleanup

#13599 Merkle comparision & sync
  hazelcast/src/main/java/com/hazelcast/map/impl/MapDataSerializerHook.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MerkleTreeNodeEntries.java
  hazelcast/src/main/java/com/hazelcast/monitor/impl/LocalWanPublisherStatsImpl.java
  hazelcast/src/main/java/com/hazelcast/spi/OperationService.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/InvokeOnPartitions.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/wan/WanReplicationService.java
  hazelcast/src/main/java/com/hazelcast/wan/impl/DistributedServiceWanEventCounters.java
  hazelcast/src/main/java/com/hazelcast/wan/merkletree/ConsistencyCheckResult.java
  hazelcast/src/main/java/com/hazelcast/wan/merkletree/MerkleTreeUtil.java
Labels: Module: WAN, Team: Core, Type: Enhancement

#13607 Speed up closing Hazelcast connections in tests.
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioChannel.java
  hazelcast/src/test/java/com/hazelcast/test/AbstractHazelcastClassRunner.java
Labels: Team: Core, Type: Test-Failure

#13612 [DO NOT MERGE] Allow negative diffs when calculating relative record times
  hazelcast/src/main/java/com/hazelcast/map/impl/record/AbstractRecord.java
Labels: Team: Core, Type: Test-Failure

#13613 Fixes EmbeddedMapInterceptorTest incorrect sync call assumption
  hazelcast/src/test/java/com/hazelcast/map/EmbeddedMapInterceptorTest.java
Labels: Team: Core, Type: Test-Failure

#13605 Improve TLS/SSL snippets in full config examples
  hazelcast-client/src/main/resources/hazelcast-client-full.xml
  hazelcast-client/src/test/java/com/hazelcast/client/config/XmlClientConfigBuilderTest.java
  hazelcast/src/main/resources/hazelcast-full-example.xml
Labels: Team: Client, Type: Enhancement

#13615 Minor javadoc improvement com.hz.logging package.info
  hazelcast/src/main/java/com/hazelcast/logging/package-info.java
Labels: Type: Cleanup

#13608 Minor javadoc improvement Networking
  hazelcast/src/main/java/com/hazelcast/internal/networking/Networking.java
Labels: Team: Core, Type: Cleanup

#13627 Fix counter reset when ChannelHandlers change in the pipeline.
  hazelcast/src/main/java/com/hazelcast/internal/networking/OutboundHandler.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioInboundPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioOutboundPipeline.java
Labels: Team: Core, Type: Test-Failure

#13633 [BACKPORT] Increases wait time in cache expiration backup test
  hazelcast/src/test/java/com/hazelcast/cache/eviction/CacheExpirationTest.java
Labels: Team: Core, Type: Test-Failure

#13628 [BACKPORT] Fix counter reset when ChannelHandlers change in the pipeline.
  hazelcast/src/main/java/com/hazelcast/internal/networking/OutboundHandler.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioInboundPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioOutboundPipeline.java
Labels: Team: Core, Type: Defect, Type: Test-Failure

#13635 Prepare ExpirationTimeTest for subclassing in EE side
  hazelcast/src/test/java/com/hazelcast/map/ExpirationTimeTest.java
Labels: Team: Core, Type: Defect

#13625 [3.11] Fix remove WAN event cycle
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/BaseRemoveOperation.java
  hazelcast/src/test/java/com/hazelcast/map/impl/operation/RemoveBaseOperationWanFlagSerializationTest.java
Labels: Module: WAN, Team: Core, Type: Defect

#13623 [3.10.x] Fix remove WAN event cycle
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/BaseRemoveOperation.java
  hazelcast/src/test/java/com/hazelcast/map/impl/operation/RemoveBaseOperationWanFlagSerializationTest.java
Labels: Module: WAN, Team: Core, Type: Defect

#13561 fix typo in lifecycle state
  hazelcast/src/main/java/com/hazelcast/core/LifecycleEvent.java
Labels: Team: Documentation

#13503 Remove AWS IPv4 enforcement
  hazelcast/src/main/java/com/hazelcast/instance/DefaultAddressPicker.java
Labels: Team: Core

#13497 [BACKPORT] Account for partitioned indexes when iterating
  hazelcast/src/main/java/com/hazelcast/map/impl/query/QueryRunner.java
  hazelcast/src/test/java/com/hazelcast/map/MapQueryPartitionIteratorTest.java
Labels: Backport, Interface: IMap, Team: Core, Type: Defect

#13493 Account for partitioned indexes when iterating
  hazelcast/src/main/java/com/hazelcast/map/impl/query/QueryRunner.java
  hazelcast/src/test/java/com/hazelcast/map/MapQueryPartitionIteratorTest.java
Labels: Interface: IMap, Team: Core, Type: Defect

#13586 Unified partition cleaning methods - 2
  hazelcast/src/main/java/com/hazelcast/map/impl/MapMigrationAwareService.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapServiceContext.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapServiceContextImpl.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapSplitBrainHandlerService.java
  hazelcast/src/main/java/com/hazelcast/map/impl/PartitionContainer.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/DefaultRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/RecordStore.java
  hazelcast/src/main/java/com/hazelcast/query/impl/Indexes.java
Labels: Team: Core, Type: Enhancement

#13632 Fix RU issue with undefined MaxIdle in incoming stream
  hazelcast/src/main/java/com/hazelcast/map/impl/record/AbstractRecord.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/AbstractEvictableRecordStore.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/merge/MapMergingEntryImpl.java
  hazelcast/src/main/java/com/hazelcast/spi/merge/MergingMaxIdle.java
Labels: Team: Core, Type: Test-Failure

#13644 Made removeAllRecordStoresOfAllMaps protected
  hazelcast/src/main/java/com/hazelcast/map/impl/MapServiceContextImpl.java
Labels: Interface: IMap, Team: Core

#13647 Fix checkstyle for EPOCH_TIME field
  hazelcast/src/main/java/com/hazelcast/map/impl/record/AbstractRecord.java
Labels: Team: Core

#13646 Fix RU issue with undefined MaxIdle in incoming stream
  hazelcast/src/main/java/com/hazelcast/map/impl/record/AbstractRecord.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/AbstractEvictableRecordStore.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/merge/MapMergingEntryImpl.java
  hazelcast/src/main/java/com/hazelcast/spi/merge/MergingMaxIdle.java
Labels: Team: Core, Type: Test-Failure

#13552 Fix lock timeout behaviour when key owner is gone
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientConditionProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientLockProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/PartitionSpecificClientProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientInvocation.java
  hazelcast-client/src/test/java/com/hazelcast/client/lock/ClientLockTest.java
  hazelcast/src/test/java/com/hazelcast/concurrent/lock/LockAdvancedTest.java
Labels: Team: Client, Type: Defect

#13554 Fix lock timeout behaviour when key owner is gone
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientConditionProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientLockProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/PartitionSpecificClientProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientInvocation.java
  hazelcast-client/src/test/java/com/hazelcast/client/lock/ClientLockTest.java
  hazelcast/src/test/java/com/hazelcast/concurrent/lock/LockAdvancedTest.java
Labels: Backport, Team: Client, Type: Defect

#13577 Server should not close clients when client only listens
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/HeartbeatManager.java
  hazelcast-client/src/test/java/com/hazelcast/client/ClientRegressionWithMockNetworkTest.java
Labels: Team: Client, Type: Defect

#13578 Server should not close clients when client only listens
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/HeartbeatManager.java
  hazelcast-client/src/test/java/com/hazelcast/client/ClientRegressionWithMockNetworkTest.java
Labels: Backport, Team: Client, Type: Defect

#13649 removing upper bound check from ClusterConnectionRetryTest
  hazelcast-client/src/test/java/com/hazelcast/client/connection/nio/ClusterConnectionRetryTest.java
Labels: Cause: Test - Timing, Type: Test-Failure

#13643 Renamed 3.11 group property
  hazelcast/src/main/java/com/hazelcast/map/impl/MapContainer.java
  hazelcast/src/main/java/com/hazelcast/spi/properties/GroupProperty.java
  hazelcast/src/test/java/com/hazelcast/map/EntryLoadedListenerCompatibleModeTest.java
  hazelcast/src/test/java/com/hazelcast/map/InterceptorTest.java
Labels: Interface: IMap, Team: Core

#13575 Refactored client query cache server-response handling code paths.
  hazelcast-client/src/main/java/com/hazelcast/client/impl/querycache/subscriber/ClientQueryCacheEndToEndConstructor.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/MapPublisherCreateMessageTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/MapPublisherCreateWithValueMessageTask.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/AbstractInternalQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/AbstractQueryCacheEndToEndConstructor.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/DefaultQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/DefaultQueryCacheRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/InternalQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/NodeQueryCacheEndToEndConstructor.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/NullQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/QueryCacheRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/SubscriberAccumulatorHandler.java
Labels: Team: Client, Team: Core, Type: Perf. Defect

#13652 Modify test to make it non-java client friendly
  hazelcast-client/src/test/java/com/hazelcast/client/ClientRegressionWithMockNetworkTest.java
Labels: Team: Client, Type: Enhancement

#13665 [FORWARD PORT] Refactored client query cache server-response handling code paths.
  hazelcast-client/src/main/java/com/hazelcast/client/impl/querycache/subscriber/ClientQueryCacheEndToEndConstructor.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/MapPublisherCreateMessageTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/MapPublisherCreateWithValueMessageTask.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/AbstractInternalQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/AbstractQueryCacheEndToEndConstructor.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/DefaultQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/DefaultQueryCacheRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/InternalQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/NodeQueryCacheEndToEndConstructor.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/NullQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/QueryCacheRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/SubscriberAccumulatorHandler.java
Labels: Team: Client, Team: Core, Type: Perf. Defect

#13650 Fix map entry with custom max-idle doesn't send expiration notification to backups
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/AbstractEvictableRecordStore.java
  hazelcast/src/test/java/com/hazelcast/map/EvictionTest.java
Labels: Team: Core, Type: Test-Failure

#13661 LocalWanStatsImpl toString impl
  hazelcast/src/main/java/com/hazelcast/monitor/impl/LocalWanStatsImpl.java
Labels: Module: WAN, Team: Core, Type: Enhancement

#13669 Assert port available for binding when a test is over
  hazelcast/src/test/java/com/hazelcast/nio/tcp/TcpIpConnection_AbstractTest.java
Labels: Team: Core, Type: Enhancement

#13655 [BACKPORT] OperationThreadSampleDiagnostics
  hazelcast/src/main/java/com/hazelcast/instance/DefaultNodeExtension.java
  hazelcast/src/main/java/com/hazelcast/internal/diagnostics/OperationThreadSamplerPlugin.java
  hazelcast/src/main/java/com/hazelcast/util/ItemCounter.java
  hazelcast/src/test/java/com/hazelcast/util/ItemCounterTest.java
Labels: Type: Enhancement

#13648 OperationThreadSampleDiagnostics
  hazelcast/src/main/java/com/hazelcast/instance/DefaultNodeExtension.java
  hazelcast/src/main/java/com/hazelcast/internal/diagnostics/OperationThreadSamplerPlugin.java
  hazelcast/src/main/java/com/hazelcast/util/ItemCounter.java
  hazelcast/src/test/java/com/hazelcast/util/ItemCounterTest.java
Labels: Team: Core, Team: QuSP, Type: Enhancement

#13670 Whitelist "process reaper thread" in the Thread Leak Tests
  hazelcast/src/test/java/classloading/ThreadLeakTestUtils.java
Labels: Team: Core, Type: Defect
