Repository hazelcast/hazelcast, pull requests merged in 2018-03, with the labels that each got.

#12456 Write javadoc for IndexAwarePredicate and related classes
  hazelcast/src/main/java/com/hazelcast/query/IndexAwarePredicate.java
  hazelcast/src/main/java/com/hazelcast/query/Predicate.java
  hazelcast/src/main/java/com/hazelcast/query/impl/Index.java
  hazelcast/src/main/java/com/hazelcast/query/impl/QueryContext.java
Labels: Team: Core, Team: Documentation, Type: Enhancement

#12461 Check local member uuid under the cluster service lock
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterJoinManager.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/operations/FinalizeJoinOp.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/operations/MembersUpdateOp.java
  hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/MembershipUpdateTest.java
Labels: Team: Core, Type: Defect

#12446 Test DynamicConfigurationAwareConfig overrides all public methods of Config
  hazelcast-client/src/main/java/com/hazelcast/client/impl/ClientDynamicClusterConfig.java
  hazelcast-client/src/test/java/com/hazelcast/client/impl/ClientDynamicConfigurationAwareConfigTest.java
  hazelcast/src/test/java/com/hazelcast/internal/dynamicconfig/DynamicConfigurationAwareConfigTest.java
Labels: Team: Client, Team: Core, Type: Enhancement

#12458 Fixed OverridePropertyRule with PowerMock
  hazelcast/src/main/java/com/hazelcast/instance/DefaultAddressPicker.java
  hazelcast/src/test/java/com/hazelcast/instance/DefaultAddressPickerInterfacesTest.java
  hazelcast/src/test/java/com/hazelcast/instance/DefaultAddressPickerTest.java
  hazelcast/src/test/java/com/hazelcast/spi/discovery/multicast/MemberToMemberDiscoveryTest.java
  hazelcast/src/test/java/com/hazelcast/test/OverridePropertyRulePowerMockTest.java
  hazelcast/src/test/java/com/hazelcast/test/OverridePropertyRuleTest.java
  pom.xml
Labels: Team: Core, Type: Test-Failure

#12467 Decrease schedule_withMapChanges_durable loop count
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/ScheduledExecutorServiceBasicTest.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/ScheduledExecutorServiceTestSupport.java
  hazelcast/src/test/java/com/hazelcast/test/HazelcastTestSupport.java
Labels: Interface: IScheduledExecutor, Team: Core, Type: Defect

#12431 Fix partition listener in IScheduledFutureProxy
  hazelcast-client/src/test/java/com/hazelcast/client/scheduledexecutor/ClientScheduledExecutorServiceBasicTest.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/DistributedScheduledExecutorService.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledFutureProxy.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/ScheduledExecutorServiceBasicTest.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/ScheduledExecutorSplitBrainTest.java
Labels: Interface: IScheduledExecutor, Team: Core, Type: Defect

#12463 Remove required attribute from group tag for both name and password
  hazelcast-spring/src/main/resources/hazelcast-spring-3.10.xsd
Labels: Team: Core, Type: Enhancement

#12464 Check NATIVE data can be merged with provided merge policy
  hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxyUtil.java
  hazelcast/src/main/java/com/hazelcast/internal/config/ConfigValidator.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/merge/AbstractMergeRunnable.java
Labels: Team: Core

#12477 Drop legacy merge policy for cache
  hazelcast/src/main/java/com/hazelcast/config/CacheSimpleConfig.java
  hazelcast/src/main/java/com/hazelcast/config/MergePolicyConfig.java
  hazelcast/src/main/java/com/hazelcast/config/ReplicatedMapConfig.java
  hazelcast/src/main/resources/hazelcast-default.xml
Labels: Team: Core

#12483 Protect against oversleeping of HazelcastTestSupport#sleepAndStop
  hazelcast/src/test/java/com/hazelcast/test/HazelcastTestSupport.java
Labels: Team: Core, Type: Enhancement

#12449 Evict map during migration
  hazelcast/src/main/java/com/hazelcast/map/impl/eviction/EvictionChecker.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/MapReplicationStateHolder.java
  hazelcast/src/test/java/com/hazelcast/map/EvictionMaxSizePolicyTest.java
Labels: Team: Core, Type: Defect

#12487 Increase validity for flakeIds concurrent smoke test
  hazelcast/src/test/java/com/hazelcast/flakeidgen/impl/AutoBatcherTest.java
Labels: Interface: FlakeIDGenerator, Team: Core, Type: Test-Failure

#12472 Remove 3.8 rolling upgrade checks for ringbuffer and event journal
  hazelcast/src/main/java/com/hazelcast/cache/impl/journal/CacheEventJournalSubscribeOperation.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/journal/RingbufferCacheEventJournalImpl.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/cache/CacheEventJournalReadTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/cache/CacheEventJournalSubscribeTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/MapEventJournalReadTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/MapEventJournalSubscribeTask.java
  hazelcast/src/main/java/com/hazelcast/internal/journal/EventJournal.java
  hazelcast/src/main/java/com/hazelcast/internal/journal/EventJournalReadOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/journal/MapEventJournalSubscribeOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/journal/RingbufferMapEventJournalImpl.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/ReadResultSetImpl.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferContainer.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferService.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/client/PortableReadResultSet.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/operations/ReplicationOperation.java
Labels: Team: Core, Type: Cleanup

#12488 Increase write-behind delay in test
  hazelcast/src/test/java/com/hazelcast/map/impl/mapstore/MapStoreWriteBehindTest.java
Labels: Interface: IMap, Team: Core, Type: Test-Failure

#12492 Increase connection-attempt-limit for ClientToMemberDiscoveryTest
  hazelcast/src/test/resources/hazelcast-client-multicast-plugin.xml
Labels: Team: Client, Type: Test-Failure

#12491 Defer collection of replication data until serialization stage
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/MapReplicationOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/MapReplicationStateHolder.java
Labels: Team: Core

#12494 Ignore NoHttpResponseException when shutting down a member via Rest
  hazelcast/src/test/java/com/hazelcast/internal/ascii/RestClusterTest.java
Labels: Team: Core, Type: Defect

#12481 Do not break the text command loop on error
  hazelcast/src/main/java/com/hazelcast/internal/ascii/TextCommandServiceImpl.java
Labels: Team: Core, Type: Defect

#12496 Fix cluster lock lease time extension
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterStateManager.java
  hazelcast/src/main/java/com/hazelcast/internal/util/LockGuard.java
  hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/AdvancedClusterStateTest.java
Labels: Team: Core, Type: Defect

#12385 Observe contract of CacheEntryEvent#getValue for REMOVED/EXPIRED events
  hazelcast/src/main/java/com/hazelcast/cache/impl/CacheEventListenerAdaptor.java
  hazelcast/src/test/java/com/hazelcast/cache/jsr/CacheListenerTest.java
Labels: Team: Core, Type: Defect

#12499 Decrease resource usage on QueryBounceTest and other tests
  hazelcast/src/test/java/com/hazelcast/collection/impl/queue/QueueTestsFrom2X.java
  hazelcast/src/test/java/com/hazelcast/map/MapListenerTest.java
  hazelcast/src/test/java/com/hazelcast/map/QueryBounceTest.java
  hazelcast/src/test/java/com/hazelcast/ringbuffer/impl/RingbufferAddAllReadManyStressTest.java
  hazelcast/src/test/java/com/hazelcast/spi/impl/operationexecutor/impl/OperationExecutorImpl_AbstractTest.java
  hazelcast/src/test/java/com/hazelcast/test/HazelcastTestSupport.java
Labels: Team: Core, Type: Test-Failure

#12490 Remove 3.8 compat code in AbstractRegistrationOperation
  hazelcast/src/main/java/com/hazelcast/spi/impl/eventservice/impl/operations/AbstractRegistrationOperation.java
Labels: Team: Core, Type: Cleanup

#12500 Add warning comments for cluster classes which should remain Versioned
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/SplitBrainJoinMessage.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/operations/HeartbeatOp.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/operations/MasterConfirmationOp.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/operations/MembersUpdateOp.java
Labels: Team: Core, Type: Cleanup

#12489 Remove remaining 3.8 compat codes in partition package
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/InternalPartitionServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/PartitionReplicaManager.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/operation/PartitionBackupReplicaAntiEntropyOperation.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/operation/PartitionReplicaSyncRequest.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/operation/PartitionReplicaSyncResponse.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/operation/PartitionReplicaSyncRetryResponse.java
Labels: Team: Core, Type: Cleanup

#12468 Add more log to test MapStoreDataLoadingContinuesWhenNodeJoins
  hazelcast/src/test/java/com/hazelcast/map/impl/mapstore/MapStoreDataLoadingContinuesWhenNodeJoins.java
Labels: Interface: IMap, Team: Core, Type: Enhancement

#12509 Minor ClientConnection.equals cleanup
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnection.java
Labels: Team: Client, Type: Cleanup

#12507 [BACKPORT] Observe contract of CacheEntryEvent#getValue for REMOVED/EXPIRED events
  hazelcast/src/main/java/com/hazelcast/cache/impl/CacheEventListenerAdaptor.java
  hazelcast/src/test/java/com/hazelcast/cache/jsr/CacheListenerTest.java
Labels: Backport, Team: Core, Type: Defect

#12510 Added warnings to socket interceptors about TLS bypass
  hazelcast/src/main/java/com/hazelcast/nio/MemberSocketInterceptor.java
  hazelcast/src/main/java/com/hazelcast/nio/SocketInterceptor.java
Labels: Type: Enhancement

#12513 Override client-side CacheListenerTest to use correct entry filter
  hazelcast-client/src/test/java/com/hazelcast/client/cache/jsr/CacheListenerTest.java
  hazelcast/src/test/java/com/hazelcast/cache/jsr/AbstractCacheListenerTest.java
  hazelcast/src/test/java/com/hazelcast/cache/jsr/CacheListenerTest.java
Labels: Interface: ICache, Team: Core, Type: Test-Failure

#12504 Fix ICardinalityEstimator conversion from SPARSE to DENSE
  hazelcast/src/main/java/com/hazelcast/cardinality/impl/hyperloglog/impl/HyperLogLogImpl.java
  hazelcast/src/main/java/com/hazelcast/cardinality/impl/hyperloglog/impl/SparseHyperLogLogEncoder.java
  hazelcast/src/test/java/com/hazelcast/cardinality/impl/hyperloglog/impl/HyperLogLogImplTest.java
  hazelcast/src/test/java/com/hazelcast/cardinality/impl/hyperloglog/impl/SparseHyperLogLogEncoderTest.java
Labels: Interface: CardinalityEstimator, Source: Internal, Team: Core, Type: Defect

#12482 Fixed FindBugs issue in PhoneHome
  hazelcast/src/main/java/com/hazelcast/util/PhoneHome.java
  hazelcast/src/test/java/com/hazelcast/util/PhoneHomeTest.java
Labels: Type: Cleanup, Type: Defect

#12517 Add eventual cluster size assertions to AdvancedClusterStateTest
  hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/AdvancedClusterStateTest.java
Labels: Team: Core, Type: Test-Failure

#12514 [BACKPORT] Override client-side CacheListenerTest to use correct entry filter
  hazelcast-client/src/test/java/com/hazelcast/client/cache/jsr/CacheListenerTest.java
  hazelcast/src/test/java/com/hazelcast/cache/jsr/AbstractCacheListenerTest.java
  hazelcast/src/test/java/com/hazelcast/cache/jsr/CacheListenerTest.java
Labels: Backport, Interface: ICache, Team: Core, Type: Test-Failure

#12512 Fail fast only if cluster version is >= 3.10
  hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxyUtil.java
  hazelcast/src/main/java/com/hazelcast/internal/config/ConfigValidator.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapRemoteService.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/merge/AbstractMergeRunnable.java
Labels: Team: Core, Type: Defect

#12508 Make mastership claim idempotent and retry until timeouts or target leaves
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/MembershipManager.java
  hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/MemberListJoinVersionTest.java
  hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/MembershipFailureTest.java
  hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/MembershipUpdateTest.java
  hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/PromoteLiteMemberTest.java
  hazelcast/src/test/java/com/hazelcast/internal/partition/AntiEntropyCorrectnessTest.java
  hazelcast/src/test/java/com/hazelcast/internal/partition/DirtyBackupTest.java
  hazelcast/src/test/java/com/hazelcast/nio/tcp/FirewallingConnectionManager.java
  hazelcast/src/test/java/com/hazelcast/nio/tcp/OperationPacketFilter.java
  hazelcast/src/test/java/com/hazelcast/nio/tcp/PacketFilter.java
  hazelcast/src/test/java/com/hazelcast/test/PacketFiltersUtil.java
Labels: Team: Core, Type: Defect

#12374 Move ClientJoinOperation to PreJoin
  hazelcast-client/src/test/java/com/hazelcast/client/ClientOwnershipTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/ClientReconnectTest.java
  hazelcast/src/main/java/com/hazelcast/client/impl/ClientDataSerializerHook.java
  hazelcast/src/main/java/com/hazelcast/client/impl/ClientEngineImpl.java
  hazelcast/src/main/java/com/hazelcast/client/impl/operations/ClientDisconnectionOperation.java
  hazelcast/src/main/java/com/hazelcast/client/impl/operations/ClientReAuthOperation.java
  hazelcast/src/main/java/com/hazelcast/client/impl/operations/OnJoinClientOperation.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/AbstractStableClusterMessageTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/AuthenticationBaseMessageTask.java
  hazelcast/src/main/java/com/hazelcast/spi/ExecutionService.java
  hazelcast/src/test/java/com/hazelcast/quorum/QuorumOperationTest.java
Labels: Team: Client, Type: Defect

#12375 Move ClientJoinOperation to PreJoin
  hazelcast-client/src/test/java/com/hazelcast/client/ClientOwnershipTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/ClientReconnectTest.java
  hazelcast/src/main/java/com/hazelcast/client/impl/ClientDataSerializerHook.java
  hazelcast/src/main/java/com/hazelcast/client/impl/ClientEngineImpl.java
  hazelcast/src/main/java/com/hazelcast/client/impl/operations/ClientDisconnectionOperation.java
  hazelcast/src/main/java/com/hazelcast/client/impl/operations/ClientReAuthOperation.java
  hazelcast/src/main/java/com/hazelcast/client/impl/operations/OnJoinClientOperation.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/AbstractStableClusterMessageTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/AuthenticationBaseMessageTask.java
  hazelcast/src/main/java/com/hazelcast/spi/ExecutionService.java
Labels: Backport, Team: Client, Type: Defect

#12415 Relaxing owner connection check for client invocations
  hazelcast-client/src/main/java/com/hazelcast/client/connection/ClientConnectionManager.java
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/txn/TransactionProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/txn/xa/XAResourceProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/SmartClientInvocationService.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/listener/SmartClientListenerService.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/properties/ClientProperty.java
  hazelcast-client/src/test/java/com/hazelcast/client/ClientRegressionWithRealNetworkTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/spi/impl/ClientConnectionManagerTranslateTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/txn/ClientTxnOwnerDisconnectedTest.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientMessage.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/transaction/XACollectTransactionsMessageTask.java
Labels: Team: Client

#12524 Invocation_NetworkSplitTest cleanup
  hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/Invocation_NetworkSplitTest.java
Labels: Team: Core, Type: Test-Failure

#12498 Remove clearMapOnly method on MapProxyImpl
  hazelcast/src/main/java/com/hazelcast/map/impl/proxy/MapProxyImpl.java
Labels: Team: Core, Type: Cleanup

#11782 [FORWARD-PORT] Improve WAN diagnostics
  hazelcast-client/src/test/java/com/hazelcast/client/flakeidgen/impl/FlakeIdGenerator_ClientBackpressureTest.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapReplicationSupportingService.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapServiceContextImpl.java
  hazelcast/src/main/java/com/hazelcast/map/impl/wan/MapReplicationRemove.java
  hazelcast/src/main/java/com/hazelcast/map/impl/wan/MapReplicationUpdate.java
  hazelcast/src/main/java/com/hazelcast/monitor/LocalWanPublisherStats.java
  hazelcast/src/main/java/com/hazelcast/monitor/impl/LocalWanPublisherStatsImpl.java
  hazelcast/src/main/java/com/hazelcast/spi/ReplicationSupportingService.java
  hazelcast/src/main/java/com/hazelcast/wan/ReplicationEventObject.java
  hazelcast/src/main/java/com/hazelcast/wan/WanReplicationService.java
  hazelcast/src/main/java/com/hazelcast/wan/impl/WanEventCounter.java
  hazelcast/src/main/java/com/hazelcast/wan/impl/WanEventCounterContainer.java
  hazelcast/src/main/java/com/hazelcast/wan/impl/WanReplicationServiceImpl.java
Labels: Module: WAN, Team: Core, Type: Enhancement

#12476 Added automated test to check for missing Versioned implementations
  hazelcast/src/main/java/com/hazelcast/config/QueueConfig.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterHeartbeatManager.java
  hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/DataSerializableConventionsTest.java
  hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/DataSerializableImplementsVersionedTest.java
  hazelcast/src/test/java/com/hazelcast/test/ReflectionsHelper.java
Labels: Team: Core, Type: Defect, Type: Enhancement

#12521 Move long running parameterized near cache tests to slow test category
  hazelcast-client/src/test/java/com/hazelcast/client/cache/nearcache/ClientCacheNearCacheBasicSlowTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/cache/nearcache/ClientCacheNearCacheBasicTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/cache/nearcache/ClientCacheNearCachePreloaderSlowTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/cache/nearcache/ClientCacheNearCachePreloaderTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/AbstractClientMapTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/ClientEntryProcessorTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/ClientMapNearCacheBasicSlowTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/ClientMapNearCacheBasicTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/ClientMapNearCachePreloaderSlowTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/ClientMapNearCachePreloaderTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/ClientMapNearCacheSlowTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/ClientMapNearCacheTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/LiteMemberClientMapNearCacheBasicSlowTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/LiteMemberClientMapNearCacheBasicTest.java
  hazelcast/src/main/java/com/hazelcast/config/NearCacheConfig.java
Labels: Team: Core, Type: Enhancement

#12533 Few typos and missing javadocs
  hazelcast/src/main/java/com/hazelcast/spi/Operation.java
  hazelcast/src/main/java/com/hazelcast/util/ServiceLoader.java
  hazelcast/src/main/resources/hazelcast-config-3.10.xsd
Labels: Team: Core, Type: Cleanup

#12529 Shorten test durations
  hazelcast-client/src/test/java/com/hazelcast/client/cache/nearcache/ClientCacheNearCacheBasicTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/ClientMapNearCacheBasicTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/LiteMemberClientMapNearCacheBasicTest.java
  hazelcast/src/test/java/com/hazelcast/collection/impl/txnqueue/TransactionQueueTest.java
  hazelcast/src/test/java/com/hazelcast/map/impl/nearcache/LiteMemberMapNearCacheBasicTest.java
  hazelcast/src/test/java/com/hazelcast/map/impl/nearcache/MapNearCacheBasicTest.java
  hazelcast/src/test/java/com/hazelcast/map/impl/tx/TxnMapNearCacheBasicTest.java
  hazelcast/src/test/java/com/hazelcast/quorum/lock/LockQuorumWriteTest.java
Labels: Team: Core, Type: Enhancement

#12538 Fixed ReplicatedMap with lite members and lite member promotion
  hazelcast-spring/src/test/java/com/hazelcast/spring/context/LiteMemberTest.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapEventPublishingService.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapProxy.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapService.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapSplitBrainHandlerService.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/operation/ClearOperation.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/operation/ContainsKeyOperation.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/operation/GetOperation.java
  hazelcast/src/main/java/com/hazelcast/spi/ManagedService.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/eventservice/impl/RemoteEventProcessor.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/ProxyRegistry.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/operations/PostJoinProxyOperation.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/servicemanager/impl/ServiceManagerImpl.java
  hazelcast/src/test/java/com/hazelcast/replicatedmap/ReplicatedMapAntiEntropyTest.java
  hazelcast/src/test/java/com/hazelcast/replicatedmap/ReplicatedMapLiteMemberTest.java
  hazelcast/src/test/java/com/hazelcast/replicatedmap/ReplicatedMapLoadingTest.java
  hazelcast/src/test/java/com/hazelcast/replicatedmap/ReplicatedMapPutSerializationTest.java
  hazelcast/src/test/java/com/hazelcast/replicatedmap/ReplicatedMapReadYourWritesTest.java
  hazelcast/src/test/java/com/hazelcast/replicatedmap/impl/ReplicatedMapServiceTest.java
Labels: Team: Core, Type: Defect

#12532 Make LockMBeanTest resilient against hiccups
  hazelcast/src/test/java/com/hazelcast/internal/jmx/LockMBeanTest.java
Labels: Interface: ILock, Team: Core, Type: Test-Failure

#12497 Fixed ScheduledExecutorContainer and enhanced split-brain test
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorContainer.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledTaskResult.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/ScheduledExecutorServiceTestSupport.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/ScheduledExecutorSplitBrainTest.java
Labels: Team: Core, Type: Defect

#12543 Removed the boxing to Integer in TimedMemberStateFactoryHelper
  hazelcast/src/main/java/com/hazelcast/internal/management/TimedMemberStateFactoryHelper.java
Labels: Type: Cleanup

#12544 Fix integer overflow in PagingPredicate with large pages
  hazelcast-client/src/test/java/com/hazelcast/client/map/ClientPagingPredicateTest.java
  hazelcast/src/main/java/com/hazelcast/util/SortingUtil.java
  hazelcast/src/test/java/com/hazelcast/map/PagingPredicateTest.java
Labels: Team: Core, Type: Defect

#12545 Revert "Cleanup of ConcurrencyUtil"
  hazelcast/src/main/java/com/hazelcast/util/ConcurrencyUtil.java
  hazelcast/src/test/java/com/hazelcast/util/ConcurrencyUtilTest.java
Labels: Type: Critical, Type: Perf. Defect

#12473 Remove 3.8 rolling upgrade checks
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/DeployClassesMessageTask.java
  hazelcast/src/main/java/com/hazelcast/concurrent/lock/ObjectNamespaceSerializationHelper.java
  hazelcast/src/main/java/com/hazelcast/durableexecutor/impl/operations/PutResultOperation.java
  hazelcast/src/main/java/com/hazelcast/internal/usercodedeployment/impl/ClassData.java
  hazelcast/src/main/java/com/hazelcast/monitor/TimedMemberState.java
  hazelcast/src/main/java/com/hazelcast/monitor/impl/MemberStateImpl.java
  hazelcast/src/main/java/com/hazelcast/multimap/impl/MultiMapProxySupport.java
Labels: Team: Core, Type: Cleanup

#12438 Renaming in IOBalancer
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/iobalancer/IOBalancer.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/iobalancer/IOBalancerThread.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/iobalancer/LoadImbalance.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/iobalancer/LoadMigrationStrategy.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/iobalancer/LoadTracker.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/iobalancer/MonkeyMigrationStrategy.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/iobalancer/IOBalancerMemoryLeakTest.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/iobalancer/IOBalancerStressTest.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/iobalancer/IOBalancerTest.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/iobalancer/LoadMigrationStrategyTest.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/iobalancer/LoadTrackerTest.java
  hazelcast/src/test/java/com/hazelcast/internal/networking/nio/iobalancer/MonkeyMigrationStrategyTest.java
Labels: Team: Core, Type: Cleanup

#12466 Fixed visibility issue in split-brain recovery
  hazelcast/src/main/java/com/hazelcast/cardinality/impl/CardinalityEstimatorContainerCollector.java
  hazelcast/src/main/java/com/hazelcast/cardinality/impl/CardinalityEstimatorService.java
  hazelcast/src/main/java/com/hazelcast/collection/impl/collection/CollectionContainerCollector.java
  hazelcast/src/main/java/com/hazelcast/collection/impl/collection/CollectionService.java
  hazelcast/src/main/java/com/hazelcast/collection/impl/list/ListService.java
  hazelcast/src/main/java/com/hazelcast/collection/impl/queue/QueueContainerCollector.java
  hazelcast/src/main/java/com/hazelcast/collection/impl/queue/QueueService.java
  hazelcast/src/main/java/com/hazelcast/collection/impl/set/SetService.java
  hazelcast/src/main/java/com/hazelcast/concurrent/atomiclong/AtomicLongContainer.java
  hazelcast/src/main/java/com/hazelcast/concurrent/atomiclong/AtomicLongContainerCollector.java
  hazelcast/src/main/java/com/hazelcast/concurrent/atomiclong/AtomicLongService.java
  hazelcast/src/main/java/com/hazelcast/concurrent/atomiclong/operations/MergeOperation.java
  hazelcast/src/main/java/com/hazelcast/concurrent/atomicreference/AtomicReferenceContainer.java
  hazelcast/src/main/java/com/hazelcast/concurrent/atomicreference/AtomicReferenceContainerCollector.java
  hazelcast/src/main/java/com/hazelcast/concurrent/atomicreference/AtomicReferenceService.java
  hazelcast/src/main/java/com/hazelcast/concurrent/atomicreference/operations/MergeOperation.java
  hazelcast/src/main/java/com/hazelcast/multimap/impl/MultiMapContainer.java
  hazelcast/src/main/java/com/hazelcast/multimap/impl/MultiMapContainerCollector.java
  hazelcast/src/main/java/com/hazelcast/multimap/impl/MultiMapService.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/ArrayRingbuffer.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/Ringbuffer.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferContainer.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferContainerCollector.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferService.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/AbstractScheduledExecutorContainerHolder.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/DistributedScheduledExecutorService.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorContainerCollector.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorPartition.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/merge/AbstractContainerCollector.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/merge/AbstractContainerMerger.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/merge/AbstractMergeRunnable.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/merge/AbstractNamedContainerCollector.java
  hazelcast/src/test/java/com/hazelcast/spi/impl/merge/AbstractContainerCollectorTest.java
  hazelcast/src/test/java/com/hazelcast/spi/impl/merge/AbstractContainerMergerTest.java
  hazelcast/src/test/java/com/hazelcast/spi/impl/merge/AbstractNamedContainerCollectorTest.java
  hazelcast/src/test/java/com/hazelcast/spi/impl/merge/TestContainerCollector.java
  hazelcast/src/test/java/com/hazelcast/spi/impl/merge/TestContainerMerger.java
  hazelcast/src/test/java/com/hazelcast/spi/impl/merge/TestMergeOperation.java
  hazelcast/src/test/java/com/hazelcast/spi/impl/merge/TestNamedContainerCollector.java
Labels: Team: Core, Type: Defect

#12191 Compilation with Java 6 and above
  hazelcast/src/main/java/com/hazelcast/util/SortingUtil.java
  hazelcast/src/test/java/com/hazelcast/executor/ExecutorServiceCreateDestroyTest.java
  hazelcast/src/test/java/com/hazelcast/internal/config/ConfigValidatorTest.java
  hazelcast/src/test/java/com/hazelcast/quorum/durableexecutor/DurableExecutorQuorumWriteTest.java
  hazelcast/src/test/java/com/hazelcast/quorum/executor/ExecutorQuorumWriteTest.java
Labels: Team: Core, Type: Cleanup, Type: Enhancement

#12531 Improve logging around cluster joining
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/MembershipManager.java
  hazelcast/src/test/java/com/hazelcast/cluster/JoinStressTest.java
Labels: Team: Core, Type: Test-Failure

#12560 Fix partition assignment test by asserting cluster size before terminating nodes
  hazelcast/src/test/java/com/hazelcast/internal/partition/AbstractPartitionAssignmentsCorrectnessTest.java
  hazelcast/src/test/java/com/hazelcast/test/HazelcastTestSupport.java
Labels: Team: Core, Type: Test-Failure

#12561 Fix partition assignment test by asserting cluster size before terminating nodes
  hazelcast/src/test/java/com/hazelcast/internal/partition/AbstractPartitionAssignmentsCorrectnessTest.java
  hazelcast/src/test/java/com/hazelcast/test/HazelcastTestSupport.java
Labels: Backport, Team: Core, Type: Test-Failure

#12437 ExecuteScriptRequest/ThreadDumpRequest error reporting
  hazelcast/src/main/java/com/hazelcast/internal/management/ManagementCenterService.java
  hazelcast/src/main/java/com/hazelcast/internal/management/operation/ScriptExecutorOperation.java
  hazelcast/src/main/java/com/hazelcast/internal/management/request/ChangeWanStateRequest.java
  hazelcast/src/main/java/com/hazelcast/internal/management/request/ClearWanQueuesRequest.java
  hazelcast/src/main/java/com/hazelcast/internal/management/request/ExecuteScriptRequest.java
  hazelcast/src/main/java/com/hazelcast/internal/management/request/MapConfigRequest.java
  hazelcast/src/main/java/com/hazelcast/internal/management/request/ThreadDumpRequest.java
  hazelcast/src/test/java/com/hazelcast/internal/management/ExecuteScriptRequestTest.java
Labels: Team: Integration, Type: Enhancement

#12503 Unified ReplicatedMapSplitBrainHandlerService with IMap and ICache
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapMergeRunnable.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapSplitBrainHandlerService.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/record/AbstractBaseReplicatedRecordStore.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/record/ReplicatedRecordStore.java
  hazelcast/src/test/java/com/hazelcast/replicatedmap/impl/record/LazyIteratorTest.java
Labels: Team: Core, Type: Cleanup, Type: Defect

#12562 Ensures dynamic data structure configs can be added when proper version
  hazelcast-client/src/test/java/com/hazelcast/client/impl/ClientDynamicConfigRollingUpgradeTest.java
  hazelcast/src/main/java/com/hazelcast/config/AbstractBasicConfig.java
  hazelcast/src/main/java/com/hazelcast/config/AtomicLongConfig.java
  hazelcast/src/main/java/com/hazelcast/config/AtomicReferenceConfig.java
  hazelcast/src/main/java/com/hazelcast/config/CountDownLatchConfig.java
  hazelcast/src/main/java/com/hazelcast/config/FlakeIdGeneratorConfig.java
  hazelcast/src/main/java/com/hazelcast/config/PNCounterConfig.java
  hazelcast/src/main/java/com/hazelcast/internal/dynamicconfig/ClusterWideConfigurationService.java
  hazelcast/src/main/java/com/hazelcast/internal/dynamicconfig/DynamicConfigurationAwareConfig.java
  hazelcast/src/test/java/com/hazelcast/internal/dynamicconfig/DynamicConfigRollingUpgradeTest.java
  hazelcast/src/test/java/com/hazelcast/internal/dynamicconfig/DynamicConfigVersionTest.java
Labels: Team: Core, Type: Defect

#12563 Acquire WanReplicationService from NodeEngine while deleting cache
  hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java
Labels: Team: Core, Type: Defect

#12564 Acquire WanReplicationService from NodeEngine while deleting cache
  hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java
Labels: Backport, Team: Core, Type: Defect

#12526 RU: 3.9 - Retry mastership claim only for 3.10+
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/MembershipManager.java
Labels: Team: Core

#12576 [backport] Publish oldValue after imap#set when map has a query cache
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/querycache/ClientQueryCacheUpdateTest.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/SetOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/DefaultRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/RecordStore.java
Labels: Team: Core, Type: Defect

#12565 Test fix: Populate data from client-without-near-cache
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/LiteMemberClientMapNearCacheBasicTest.java
Labels: Team: Core

#12567 Disable invalidation configs for expiration test
  hazelcast/src/test/java/com/hazelcast/map/impl/nearcache/NearCacheTest.java
  hazelcast/src/test/java/com/hazelcast/map/impl/nearcache/NearCacheTestSupport.java
Labels: Team: Core

#12578 Move Memoizer to internal util package
  hazelcast/src/main/java/com/hazelcast/crdt/pncounter/PNCounterService.java
  hazelcast/src/main/java/com/hazelcast/internal/util/Memoizer.java
Labels: Team: Core, Type: Enhancement

#12495 Add Versioned interface since 3.9 members may still depend on it
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/ReadResultSetImpl.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/operations/ReplicationOperation.java
Labels: Team: Core, Type: Defect

#12429 Tolerate event journal reads of stale and future items
  hazelcast-client/src/main/java/com/hazelcast/client/cache/impl/ClientCacheProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientRingbufferProxy.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxy.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/journal/RingbufferCacheEventJournalImpl.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/cache/CacheEventJournalReadTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/MapEventJournalReadTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/ringbuffer/RingbufferReadManyMessageTask.java
  hazelcast/src/main/java/com/hazelcast/internal/journal/EventJournal.java
  hazelcast/src/main/java/com/hazelcast/internal/journal/EventJournalReadOperation.java
  hazelcast/src/main/java/com/hazelcast/internal/journal/EventJournalReader.java
  hazelcast/src/main/java/com/hazelcast/map/impl/journal/RingbufferMapEventJournalImpl.java
  hazelcast/src/main/java/com/hazelcast/map/impl/proxy/MapProxyImpl.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/ReadResultSet.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/Ringbuffer.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/ReadResultSetImpl.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/client/PortableReadResultSet.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/operations/ReadManyOperation.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/BinaryCompatibilityFileGenerator.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/BinaryCompatibilityNullFileGenerator.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityNullTest_1_0.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityNullTest_1_1.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityNullTest_1_2.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityNullTest_1_3.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityNullTest_1_4.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityNullTest_1_5.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityNullTest_1_6.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_1_0.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_1_1.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_1_2.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_1_3.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_1_4.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_1_5.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_1_6.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/EncodeDecodeCompatibilityNullTest.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/EncodeDecodeCompatibilityTest.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ServerCompatibilityNullTest_1_0.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ServerCompatibilityNullTest_1_1.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ServerCompatibilityNullTest_1_2.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ServerCompatibilityNullTest_1_3.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ServerCompatibilityNullTest_1_4.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ServerCompatibilityNullTest_1_5.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ServerCompatibilityNullTest_1_6.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ServerCompatibilityTest_1_0.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ServerCompatibilityTest_1_1.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ServerCompatibilityTest_1_2.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ServerCompatibilityTest_1_3.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ServerCompatibilityTest_1_4.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ServerCompatibilityTest_1_5.java
  hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ServerCompatibilityTest_1_6.java
  hazelcast/src/test/java/com/hazelcast/journal/AbstractEventJournalBasicTest.java
  hazelcast/src/test/resources/1.6.protocol.compatibility.binary
  hazelcast/src/test/resources/1.6.protocol.compatibility.null.binary
  pom.xml
Labels: Team: Core, Type: Enhancement

#12586 Reminder to dispose tasks upon RejectedExecutionException due to capacity
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorContainer.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/ScheduledExecutorServiceBasicTest.java
Labels: Estimation: S, Interface: IScheduledExecutor, Source: Internal, Team: Core, Type: Enhancement

#12579 adding the exception to the log warning in ClientCacheMetaDataFetcher
  hazelcast-client/src/main/java/com/hazelcast/client/cache/impl/nearcache/invalidation/ClientCacheMetaDataFetcher.java
Labels: Interface: ICache, Team: Core, Type: Enhancement

#12584 Do not rethrow exceptions cached in futures in ProxyRegistry.destroy()
  hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/ProxyRegistry.java
Labels: Team: Core, Type: Test-Failure

#12372 Improve logging factories creation and sharing
  hazelcast/src/main/java/com/hazelcast/logging/Logger.java
  hazelcast/src/test/java/com/hazelcast/logging/CustomLoggerFactorySingularityTest.java
  hazelcast/src/test/java/com/hazelcast/logging/LoggerTest.java
Labels: Team: Core, Type: Enhancement

#12575 adds prefix filter for RingBuffer#ReadMany operation test from clients
  hazelcast/src/test/java/com/hazelcast/client/test/IdentifiedFactory.java
  hazelcast/src/test/java/com/hazelcast/client/test/PrefixFilter.java
Labels: Team: Client

#12592 Shutdown all services if Node creation fails
  hazelcast/src/main/java/com/hazelcast/instance/Node.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/NodeEngineImpl.java
  hazelcast/src/test/java/com/hazelcast/instance/NodeThreadLeakTest.java
Labels: Team: Core, Type: Defect

#12593 Throw CacheNotExistsException when cache config does not exist
  hazelcast/src/main/java/com/hazelcast/cache/impl/journal/RingbufferCacheEventJournalImpl.java
Labels: Team: Core, Type: Defect

#12607 PartitionReplicaSyncResponse should be TargetAware
  hazelcast/src/main/java/com/hazelcast/internal/partition/operation/PartitionReplicaSyncRequest.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/operation/PartitionReplicaSyncResponse.java
Labels: Team: Core, Type: Defect

#12577 Respect index config in query caches
  hazelcast/src/main/java/com/hazelcast/map/QueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/AbstractInternalQueryCache.java
  hazelcast/src/test/java/com/hazelcast/map/impl/querycache/subscriber/QueryCacheIndexConfigTest.java
Labels: Team: Core, Type: Defect

#12601 Have MockJoiner consult the set targetAddress when picking join address
  hazelcast/src/test/java/com/hazelcast/test/SplitBrainTestSupport.java
  hazelcast/src/test/java/com/hazelcast/test/mocknetwork/MockJoiner.java
Labels: Team: Core, Type: Defect

#12594 Added test HazelcastInstance factory classes which add protection against unintended joins
  hazelcast-client/src/test/java/com/hazelcast/client/test/TestAwareClientFactory.java
  hazelcast/src/test/java/com/hazelcast/test/TestAwareInstanceFactory.java
Labels: Team: Core, Type: Enhancement

#12608 FinalizeJoinOp should return response when sent via invocation
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterJoinManager.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/operations/FinalizeJoinOp.java
  hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/OperationServiceImpl_BasicTest.java
Labels: Team: Core, Type: Defect

#12604 Assert index eventually has some data in MapIndexLifecycleTest
  hazelcast/src/test/java/com/hazelcast/map/MapIndexLifecycleTest.java
Labels: Team: Core, Type: Test-Failure

#12580 [BACKPORT] Respect index config in query caches
  hazelcast/src/main/java/com/hazelcast/map/QueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/AbstractInternalQueryCache.java
  hazelcast/src/test/java/com/hazelcast/map/impl/querycache/subscriber/QueryCacheIndexConfigTest.java
Labels: Backport, Team: Core, Type: Defect

#12542 Fix ManagementCenterService shutting down if MC is enabled on JDK 9
  hazelcast/src/main/java/com/hazelcast/internal/management/TimedMemberStateFactoryHelper.java
  hazelcast/src/test/java/com/hazelcast/internal/management/ZuluExcludeRule.java
Labels: Team: Core, Team: Integration, Type: Defect, Type: Test-Failure

#12591 Do not mutate ReplicatedMapConfig while constructing read-only variant
  hazelcast/src/main/java/com/hazelcast/config/ReplicatedMapConfig.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapService.java
  hazelcast/src/test/java/com/hazelcast/internal/dynamicconfig/DynamicConfigTest.java
Labels: Interface: ReplicatedMap, Team: Core, Type: Defect

#12610 Fix possible NPE while creating logging factories
  hazelcast/src/main/java/com/hazelcast/logging/Logger.java
Labels: Team: Core, Type: Defect

#12613 Ensure migrations are completed before running assertions
  hazelcast/src/test/java/com/hazelcast/map/MapIndexLifecycleTest.java
Labels: Team: Core, Type: Test-Failure

#12620 [FORWARD PORT] Do not mutate ReplicatedMapConfig while constructing read-only variant
  hazelcast/src/main/java/com/hazelcast/config/ReplicatedMapConfig.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapService.java
  hazelcast/src/test/java/com/hazelcast/internal/dynamicconfig/DynamicConfigTest.java
Labels: Interface: ReplicatedMap, Team: Core, Type: Defect

#12540 Create proxies of a client on cluster back when cluster restarted
  hazelcast-client/src/main/java/com/hazelcast/client/impl/HazelcastClientInstanceImpl.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/ProxyManager.java
  hazelcast-client/src/test/java/com/hazelcast/client/proxy/DistributedObjectListenerTest.java
Labels: Backport, Team: Client, Type: Defect

#12618 Fix ManagementCenterService shutting down if MC is enabled on JDK 9
  hazelcast/src/main/java/com/hazelcast/internal/management/TimedMemberStateFactoryHelper.java
  hazelcast/src/test/java/com/hazelcast/internal/management/ZuluExcludeRule.java
Labels: Team: Core, Team: Integration, Type: Defect, Type: Test-Failure

#12612 Added ID count to flake ID generators statistics
  hazelcast/src/main/java/com/hazelcast/flakeidgen/impl/FlakeIdGeneratorProxy.java
  hazelcast/src/main/java/com/hazelcast/flakeidgen/impl/FlakeIdGeneratorService.java
  hazelcast/src/main/java/com/hazelcast/monitor/LocalFlakeIdGeneratorStats.java
  hazelcast/src/main/java/com/hazelcast/monitor/impl/LocalFlakeIdGeneratorStatsImpl.java
  hazelcast/src/test/java/com/hazelcast/flakeidgen/impl/FlakeIdGenerator_MemberIntegrationTest.java
Labels: Interface: FlakeIDGenerator, Team: Core, Team: Integration, Type: Enhancement

#12622 Add null checks for add listener methods of data structures
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientListProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientMultiMapProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientQueueProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientReliableTopicProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientReplicatedMapProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientSetProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientTopicProxy.java
  hazelcast-client/src/test/java/com/hazelcast/client/listeners/ClientAddListenerWithNullParameterTests.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapProxy.java
  hazelcast/src/test/java/com/hazelcast/listeners/AddListenerWithNullParameterTests.java
Labels: Team: Client, Team: Core, Type: Defect

#12621 Add null checks for add listener methods of data structures
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientListProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientMultiMapProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientQueueProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientReliableTopicProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientReplicatedMapProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientSetProxy.java
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientTopicProxy.java
  hazelcast-client/src/test/java/com/hazelcast/client/listeners/ClientAddListenerWithNullParameterTests.java
  hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapProxy.java
  hazelcast/src/test/java/com/hazelcast/listeners/AddListenerWithNullParameterTests.java
Labels: Backport, Team: Client, Team: Core, Type: Defect

#12569 Remove WAN event list from EP operations
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/AbstractMultipleEntryBackupOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/EntryOperator.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/MultipleEntryBackupOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/MultipleEntryOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/PartitionWideEntryBackupOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/PartitionWideEntryOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/PartitionWideEntryWithPredicateOperation.java
Labels: Module: WAN, Team: Core, Type: Enhancement

#12603 Increase connection-attempt-limit for ClientQueryCacheBasicTest
  hazelcast-client/src/test/java/com/hazelcast/client/map/impl/querycache/ClientQueryCacheBasicTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/txn/ClientTxnMapTest.java
  hazelcast-client/src/test/java/com/hazelcast/client/txn/serialization/TxnMapDeserializationTest.java
Labels: Interface: IMap, Team: Client, Type: Test-Failure

#12628 Add support for -beta-x suffix when parsing hazelcast version (#12365)
  hazelcast/src/main/java/com/hazelcast/util/StringUtil.java
  hazelcast/src/test/java/com/hazelcast/instance/BuildInfoProviderTest.java
  hazelcast/src/test/java/com/hazelcast/util/StringUtilTest.java
  hazelcast/src/test/java/com/hazelcast/version/MemberVersionTest.java
Labels: Team: Core, Type: Enhancement

#12629 [BACKPORT] Add support for -beta-x suffix when parsing hazelcast version (#12365)
  hazelcast/src/main/java/com/hazelcast/util/StringUtil.java
  hazelcast/src/test/java/com/hazelcast/instance/BuildInfoProviderTest.java
  hazelcast/src/test/java/com/hazelcast/util/StringUtilTest.java
  hazelcast/src/test/java/com/hazelcast/version/MemberVersionTest.java
Labels: Backport, Team: Core, Type: Enhancement

#12609 Handle CLEAR_ALL and EVICT_ALL events for query cache
  hazelcast-client/src/main/java/com/hazelcast/client/impl/querycache/ClientQueryCacheContext.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/NodeQueryCacheContext.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/QueryCacheContext.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/AbstractInternalQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/DefaultQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/InternalQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/NullQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/SubscriberAccumulatorHandler.java
  hazelcast/src/test/java/com/hazelcast/map/impl/querycache/QueryCacheWithMapWideEventsTest.java
  hazelcast/src/test/java/com/hazelcast/mapreduce/helpers/Employee.java
Labels: Team: Core, Type: Defect

#12634 [backport] Handle CLEAR_ALL and EVICT_ALL events for query cache
  hazelcast-client/src/main/java/com/hazelcast/client/impl/querycache/ClientQueryCacheContext.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/NodeQueryCacheContext.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/QueryCacheContext.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/AbstractInternalQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/DefaultQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/InternalQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/NullQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/SubscriberAccumulatorHandler.java
  hazelcast/src/test/java/com/hazelcast/map/impl/querycache/QueryCacheWithMapWideEventsTest.java
  hazelcast/src/test/java/com/hazelcast/mapreduce/helpers/Employee.java
Labels: Team: Core, Type: Defect

#12605 Fixes LoggingScheduledExecutor removeOnCancel problems
  hazelcast/src/main/java/com/hazelcast/spi/properties/GroupProperty.java
  hazelcast/src/main/java/com/hazelcast/util/executor/LoggingScheduledExecutor.java
  hazelcast/src/test/java/com/hazelcast/test/HazelcastTestSupport.java
  hazelcast/src/test/java/com/hazelcast/util/executor/LoggingScheduledExecutorTest.java
Labels: Priority: High, Team: QuSP, Type: Perf. Defect

#12581 Fix behaviour when addressProvider.loadAddress throws excepion
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java
  hazelcast-client/src/test/java/com/hazelcast/client/spi/impl/discovery/ClientDiscoverySpiTest.java
Labels: Team: Client, Type: Defect

#12582 Fix behaviour when addressProvider.loadAddress throws excepion
  hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java
  hazelcast-client/src/test/java/com/hazelcast/client/spi/impl/discovery/ClientDiscoverySpiTest.java
Labels: Backport, Team: Client, Type: Defect

#12641 Fixes version comparisons in conditional serialization
  hazelcast/src/main/java/com/hazelcast/cardinality/impl/hyperloglog/impl/SparseHyperLogLogEncoder.java
  hazelcast/src/main/java/com/hazelcast/config/ReplicatedMapConfig.java
  hazelcast/src/main/java/com/hazelcast/map/impl/proxy/MapProxyImpl.java
  hazelcast/src/test/java/com/hazelcast/mapreduce/helpers/Employee.java
Labels: Module: Rolling Upgrade, Team: Core, Type: Defect

#12638 Fixed FindBugs issue in AbstractMultipleEntryBackupOperation
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/AbstractMultipleEntryBackupOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/PartitionWideEntryBackupOperation.java
Labels: Team: Core, Type: Defect

#12635 Cleanup query cache code
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/accumulator/AccumulatorScannerTask.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/accumulator/BasicAccumulator.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/event/BatchEventData.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/event/BatchIMapEvent.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/publisher/MapListenerRegistry.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/publisher/MapPublisherRegistry.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/publisher/PublisherRegistry.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/AbstractQueryCacheEndToEndConstructor.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/DefaultQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/DefaultQueryCacheRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/EvictionOperator.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/InternalQueryCacheListenerAdapter.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/MapSubscriberRegistry.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/QueryCacheRecordHashMap.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/SubscriberAccumulator.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/SubscriberAccumulatorHandler.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/record/AbstractQueryCacheRecord.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/record/DataQueryCacheRecord.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/record/DataQueryCacheRecordFactory.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/record/ObjectQueryCacheRecord.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/record/ObjectQueryCacheRecordFactory.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/record/QueryCacheRecord.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/record/QueryCacheRecordFactory.java
  hazelcast/src/test/java/com/hazelcast/map/impl/querycache/AbstractQueryCacheTestSupport.java
  hazelcast/src/test/java/com/hazelcast/map/impl/querycache/QueryCacheListenerTest.java
  hazelcast/src/test/java/com/hazelcast/map/impl/querycache/QueryCacheMethodsWithPredicateTest.java
  hazelcast/src/test/java/com/hazelcast/map/impl/querycache/QueryCacheTest.java
Labels: Team: Core, Type: Defect

#12643 Minor layout improvement NioOutboundPipeline
  hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioOutboundPipeline.java
Labels: Type: Cleanup

#12640 Serialize WAN event collection size on unknown and 3.9 cluster version
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/AbstractMultipleEntryBackupOperation.java
Labels: Interface: IMap, Team: Core, Type: Defect

#12644 Suppress findbugs warning about broad catch
  hazelcast/src/main/java/com/hazelcast/util/executor/LoggingScheduledExecutor.java
Labels: Team: Core

#12647 Drop heartbeat messages before suspicion to correctly split cluster
  hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/MembershipFailureTest.java
Labels: Team: Core, Type: Test-Failure

#12648 Drop heartbeat messages before suspicion to correctly split cluster
  hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/MembershipFailureTest.java
Labels: Backport, Team: Core, Type: Test-Failure

#12616 Remove option to return PortableReadResultSet from ReadManyOp as unused
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/client/PortableReadResultSet.java
  hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/operations/ReadManyOperation.java
  hazelcast/src/test/java/com/hazelcast/ringbuffer/impl/operations/ReadManyOperationTest.java
Labels: Team: Core, Type: Defect

#12627 Fixed merge policy check in ConfigValidator
  hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractHazelcastCacheManager.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxyUtil.java
  hazelcast/src/main/java/com/hazelcast/cache/impl/CacheSplitBrainHandlerService.java
  hazelcast/src/main/java/com/hazelcast/internal/config/ConfigValidator.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapRemoteService.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/merge/AbstractMergeRunnable.java
  hazelcast/src/test/java/com/hazelcast/internal/config/ConfigValidatorTest.java
Labels: Team: Core, Type: Defect

#12595 [FORWARD PORT] ExecuteScriptRequest/ThreadDumpRequest error reporting
  hazelcast/src/main/java/com/hazelcast/internal/management/ManagementCenterService.java
  hazelcast/src/main/java/com/hazelcast/internal/management/operation/ScriptExecutorOperation.java
  hazelcast/src/main/java/com/hazelcast/internal/management/request/ChangeWanStateRequest.java
  hazelcast/src/main/java/com/hazelcast/internal/management/request/ClearWanQueuesRequest.java
  hazelcast/src/main/java/com/hazelcast/internal/management/request/ExecuteScriptRequest.java
  hazelcast/src/main/java/com/hazelcast/internal/management/request/MapConfigRequest.java
  hazelcast/src/main/java/com/hazelcast/internal/management/request/ThreadDumpRequest.java
  hazelcast/src/test/java/com/hazelcast/internal/management/ExecuteScriptRequestTest.java
Labels: Team: Integration, Type: Enhancement

#12650 Fix testAsyncConnectionCreationInAsyncMethods
  hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java
Labels: Team: Client, Type: Defect

#12649 Fix testAsyncConnectionCreationInAsyncMethods
  hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java
Labels: Backport, Team: Client, Type: Defect

#12658 Cleanup of ConfigValidator tests
  hazelcast/src/test/java/com/hazelcast/internal/config/ConfigValidatorEvictionConfigTest.java
  hazelcast/src/test/java/com/hazelcast/internal/config/ConfigValidatorNearCacheConfigTest.java
  hazelcast/src/test/java/com/hazelcast/internal/config/ConfigValidatorTest.java
Labels: Team: Core, Type: Cleanup

#12665 [backport] Fixed NPE when QueryCache#getAll
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/accumulator/AccumulatorScannerTask.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/accumulator/BasicAccumulator.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/event/BatchEventData.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/event/BatchIMapEvent.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/publisher/MapListenerRegistry.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/publisher/MapPublisherRegistry.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/publisher/PublisherRegistry.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/AbstractQueryCacheEndToEndConstructor.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/DefaultQueryCache.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/DefaultQueryCacheRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/EvictionOperator.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/InternalQueryCacheListenerAdapter.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/MapSubscriberRegistry.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/QueryCacheRecordHashMap.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/SubscriberAccumulator.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/SubscriberAccumulatorHandler.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/record/AbstractQueryCacheRecord.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/record/DataQueryCacheRecord.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/record/DataQueryCacheRecordFactory.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/record/ObjectQueryCacheRecord.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/record/ObjectQueryCacheRecordFactory.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/record/QueryCacheRecord.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/record/QueryCacheRecordFactory.java
  hazelcast/src/test/java/com/hazelcast/map/impl/querycache/AbstractQueryCacheTestSupport.java
  hazelcast/src/test/java/com/hazelcast/map/impl/querycache/QueryCacheListenerTest.java
  hazelcast/src/test/java/com/hazelcast/map/impl/querycache/QueryCacheMethodsWithPredicateTest.java
  hazelcast/src/test/java/com/hazelcast/map/impl/querycache/QueryCacheTest.java
Labels: Team: Core, Type: Defect

#12645 Time sesitive ClientStateListeners are refactored
  hazelcast-client/src/test/java/com/hazelcast/client/util/ClientStateListenerTest.java
Labels: Team: Client, Type: Test-Failure

#12646 Time sesitive ClientStateListeners are refactored
  hazelcast-client/src/test/java/com/hazelcast/client/util/ClientStateListenerTest.java
Labels: Backport, Team: Client, Type: Test-Failure

#12654 Fix ClientReconnectTest sensitive timing problems
  hazelcast-client/src/test/java/com/hazelcast/client/ClientReconnectTest.java
Labels: Team: Client, Type: Test-Failure

#12653 Fix ClientReconnectTest sensitive timing problems
  hazelcast-client/src/test/java/com/hazelcast/client/ClientReconnectTest.java
Labels: Backport, Team: Client, Type: Test-Failure

#12666 Adds explicit serialVersionUID to test domain class Employee
  hazelcast/src/test/java/com/hazelcast/mapreduce/helpers/Employee.java
Labels: Team: Core, Type: Test-Failure

#7859 Semaphore additions and changes
  hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientSemaphoreProxy.java
  hazelcast-client/src/test/java/com/hazelcast/client/semaphore/ClientSemaphoreTest.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/DefaultMessageTaskFactoryProvider.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/semaphore/SemaphoreIncreasePermitsMessageTask.java
  hazelcast/src/main/java/com/hazelcast/concurrent/semaphore/SemaphoreContainer.java
  hazelcast/src/main/java/com/hazelcast/concurrent/semaphore/SemaphoreDataSerializerHook.java
  hazelcast/src/main/java/com/hazelcast/concurrent/semaphore/SemaphoreProxy.java
  hazelcast/src/main/java/com/hazelcast/concurrent/semaphore/operations/IncreaseBackupOperation.java
  hazelcast/src/main/java/com/hazelcast/concurrent/semaphore/operations/IncreaseOperation.java
  hazelcast/src/main/java/com/hazelcast/core/ISemaphore.java
  hazelcast/src/main/java/com/hazelcast/internal/jmx/SemaphoreMBean.java
  hazelcast/src/test/java/com/hazelcast/concurrent/semaphore/SemaphoreBasicTest.java
  hazelcast/src/test/java/com/hazelcast/quorum/QuorumOperationTest.java
  hazelcast/src/test/java/com/hazelcast/quorum/semaphore/SemaphoreQuorumWriteTest.java
Labels: Interface: ISemaphore, Team: Core, Type: Enhancement

#12651 Fix IOUtil.compress() - was infinitely looping with len < 10 inputs
  hazelcast/src/main/java/com/hazelcast/nio/IOUtil.java
  hazelcast/src/test/java/com/hazelcast/nio/IOUtilTest.java
Labels: Type: Defect

#12652 Fix IOUtil.compress() - was infinitely looping with len < 10 inputs
  hazelcast/src/main/java/com/hazelcast/nio/IOUtil.java
  hazelcast/src/test/java/com/hazelcast/nio/IOUtilTest.java
Labels: Backport, Type: Defect

#12671 Fixing time sensitive tests in ClientMapTest
  hazelcast-client/src/test/java/com/hazelcast/client/map/ClientMapTest.java
Labels: Team: Client, Type: Test-Failure

#12672 Fixing time sensitive tests in ClientMapTest
  hazelcast-client/src/test/java/com/hazelcast/client/map/ClientMapTest.java
Labels: Backport, Team: Client, Type: Test-Failure

#12669 Increase connection-attempt-limit for ClientToMemberDiscoveryTest
  hazelcast/src/test/resources/hazelcast-client-multicast-plugin.xml
Labels: Backport, Team: Client, Type: Test-Failure

#12664 Publish end-of-sequence event upon start of migration
  hazelcast/src/main/java/com/hazelcast/map/impl/MapMigrationAwareService.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/EventPublisherHelper.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/SubscriberAccumulatorHandler.java
  hazelcast/src/test/java/com/hazelcast/map/impl/querycache/QueryCacheMapWideEventsTest.java
Labels: Team: Core, Type: Defect

#11817 fix typo in ClientNetworkConfig javadoc
  hazelcast-client/src/main/java/com/hazelcast/client/config/ClientNetworkConfig.java
Labels: Team: Core, Team: Documentation, Type: Enhancement

#12511 Allow loss-tolerant reliable topic listener to tolerate ringbuffer loss
  hazelcast/src/main/java/com/hazelcast/topic/impl/reliable/ReliableMessageListenerRunner.java
  hazelcast/src/test/java/com/hazelcast/topic/impl/reliable/LossToleranceTest.java
  hazelcast/src/test/java/com/hazelcast/topic/impl/reliable/ReliableMessageListenerMock.java
Labels: Team: Core, Type: Enhancement

#12667 [backport] Publish end-of-sequence event upon start of migration
  hazelcast/src/main/java/com/hazelcast/map/impl/MapMigrationAwareService.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/EventPublisherHelper.java
  hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/SubscriberAccumulatorHandler.java
  hazelcast/src/test/java/com/hazelcast/map/impl/querycache/QueryCacheMapWideEventsTest.java
Labels: Backport, Team: Core, Type: Defect

#12475 Remove 3.8 rolling upgrade checks for IMap
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/AbstractMapQueryMessageTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/MapFetchWithQueryMessageTask.java
  hazelcast/src/main/java/com/hazelcast/map/impl/eviction/ExpirationManager.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/EvictBatchBackupOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/proxy/MapProxyImpl.java
  hazelcast/src/main/java/com/hazelcast/map/impl/query/QueryDispatcher.java
Labels: Team: Core, Type: Cleanup

#12659 Define MAX_JOIN_SECONDS on master config only to prevent join failures
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/MembershipManager.java
  hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/MembershipUpdateTest.java
Labels: Type: Test-Failure

#12660 Define MAX_JOIN_SECONDS on master config only to prevent join failures
  hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/MembershipUpdateTest.java
Labels: Backport, Type: Test-Failure

#12688 Introduces test to validate usage of isLessThan in Versioned classes
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/PostJoinMapOperation.java
  hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/VersionedInCurrentVersionTest.java
Labels: Team: Core

#12693 Fix CustomLoggerFactorySingularityTest
  hazelcast/src/test/java/com/hazelcast/logging/CustomLoggerFactorySingularityTest.java
Labels: Team: Core, Type: Test-Failure

#12695 Fixed NodeThreadLeakTest
  hazelcast/src/main/java/com/hazelcast/spi/impl/NodeEngineImpl.java
  hazelcast/src/test/java/classloading/ThreadLeakTestUtils.java
  hazelcast/src/test/java/com/hazelcast/instance/NodeThreadLeakTest.java
Labels: Team: Core, Type: Test-Failure

#12682 Cleanup on TimedMemberState
  hazelcast/src/main/java/com/hazelcast/internal/management/TimedMemberStateFactory.java
  hazelcast/src/main/java/com/hazelcast/monitor/TimedMemberState.java
  hazelcast/src/test/java/com/hazelcast/monitor/TimedMemberStateIntegrationTest.java
  hazelcast/src/test/java/com/hazelcast/monitor/TimedMemberStateTest.java
Labels: Type: Cleanup

#12187 Extend test coverage for Offloadables - make sure the heartbeats are coming during the offload
  hazelcast/src/test/java/com/hazelcast/map/EntryProcessorOffloadableTest.java
Labels: Team: Core, Type: Enhancement

#12535 Implement idempotent retries for migration operations
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/InternalPartitionServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/MigrationManager.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/PartitionReplicaStateChecker.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/PartitionServiceState.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/PartitionStateManager.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/operation/PromotionCommitOperation.java
  hazelcast/src/test/java/com/hazelcast/internal/partition/MigrationInvocationsSafetyTest.java
Labels: Team: Core, Type: Defect

#12536 Implement idempotent retries for migration operations
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/InternalPartitionServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/MigrationManager.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/PartitionReplicaStateChecker.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/PartitionServiceState.java
  hazelcast/src/main/java/com/hazelcast/internal/partition/impl/PartitionStateManager.java
  hazelcast/src/test/java/com/hazelcast/internal/partition/MigrationInvocationsSafetyTest.java
Labels: Backport, Team: Core, Type: Defect

#12685 Fix Invocation_NetworkSplitTest
  hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/Invocation_NetworkSplitTest.java
Labels: Team: Core, Type: Test-Failure

#12636 Client lock operations should use StringPartitioningStrategy
  hazelcast-client/src/test/java/com/hazelcast/client/lock/ClientLockTest.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/lock/LockForceUnlockMessageTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/lock/LockGetLockCountMessageTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/lock/LockGetRemainingLeaseTimeMessageTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/lock/LockIsLockedByCurrentThreadMessageTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/lock/LockIsLockedMessageTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/lock/LockLockMessageTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/lock/LockTryLockMessageTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/lock/LockUnlockMessageTask.java
  hazelcast/src/test/java/com/hazelcast/concurrent/lock/LockAdvancedTest.java
Labels: Interface: ILock, Team: Client, Type: Defect

#12637 Client lock operations should use StringPartitioningStrategy
  hazelcast-client/src/test/java/com/hazelcast/client/lock/ClientLockTest.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/lock/LockForceUnlockMessageTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/lock/LockGetLockCountMessageTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/lock/LockGetRemainingLeaseTimeMessageTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/lock/LockIsLockedByCurrentThreadMessageTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/lock/LockIsLockedMessageTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/lock/LockLockMessageTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/lock/LockTryLockMessageTask.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/lock/LockUnlockMessageTask.java
  hazelcast/src/test/java/com/hazelcast/concurrent/lock/LockAdvancedTest.java
Labels: Backport, Interface: ILock, Team: Client, Type: Defect

#12702 Fix ICondition timing issue
  hazelcast/src/test/java/com/hazelcast/concurrent/lock/ConditionAbstractTest.java
Labels: Type: Test-Failure

#12703 Fix ICondition timing issue
  hazelcast/src/test/java/com/hazelcast/concurrent/lock/ConditionAbstractTest.java
Labels: Backport, Type: Test-Failure

#12539 Create proxies of a client on cluster back when cluster restarted
  hazelcast-client/src/main/java/com/hazelcast/client/impl/HazelcastClientInstanceImpl.java
  hazelcast-client/src/main/java/com/hazelcast/client/spi/ProxyManager.java
  hazelcast-client/src/test/java/com/hazelcast/client/proxy/DistributedObjectListenerTest.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/DefaultMessageTaskFactoryProvider.java
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/CreateProxiesMessageTask.java
  pom.xml
Labels: Team: Client, Type: Defect

#12701 Minor cleanup Node
  hazelcast/src/main/java/com/hazelcast/instance/Node.java
Labels: Type: Cleanup
