Repository hazelcast/hazelcast, pull requests merged in 2021-12, with the labels that each got.

#20002 Fix name of CLI commands in help text [5.0.z]
  distribution/src/bin-filemode-755/hz-start
  hazelcast/src/main/java/com/hazelcast/client/console/HazelcastCommandLine.java
Labels: Type: Defect, Team: Core, Source: Internal, Add to Release Notes, Module: CLI

#19998 Update avro to 1.11.0
  pom.xml
Labels: Type: Enhancement, Team: Core, Source: Internal, Module: Jet

#20000 Fix flaky Log4jLoggerTest
  hazelcast/src/test/java/com/hazelcast/logging/AbstractLoggerTest.java
Labels: Team: Core, Type: Test-Failure, Source: Internal

#20001 Fix name of CLI commands in help text
  distribution/src/bin-filemode-755/hz-start
  hazelcast/src/main/java/com/hazelcast/client/console/HazelcastCommandLine.java
Labels: Type: Defect, Team: Core, Source: Internal, Add to Release Notes, Module: CLI

#19914 Make kinesis source generic
  extensions/kinesis/src/main/java/com/hazelcast/jet/kinesis/KinesisSources.java
  extensions/kinesis/src/main/java/com/hazelcast/jet/kinesis/impl/source/KinesisSourceP.java
  extensions/kinesis/src/main/java/com/hazelcast/jet/kinesis/impl/source/KinesisSourcePMetaSupplier.java
  extensions/kinesis/src/main/java/com/hazelcast/jet/kinesis/impl/source/KinesisSourcePSupplier.java
  extensions/kinesis/src/test/java/com/hazelcast/jet/kinesis/AbstractKinesisTest.java
  extensions/kinesis/src/test/java/com/hazelcast/jet/kinesis/KinesisIntegrationTest.java
Labels: Source: Community

#20010 Collect incoming queues metrics before draining queue into Inbox [5.0.z]
  hazelcast/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTasklet.java
Labels: Type: Defect, Team: Core, Source: Internal, Module: Jet

#19377 Collect incoming queues metrics before draining queue into Inbox
  hazelcast/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTasklet.java
Labels: Type: Defect, Team: Core, Source: Internal, Module: Jet

#20007 Update avro to 1.11.0 [5.0.z]
  pom.xml
Labels: Team: Core, Source: Internal, Add to Release Notes, dependencies, Module: Jet

#20008 Update aws-sdk to 1.12.120 [5.0.z]
  pom.xml
Labels: Type: Enhancement, Team: Core, Source: Internal, Add to Release Notes, dependencies, Module: Jet

#19999 Update aws-sdk to 1.12.120
  pom.xml
Labels: Type: Enhancement, Team: Core, Source: Internal, Module: Jet

#20013 Fix logging configuration in hz-start.bat [5.0.z]
  distribution/src/bin-regular/hz-start.bat
Labels: Type: Defect, Team: Core, Backport, Source: Internal, Module: Scripts

#20012 Fix logging configuration in hz-start.bat
  distribution/src/bin-regular/hz-start.bat
Labels: Type: Defect, Team: Core, Source: Internal, Module: Scripts

#20003 Use hazelcast.yaml when hazelcast.xml is not available
  distribution/src/bin-filemode-755/hz-start
  distribution/src/bin-regular/hz-start.bat
Labels: Type: Enhancement, Team: Core, Source: Internal, Add to Release Notes, Module: Scripts

#20004 Use hazelcast.yaml when hazelcast.xml is not available [5.0.z]
  distribution/src/bin-filemode-755/hz-cli
  distribution/src/bin-filemode-755/hz-start
  distribution/src/bin-regular/hz-start.bat
Labels: Type: Enhancement, Team: Core, Source: Internal, Add to Release Notes, Module: Scripts

#19995 Fix issue with UNKNOWN type in joins
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/types/HazelcastTypeFactory.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/map/SqlJoinTest.java
Labels: Type: Defect, Source: Internal, Team: SQL

#20020 Use default value for OWASP failBuildOnCVSS
  pom.xml
Labels: Team: Core, Source: Internal

#19991 MC-1039 - disable data access for MC
  hazelcast-spring-tests/src/test/java/com/hazelcast/spring/TestFullApplicationContext.java
  hazelcast-spring-tests/src/test/resources/com/hazelcast/spring/fullConfig-applicationContext-hazelcast.xml
  hazelcast-spring/src/main/resources/hazelcast-spring-5.1.xsd
  hazelcast/src/main/java/com/hazelcast/config/ConfigXmlGenerator.java
  hazelcast/src/main/java/com/hazelcast/config/ManagementCenterConfig.java
  hazelcast/src/main/java/com/hazelcast/internal/config/MemberDomConfigProcessor.java
  hazelcast/src/main/java/com/hazelcast/internal/management/TimedMemberState.java
  hazelcast/src/main/java/com/hazelcast/internal/management/TimedMemberStateFactory.java
  hazelcast/src/main/resources/hazelcast-config-5.1.json
  hazelcast/src/main/resources/hazelcast-config-5.1.xsd
  hazelcast/src/main/resources/hazelcast-full-example.xml
  hazelcast/src/main/resources/hazelcast-full-example.yaml
  hazelcast/src/main/resources/hazelcast-security-hardened.xml
  hazelcast/src/main/resources/hazelcast-security-hardened.yaml
  hazelcast/src/test/java/com/hazelcast/config/ConfigCompatibilityChecker.java
  hazelcast/src/test/java/com/hazelcast/config/ConfigXmlGeneratorTest.java
  hazelcast/src/test/java/com/hazelcast/config/ManagementCenterConfigTest.java
  hazelcast/src/test/java/com/hazelcast/config/XMLConfigBuilderTest.java
  hazelcast/src/test/java/com/hazelcast/config/YamlConfigBuilderTest.java
  hazelcast/src/test/java/com/hazelcast/internal/management/TimedMemberStateTest.java
  hazelcast/src/test/resources/com/hazelcast/config/yaml/testcases/member/management-center/multiple-failures.json
  hazelcast/src/test/resources/com/hazelcast/config/yaml/testcases/member/management-center/success.json
  hazelcast/src/test/resources/hazelcast-fullconfig-without-network.xml
  hazelcast/src/test/resources/hazelcast-fullconfig-without-network.yaml
Labels: Type: Enhancement, Source: Internal, Module: Config, Team: Management Center, Add to Release Notes

#20026 Update json-smart to 2.4.7
  pom.xml
Labels: Type: Critical, Team: Core, Source: Internal, Not Release Notes content, dependencies

#20027 Update json-smart to 2.4.7 [5.0.z]
  pom.xml
Labels: Type: Critical, Team: Core, Source: Internal, Not Release Notes content, dependencies

#20028 Update json-smart to 2.4.7 [5.0.1]
  pom.xml
Labels: Type: Critical, Team: Core, Source: Internal, Not Release Notes content, dependencies

#20015 [BACKPORT 5.0.z] [HZ-384] Generate the attribution files during the build (#19927)
  distribution/src/assembly/assembly-descriptor-slim.xml
  distribution/src/assembly/assembly-descriptor.xml
  pom.xml
Labels: Type: Enhancement, Team: Core, Backport, Source: Internal, Module: Scripts

#20030 Use default value for OWASP failBuildOnCVSS
  pom.xml
Labels: Team: Core, Source: Internal

#20031 Use default value for OWASP failBuildOnCVSS
  pom.xml
Labels: Team: Core, Source: Internal

#20029 CacheConfigHolder fields should be final
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/holder/CacheConfigHolder.java
Labels: Type: Defect, Team: Core, Source: Internal, Module: ICache

#19686 Fix 19622 runnable autodisposable tasks
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceProxy.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledRunnableAdapter.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceBasicTest.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceTestSupport.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/impl/TaskUtilsTest.java
Labels: Type: Defect, Team: Core, Source: Community, Module: IScheduledExecutor

#20046 Prerequisites for tiered store record
  hazelcast/src/main/java/com/hazelcast/map/impl/record/DataRecordFactory.java
  hazelcast/src/main/java/com/hazelcast/map/impl/record/ObjectRecordFactory.java
  hazelcast/src/main/java/com/hazelcast/map/impl/record/RecordFactory.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/AbstractRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/DefaultRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/RecordStore.java
  hazelcast/src/test/java/com/hazelcast/map/impl/record/AbstractRecordFactoryTest.java
  hazelcast/src/test/java/com/hazelcast/map/impl/recordstore/LazyEvictableEntryViewTest.java
  hazelcast/src/test/java/com/hazelcast/query/impl/IndexTest.java
Labels: Type: Enhancement, Priority: High, Estimation: S, Module: Persistence, Team: Storage

#19689 [BACKPORT] Fix 19622 runnable autodisposable tasks 5.0.z
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceProxy.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledRunnableAdapter.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceBasicTest.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceTestSupport.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/impl/TaskUtilsTest.java
Labels: Type: Defect, Team: Core, Backport, Source: Community, Module: IScheduledExecutor

#19688 [BACKPORT] Fix 19622 runnable autodisposable tasks 4.2.z
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceProxy.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledRunnableAdapter.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceBasicTest.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceTestSupport.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/impl/TaskUtilsTest.java
Labels: Type: Defect, Team: Core, Backport, Source: Community, Module: IScheduledExecutor

#19687 [BACKPORT] Fix 19622 runnable autodisposable tasks 4.1.z
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceProxy.java
  hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledRunnableAdapter.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceBasicTest.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceTestSupport.java
  hazelcast/src/test/java/com/hazelcast/scheduledexecutor/impl/TaskUtilsTest.java
Labels: Type: Defect, Team: Core, Backport, Source: Community, Module: IScheduledExecutor

#20017 Add client API for mappingDdl, add test
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/parse/SqlCreateMapping.java
  hazelcast-sql/src/test/java/com/hazelcast/sql/impl/schema/IMapResolverTest.java
  hazelcast/src/main/java/com/hazelcast/sql/impl/client/SqlClientService.java
Labels: Type: Enhancement, Source: Internal, Team: SQL

#20042 [HZ-757] Support sub-queries and VALUES() execution in JOIN arguments
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/HazelcastSqlValidator.java
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/ValidatorResource.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/map/SqlJoinTest.java
Labels: Type: Enhancement, Source: Internal, Team: SQL, Add to Release Notes

#20056 Update kotlin to 1.5.32
  pom.xml
Labels: Team: Core, Source: Internal, Not Release Notes content, dependencies

#20151 [5.0.z] Bump log4j2.version from 2.14.0 to 2.15.0 (#20144)
  pom.xml
Labels: Type: Defect, Team: Core, Source: Internal, Not Release Notes content, dependencies, security

#20045 Avoid need to open java.lang.reflect module on JDK17
  hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/ObjectDataInputStreamNonFinalMethodsTest.java
Labels: Type: Defect, Team: Core, Source: Internal, Module: Serialization, Not Release Notes content, JDK17

#20153 [5.0.1] Bump log4j2.version from 2.14.0 to 2.15.0 (#20144)
  pom.xml
Labels: Type: Defect, Team: Core, Source: Internal, Not Release Notes content, dependencies, security

#19963 [HZ-710] Implement view substitution
  docs/design/sql/12-create-index.md
  docs/design/sql/13-create-drop-view.md
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/CalciteSqlOptimizer.java
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/HazelcastSqlToRelConverter.java
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/OptimizerContext.java
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/PlanExecutor.java
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/SqlPlanImpl.java
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/virtual/ViewTable.java
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/parse/QueryConverter.java
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/parse/SqlCreateView.java
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/schema/HazelcastCalciteCatalogReader.java
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/schema/HazelcastViewExpander.java
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/schema/HazelcastViewRelOptTable.java
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/schema/TableResolverImpl.java
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/schema/TablesStorage.java
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/HazelcastSqlOperatorTable.java
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/HazelcastSqlValidator.java
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/operators/json/HazelcastJsonQueryFunction.java
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/operators/json/HazelcastJsonValueFunction.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/SqlExpandViewTest.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/CreateViewStatementTest.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/ShowStatementTest.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/map/SqlSelectTest.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/schema/SqlMappingTest.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/schema/TableResolverImplTest.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/schema/TablesStorageTest.java
  hazelcast/src/main/java/com/hazelcast/sql/impl/schema/view/View.java
Labels: Type: Enhancement, Source: Internal, Team: SQL, Not Release Notes content

#20051 fix leak on client message decoder
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/util/ClientMessageDecoder.java
  hazelcast/src/test/java/com/hazelcast/client/impl/protocol/util/ClientMessageSplitAndBuildTest.java
Labels: Type: Defect, Team: Client, Source: Internal, All Languages Should Check

#20161 Upgrade log4j2 to 2.15.0 [4.0.z]
  pom.xml
Labels: Team: Core, Backport, Source: Internal, Module: Security

#20163 Upgrade log4j2 to 2.15.0 [4.2.z]
  pom.xml
Labels: Type: Defect, Team: Core, Backport, Source: Internal, dependencies, security

#20162 Upgrade log4j2 to 2.15.0 [4.1.z]
  pom.xml
Labels: Type: Defect, Team: Core, Backport, Source: Internal, dependencies, security

#20169 fix leak on client message decoder
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/util/ClientMessageDecoder.java
  hazelcast/src/test/java/com/hazelcast/client/impl/protocol/util/ClientMessageSplitAndBuildTest.java
Labels: Type: Defect, Team: Client, Source: Internal

#20168 fix leak on client message decoder
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/util/ClientMessageDecoder.java
  hazelcast/src/test/java/com/hazelcast/client/impl/protocol/util/ClientMessageSplitAndBuildTest.java
Labels: Type: Defect, Team: Client, Source: Internal

#20167 fix leak on client message decoder
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/util/ClientMessageDecoder.java
  hazelcast/src/test/java/com/hazelcast/client/impl/protocol/util/ClientMessageSplitAndBuildTest.java
Labels: Type: Defect, Team: Client, Source: Internal

#20166 fix leak on client message decoder
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/util/ClientMessageDecoder.java
  hazelcast/src/test/java/com/hazelcast/client/impl/protocol/util/ClientMessageSplitAndBuildTest.java
Labels: Type: Defect, Team: Client, Source: Internal

#20181 Upgrade log4j2 to 2.15.0 [4.2.3]
  pom.xml
Labels: Type: Defect, Team: Core, Backport, Source: Internal, Module: Security, dependencies

#20180 Upgrade log4j2 to 2.15.0 [4.1.7]
  pom.xml
Labels: Type: Defect, Team: Core, Backport, Source: Internal, Module: Security, dependencies

#20179 Upgrade log4j2 to 2.15.0 [4.0.4]
  pom.xml
Labels: Type: Defect, Team: Core, Backport, Source: Internal, dependencies, security

#20149 Prerequisites for tiered store record
  hazelcast/src/main/java/com/hazelcast/map/impl/record/DataRecordFactory.java
  hazelcast/src/main/java/com/hazelcast/map/impl/record/ObjectRecordFactory.java
  hazelcast/src/main/java/com/hazelcast/map/impl/record/RecordFactory.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/AbstractRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/DefaultRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/RecordStore.java
  hazelcast/src/test/java/com/hazelcast/map/impl/record/AbstractRecordFactoryTest.java
  hazelcast/src/test/java/com/hazelcast/map/impl/recordstore/LazyEvictableEntryViewTest.java
  hazelcast/src/test/java/com/hazelcast/query/impl/IndexTest.java
Labels: Type: Enhancement, Estimation: S, Team: Storage, severity:high

#20165 Minor fix in View class
  hazelcast/src/main/java/com/hazelcast/sql/impl/schema/view/View.java
Labels: Type: Defect, Team: SQL

#20058 Fix SplitBrainTest#when_newMemberIsAddedAfterClusterSizeFallsBelowQuorumSize_then_jobRestartDoesNotSucceed
  hazelcast/src/test/java/com/hazelcast/jet/core/SplitBrainTest.java
Labels: Team: Core, Type: Test-Failure, Source: Internal, Not Release Notes content, Module: Jet

#19752 19494 Remove no-arg constructor requirement for no-configuration use case
  hazelcast/pom.xml
  hazelcast/src/main/java/com/hazelcast/internal/nio/InstanceCreationUtil.java
  hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/compact/CompactStreamSerializer.java
  hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/compact/ReflectiveCompactSerializer.java
  hazelcast/src/test/java/example/serialization/NodeDTO.java
  pom.xml
Labels: Type: Enhancement, Team: Client, Source: Community, Module: Serialization

#20199 Cleanup Storage interface
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/Storage.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/StorageImpl.java
Labels: Type: Enhancement, Priority: Medium, Source: Internal, Estimation: S, Team: Storage

#20164 Thread-safe cache replication
  hazelcast/src/main/java/com/hazelcast/cache/impl/operation/CacheNearCacheStateHolder.java
  hazelcast/src/main/java/com/hazelcast/config/AbstractCacheConfig.java
  hazelcast/src/test/java/com/hazelcast/config/CacheConfigTest.java
Labels: Type: Defect, Team: Core, Source: Internal, Module: ICache, Not Release Notes content

#20049 Avoid opening java.net module on JDK17 HZ-687
  hazelcast/src/main/java/com/hazelcast/instance/impl/DefaultAddressPicker.java
  hazelcast/src/main/java/com/hazelcast/kubernetes/DnsEndpointResolver.java
  hazelcast/src/test/java/com/hazelcast/instance/impl/DefaultAddressPickerHostnameTest.java
  hazelcast/src/test/java/com/hazelcast/instance/impl/DefaultAddressPickerInterfacesTest.java
  hazelcast/src/test/java/com/hazelcast/instance/impl/DummyNetworkInterfacesEnumerator.java
  hazelcast/src/test/java/com/hazelcast/instance/impl/NetworkInterfaceMockingOptions.java
  hazelcast/src/test/java/com/hazelcast/kubernetes/DnsEndpointResolverTest.java
Labels: Type: Enhancement, Team: Core, Source: Internal, Module: Network I/O, Not Release Notes content, JDK17

#20157 Avoid opening java.util module for tests on JDK17 HZ-687
  hazelcast/src/main/java/com/hazelcast/internal/config/override/EnvConfigProvider.java
  hazelcast/src/main/java/com/hazelcast/internal/config/override/ExternalConfigurationOverride.java
  hazelcast/src/main/java/com/hazelcast/internal/config/override/SystemPropertiesConfigProvider.java
  hazelcast/src/test/java/com/hazelcast/config/ConfigTest.java
  hazelcast/src/test/java/com/hazelcast/internal/config/override/ExternalClientConfigurationOverrideTest.java
  hazelcast/src/test/java/com/hazelcast/internal/config/override/ExternalConfigTestUtils.java
  hazelcast/src/test/java/com/hazelcast/internal/config/override/ExternalMemberConfigurationOverrideEnvTest.java
  hazelcast/src/test/java/com/hazelcast/internal/config/override/ExternalMemberConfigurationOverrideSystemPropertiesTest.java
  hazelcast/src/test/java/com/hazelcast/internal/config/override/SystemPropertiesClientConfigParserTest.java
  hazelcast/src/test/java/com/hazelcast/internal/config/override/SystemPropertiesConfigProviderTest.java
  hazelcast/src/test/java/com/hazelcast/kubernetes/KubernetesApiEndpointResolverTest.java
  hazelcast/src/test/java/com/hazelcast/test/OverridePropertyRulePowerMockTest.java
Labels: Type: Defect, Team: Core, Source: Internal, Module: Config, Not Release Notes content, JDK17

#20201 Fix one of SplitBrainTest [5.0.z]
  hazelcast/src/test/java/com/hazelcast/jet/core/SplitBrainTest.java
Labels: Team: Core, Type: Test-Failure, Backport, Source: Internal, Not Release Notes content, Module: Jet

#20156 Avoid opening java.io module for tests on JDK17 HZ-687
  hazelcast/src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyFactory.java
  hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesConfig.java
  hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/VersionedInCurrentVersionTest.java
  hazelcast/src/test/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategyFactoryTest.java
  hazelcast/src/test/java/com/hazelcast/kubernetes/KubernetesConfigTest.java
Labels: Type: Defect, Team: Core, Source: Internal, Not Release Notes content, Module: Kubernetes, JDK17

#20193 Update kotlin to 1.5.32 [5.0.z]
  pom.xml
Labels: Source: Internal, Not Release Notes content, dependencies, Module: Jet, Team: Platform

#20209 [TSTORE] Pass partitionId to RecordFactory
  hazelcast/src/main/java/com/hazelcast/map/impl/MapContainer.java
  hazelcast/src/main/java/com/hazelcast/map/impl/record/RecordFactoryAttributes.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/AbstractRecordStore.java
Labels: Type: Enhancement, Priority: High, Source: Internal, Team: Storage, Module: TStore

#20174 Avoid NPE for mapContainer request during CREATE INDEX
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/PlanExecutor.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/SqlCreateIndexTest.java
Labels: Type: Defect, Source: Internal, Team: SQL

#20041 [HZ-762] Add THIRD-PARTY.txt and attribution.txt to Hazelcast artifacts [4.2.z]
  distribution/pom.xml
  hazelcast-all/pom.xml
  hazelcast-build-utils/pom.xml
  hazelcast-build-utils/src/main/java/com/hazelcast/buildutils/HazelcastLicenseResourceTransformer.java
  hazelcast-build-utils/src/main/java/com/hazelcast/buildutils/HazelcastManifestTransformer.java
  hazelcast-build-utils/src/main/resources/LICENSE
  hazelcast-build-utils/src/main/resources/hazelcast-thirdparty-template.ftl
  hazelcast-spring-tests/pom.xml
  hazelcast-spring/pom.xml
  hazelcast-sql-core/pom.xml
  hazelcast-sql/pom.xml
  hazelcast/pom.xml
  modulepath-tests/pom.xml
  pom.xml
  src/main/assembly/assembly.xml
Labels: Type: Enhancement, Team: Core, Backport, Source: Internal, Module: Scripts

#20232 Bump log4j2.version from 2.16.0 to 2.17.0 [5.0.z]
  pom.xml
Labels: Type: Defect, Team: Core, Source: Community, Not Release Notes content, dependencies

#20239 Bump log4j2.version from 2.15.0 to 2.17.0 [4.2.4]
  pom.xml
Labels: Type: Defect, Team: Core, Source: Internal, Not Release Notes content, dependencies

#20234 Bump log4j2.version from 2.16.0 to 2.17.0 [5.0.2]
  pom.xml
Labels: Type: Defect, Team: Core, Source: Community, Not Release Notes content, dependencies

#20240 Bump log4j2.version from 2.15.0 to 2.17.0 [4.1.8]
  pom.xml
Labels: Type: Defect, Team: Core, Source: Internal, Not Release Notes content, dependencies

#20216 Rename deviceConfig to localDeviceConfig
  hazelcast-spring-tests/src/test/java/com/hazelcast/spring/TestFullApplicationContext.java
  hazelcast-spring-tests/src/test/resources/com/hazelcast/spring/fullConfig-applicationContext-hazelcast.xml
  hazelcast-spring/src/main/java/com/hazelcast/spring/HazelcastConfigBeanDefinitionParser.java
  hazelcast-spring/src/main/resources/hazelcast-spring-5.1.xsd
  hazelcast/src/main/java/com/hazelcast/config/Config.java
  hazelcast/src/main/java/com/hazelcast/config/ConfigXmlGenerator.java
  hazelcast/src/main/java/com/hazelcast/config/DeviceConfig.java
  hazelcast/src/main/java/com/hazelcast/config/DiskTierConfig.java
  hazelcast/src/main/java/com/hazelcast/config/LocalDeviceConfig.java
  hazelcast/src/main/java/com/hazelcast/internal/config/ConfigSections.java
  hazelcast/src/main/java/com/hazelcast/internal/config/ConfigUtils.java
  hazelcast/src/main/java/com/hazelcast/internal/config/MemberDomConfigProcessor.java
  hazelcast/src/main/java/com/hazelcast/internal/config/YamlMemberDomConfigProcessor.java
  hazelcast/src/main/resources/hazelcast-config-5.1.json
  hazelcast/src/main/resources/hazelcast-config-5.1.xsd
  hazelcast/src/main/resources/hazelcast-default.xml
  hazelcast/src/main/resources/hazelcast-default.yaml
  hazelcast/src/test/java/com/hazelcast/config/AbstractConfigBuilderTest.java
  hazelcast/src/test/java/com/hazelcast/config/ConfigCompatibilityChecker.java
  hazelcast/src/test/java/com/hazelcast/config/ConfigXmlGeneratorTest.java
  hazelcast/src/test/java/com/hazelcast/config/LocalDeviceConfigTest.java
  hazelcast/src/test/java/com/hazelcast/config/XMLConfigBuilderTest.java
  hazelcast/src/test/java/com/hazelcast/config/YamlConfigBuilderTest.java
  hazelcast/src/test/resources/com/hazelcast/config/yaml/testcases/member/tiered-store/multiple-failures.json
  hazelcast/src/test/resources/com/hazelcast/config/yaml/testcases/member/tiered-store/success.json
  hazelcast/src/test/resources/hazelcast-fullconfig-without-network.xml
  hazelcast/src/test/resources/hazelcast-fullconfig-without-network.yaml
Labels: Module: Config, Team: Storage

#20241 Bump log4j2.version from 2.15.0 to 2.17.0 [4.0.5]
  pom.xml
Labels: Type: Defect, Team: Core, Source: Internal, Not Release Notes content, dependencies

#20242 Bump log4j2.version from 2.16.0 to 2.17.0 [4.2.z]
  pom.xml
Labels: Type: Defect, Team: Core, Source: Internal, Not Release Notes content, dependencies

#20244 Bump log4j2.version from 2.16.0 to 2.17.0 [4.0.z]
  pom.xml
Labels: Type: Defect, Team: Core, Source: Internal, Not Release Notes content, dependencies

#20036 CacheConfigHolder fields should be final
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/holder/CacheConfigHolder.java
Labels: Type: Defect, Team: Core, Backport, Source: Internal, Module: ICache

#20035 CacheConfigHolder fields should be final
  hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/holder/CacheConfigHolder.java
Labels: Type: Defect, Team: Core, Source: Internal, Module: ICache, Forwardport

#19844 Make ClientInvocation_ExceptionTest use of separate client and member…
  hazelcast/src/test/java/com/hazelcast/client/impl/spi/impl/ClientInvocation_ExceptionTest.java
Labels: Team: Client, Team: Core, Type: Test-Failure, Source: Internal, Module: Invocation System

#20243 Bump log4j2.version from 2.16.0 to 2.17.0 [4.1.z]
  pom.xml
Labels: Type: Defect, Team: Core, Source: Internal, Not Release Notes content, dependencies

#20233 Windows/mac line endings fix for IMapResolverTest
  hazelcast-sql/src/test/java/com/hazelcast/sql/impl/schema/IMapResolverTest.java
Labels: Type: Test-Failure, Source: Internal, Team: SQL, Module: Jet

#20148 Detect multiple versions of the Hazelcast classes HZ-732
  hazelcast/src/main/java/com/hazelcast/instance/impl/DuplicatedResourcesScanner.java
  hazelcast/src/main/java/com/hazelcast/instance/impl/HazelcastInstanceFactory.java
  hazelcast/src/test/java/com/hazelcast/instance/impl/DuplicatedResourcesScannerTest.java
Labels: Type: Enhancement, Team: Core, Source: Internal, Not Release Notes content, Module: Spring

#20215 doc: for usePublic true on the Cloud
  hazelcast/src/main/java/com/hazelcast/client/impl/clientside/ClusterDiscoveryServiceBuilder.java
Labels: Type: Enhancement, Team: Client, Source: Internal, Not Release Notes content, Type: Documentation

#20221 Allow integer conversions for SQL dynamic params
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/param/NumericPrecedenceParameterConverter.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/SqlParameterTest.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/expression/math/RoundFunctionIntegrationTest.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/expression/math/TruncateFunctionIntegrationTest.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/expression/string/SubstringFunctionIntegrationTest.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/validate/RowAssignmentTypeCoercionTest.java
Labels: Type: Enhancement, Source: Internal, Team: SQL

#20037 Refactor Heartbeat/Icmp to reduce class dependencies
  hazelcast/src/main/java/com/hazelcast/client/impl/clientside/HazelcastClientInstanceImpl.java
  hazelcast/src/main/java/com/hazelcast/client/impl/connection/ClientConnectionManager.java
  hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/ClientICMPManager.java
  hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/HeartbeatManager.java
  hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java
  hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/listener/ClientListenerServiceImpl.java
  hazelcast/src/main/java/com/hazelcast/client/impl/statistics/ClusterConnectionMetricsProvider.java
  hazelcast/src/main/java/com/hazelcast/internal/cluster/fd/PingFailureDetector.java
  hazelcast/src/test/java/com/hazelcast/client/listeners/AbstractListenersOnReconnectTest.java
  hazelcast/src/test/java/com/hazelcast/client/test/ClientTestSupport.java
Labels: Type: Enhancement, Team: Client

#20256 Fix mapping of Map fields in SQL
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/SqlFilterProjectTest.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/aggregate/SqlAggregateTest_TypeCoercion.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/kafka/SqlAvroTest.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/kafka/SqlJsonTest.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/kafka/SqlPojoTest.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/map/SqlJsonTest.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/map/SqlPojoTest.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/map/SqlPortableTest.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/map/model/AllTypesValue.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/test/TestAllTypesSqlConnector.java
  hazelcast/src/main/java/com/hazelcast/sql/impl/type/QueryDataTypeUtils.java
Labels: Type: Defect, Source: Community, Team: SQL

#20016 Define declarative configuration schemas for CompactSerializationConfig
  hazelcast-spring-tests/src/test/java/com/hazelcast/spring/TestClientApplicationContext.java
  hazelcast-spring-tests/src/test/java/com/hazelcast/spring/TestFullApplicationContext.java
  hazelcast-spring-tests/src/test/java/com/hazelcast/spring/serialization/DummyCompactSerializable.java
  hazelcast-spring-tests/src/test/java/com/hazelcast/spring/serialization/DummyCompactSerializer.java
  hazelcast-spring-tests/src/test/java/com/hazelcast/spring/serialization/DummyReflectiveSerializable.java
  hazelcast-spring-tests/src/test/resources/com/hazelcast/spring/fullConfig-applicationContext-hazelcast.xml
  hazelcast-spring-tests/src/test/resources/com/hazelcast/spring/node-client-applicationContext-hazelcast.xml
  hazelcast-spring/src/main/java/com/hazelcast/spring/AbstractHazelcastBeanDefinitionParser.java
  hazelcast-spring/src/main/java/com/hazelcast/spring/config/ConfigFactory.java
  hazelcast-spring/src/main/resources/hazelcast-spring-5.1.xsd
  hazelcast-spring/src/test/java/com/hazelcast/spring/config/ConfigFactoryTest.java
  hazelcast/src/main/java/com/hazelcast/client/config/ClientConfigXmlGenerator.java
  hazelcast/src/main/java/com/hazelcast/config/ConfigXmlGenerator.java
  hazelcast/src/main/resources/hazelcast-client-config-5.1.xsd
  hazelcast/src/main/resources/hazelcast-client-full-example.xml
  hazelcast/src/main/resources/hazelcast-client-full-example.yaml
  hazelcast/src/main/resources/hazelcast-config-5.1.json
  hazelcast/src/main/resources/hazelcast-config-5.1.xsd
  hazelcast/src/main/resources/hazelcast-full-example.xml
  hazelcast/src/main/resources/hazelcast-full-example.yaml
  hazelcast/src/test/java/com/hazelcast/client/config/AbstractClientConfigBuilderTest.java
  hazelcast/src/test/java/com/hazelcast/client/config/ClientConfigXmlGeneratorTest.java
  hazelcast/src/test/java/com/hazelcast/client/config/XmlClientConfigBuilderTest.java
  hazelcast/src/test/java/com/hazelcast/client/config/YamlClientConfigBuilderTest.java
  hazelcast/src/test/java/com/hazelcast/config/AbstractConfigBuilderTest.java
  hazelcast/src/test/java/com/hazelcast/config/CompactSerializationConfigConfigBuilderTest.java
  hazelcast/src/test/java/com/hazelcast/config/ConfigXmlGeneratorTest.java
  hazelcast/src/test/java/com/hazelcast/config/XMLConfigBuilderTest.java
  hazelcast/src/test/java/com/hazelcast/config/YamlConfigBuilderTest.java
  hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/compact/CompactTestUtil.java
  hazelcast/src/test/resources/com/hazelcast/config/yaml/testcases/common/serialization/multiple-failures.json
  hazelcast/src/test/resources/com/hazelcast/config/yaml/testcases/common/serialization/success.json
  hazelcast/src/test/resources/hazelcast-client-full.xml
  hazelcast/src/test/resources/hazelcast-client-full.yaml
  hazelcast/src/test/resources/hazelcast-fullconfig-without-network.xml
  hazelcast/src/test/resources/hazelcast-fullconfig-without-network.yaml
Labels: Type: Enhancement, Team: Client, Source: Internal, Module: Serialization

#20274 [HZ-797] TSTORE: TieredStorageImpl integration into IMap
  checkstyle/suppressions.xml
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/BasePutOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/BaseRemoveOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/ClearOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/GetOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/MapOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/AbstractEvictableRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/DefaultRecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/JsonMetadataStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/RecordStore.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/Storage.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/StorageImpl.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/StorageSCHM.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/expiry/ExpirySystem.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/expiry/ExpirySystemIf.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/OperationRunner.java
  hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationRunnerImpl.java
  hazelcast/src/test/java/com/hazelcast/map/BasicMapTest.java
  hazelcast/src/test/java/com/hazelcast/test/HazelcastTestSupport.java
Labels: Type: Enhancement, Priority: High, Estimation: M, Team: Storage, Module: TStore
