Repository hazelcast/hazelcast, pull requests merged in 2023-06, with the labels that each got.

#24704 Fix leading zero calculation [HZ-2492] [5.3.z] (#24674)
  hazelcast/src/main/java/com/hazelcast/internal/util/Sha256Util.java
  hazelcast/src/test/java/com/hazelcast/internal/util/Sha256UtilTest.java
Labels: Type: Defect, Team: Integration, Source: Internal, Module: Jet

#24714 Remove PowerMock [HZ-774]
  hazelcast/src/test/java/com/hazelcast/map/impl/query/ParallelPartitionScanExecutorTest.java
  hazelcast/src/test/java/com/hazelcast/test/OverridePropertyRuleMockTest.java
  pom.xml
Labels: Team: Integration, Type: Cleanup, Source: Internal, Not Release Notes content

#24691 Bump hadoop.version from 3.3.4 to 3.3.5 [5.2.z]
  extensions/hadoop-dist/pom.xml
  pom.xml
Labels: Source: Internal, Source: Community, dependencies, jdk8-not-supported

#24690 Bump hadoop.version from 3.3.4 to 3.3.5 [5.3.z]
  extensions/hadoop-dist/pom.xml
  pom.xml
Labels: Source: Internal, Source: Community, dependencies, jdk8-not-supported

#24727 Bump jackson.version to 2.15.2 [5.3.z]
  extensions/csv/pom.xml
  extensions/kinesis/pom.xml
  hazelcast/pom.xml
  pom.xml
Labels: Team: Integration, Source: Internal, Add to Release Notes, dependencies, Module: Maven build

#24685 Skip archunit tests for JDK 21 [HZ-2496]
  extensions/avro/src/test/java/com/hazelcast/jet/avro/AvroSerializableTest.java
  extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/CdcDebeziumSerializableTest.java
  extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/CdcMysqlSerializableTest.java
  extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/CdcPostgresSerializableTest.java
  extensions/csv/src/test/java/com/hazelcast/jet/csv/CsvSerializableTest.java
  extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/Elastic6SerializableTest.java
  extensions/elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/elastic/Elastic7SerializableTest.java
  extensions/grpc/src/test/java/com/hazelcast/jet/grpc/GrpcSerializableTest.java
  extensions/hadoop/src/test/java/com/hazelcast/jet/hadoop/HadoopSerializableTest.java
  extensions/kafka/src/test/java/com/hazelcast/jet/kafka/KafkaSerializableTest.java
  extensions/kinesis/src/test/java/com/hazelcast/jet/kinesis/KinesisSerializableTest.java
  extensions/python/src/test/java/com/hazelcast/jet/python/PythonSerializableTest.java
  extensions/s3/src/test/java/com/hazelcast/jet/s3/S3SerializableTest.java
  hazelcast-archunit-rules/pom.xml
  hazelcast-archunit-rules/src/main/java/com/hazelcast/test/archunit/ArchUnitTestSupport.java
  hazelcast-archunit-rules/src/test/java/com/hazelcast/test/archunit/ArchUnitRulesTest.java
  hazelcast/src/test/java/com/hazelcast/HazelcastCompletableFutureAsyncUsageTest.java
  hazelcast/src/test/java/com/hazelcast/jet/JetSerializableTest.java
Labels: Team: Integration, Type: Test-Failure, Source: Internal, Not Release Notes content, Module: Jet

#24598 Wrap TABLE operator in subquery for better scoping [HZ-2453]
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/HazelcastSqlValidator.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/s2sjoin/SqlStreamToStreamJoinTest.java
Labels: Type: Enhancement, Source: Internal, Team: SQL, Not Release Notes content, SQL-only, Module: SQL

#24738 Remove unknown parameter enableRSS from checkstyle config
  pom.xml
Labels: Team: Integration, Type: Cleanup, Source: Internal, Not Release Notes content, Module: Maven build

#24739 Fix deprecations without annotation
  hazelcast/src/main/java/com/hazelcast/config/security/LdapAuthenticationConfig.java
  hazelcast/src/main/java/com/hazelcast/hotrestart/package-info.java
  hazelcast/src/main/java/com/hazelcast/jet/JetCacheManager.java
  hazelcast/src/main/java/com/hazelcast/jet/config/InstanceConfig.java
  hazelcast/src/main/java/com/hazelcast/jet/pipeline/FileSourceBuilder.java
  hazelcast/src/main/java/com/hazelcast/jet/pipeline/GeneralStageWithKey.java
  hazelcast/src/main/java/com/hazelcast/jet/pipeline/Pipeline.java
  hazelcast/src/main/java/com/hazelcast/memory/MemorySize.java
Labels: Type: Cleanup, Source: Internal, Not Release Notes content, Team: Platform

#24734 Remove elasticsearch-6 extension module
  distribution/pom.xml
  extensions/elasticsearch/elasticsearch-6/pom.xml
  extensions/elasticsearch/elasticsearch-6/src/main/java/com/hazelcast/jet/elastic/ElasticClients.java
  extensions/elasticsearch/elasticsearch-6/src/main/java/com/hazelcast/jet/elastic/ElasticSinkBuilder.java
  extensions/elasticsearch/elasticsearch-6/src/main/java/com/hazelcast/jet/elastic/ElasticSinks.java
  extensions/elasticsearch/elasticsearch-6/src/main/java/com/hazelcast/jet/elastic/ElasticSourceBuilder.java
  extensions/elasticsearch/elasticsearch-6/src/main/java/com/hazelcast/jet/elastic/ElasticSources.java
  extensions/elasticsearch/elasticsearch-6/src/main/java/com/hazelcast/jet/elastic/impl/ElasticCatClient.java
  extensions/elasticsearch/elasticsearch-6/src/main/java/com/hazelcast/jet/elastic/impl/ElasticSourceConfiguration.java
  extensions/elasticsearch/elasticsearch-6/src/main/java/com/hazelcast/jet/elastic/impl/ElasticSourceP.java
  extensions/elasticsearch/elasticsearch-6/src/main/java/com/hazelcast/jet/elastic/impl/ElasticSourcePMetaSupplier.java
  extensions/elasticsearch/elasticsearch-6/src/main/java/com/hazelcast/jet/elastic/impl/ElasticSourcePSupplier.java
  extensions/elasticsearch/elasticsearch-6/src/main/java/com/hazelcast/jet/elastic/impl/RetryUtils.java
  extensions/elasticsearch/elasticsearch-6/src/main/java/com/hazelcast/jet/elastic/impl/Shard.java
  extensions/elasticsearch/elasticsearch-6/src/main/java/com/hazelcast/jet/elastic/package-info.java
  extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/AuthElasticSinksTest.java
  extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/AuthElasticSourcesTest.java
  extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/BaseElasticTest.java
  extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/ClientHolder.java
  extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/CommonElasticSinksTest.java
  extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/CommonElasticSourcesTest.java
  extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/Elastic6SerializableTest.java
  extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/ElasticClientsTest.java
  extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/ElasticSinkBuilderTest.java
  extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/ElasticSourceBuilderTest.java
  extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/ElasticSupport.java
  extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/LocalClusterElasticSinksTest.java
  extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/LocalClusterElasticSourcesTest.java
  extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/LocalElasticSinkTest.java
  extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/LocalElasticSourcesTest.java
  extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/impl/ElasticCatClientTest.java
  extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/impl/ElasticSourcePMetaSupplierTest.java
  extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/impl/ElasticSourcePTest.java
  extensions/elasticsearch/elasticsearch-6/src/test/resources/log4j2.xml
  extensions/elasticsearch/elasticsearch-6/src/test/resources/mock_es_responses/es2node_nodes.json
  extensions/elasticsearch/elasticsearch-6/src/test/resources/mock_es_responses/es2node_shards.json
  extensions/elasticsearch/elasticsearch-6/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  extensions/pom.xml
  hazelcast-coverage-report/pom.xml
Labels: Team: Integration, Type: Cleanup, Source: Internal, Add to Release Notes, Module: Jet

#24743 Add profile allowing to skip modulepath tests
  pom.xml
Labels: Team: Integration, Type: Cleanup, Source: Internal, Not Release Notes content, Module: Maven build

#24730 Bump jackson.version to 2.15.2 [5.2.z]
  extensions/csv/pom.xml
  extensions/kinesis/pom.xml
  hazelcast/pom.xml
  pom.xml
Labels: Team: Integration, Source: Internal, Add to Release Notes, dependencies, Module: Maven build

#24733 Bump jackson.version to 2.15.2 [5.0.z]
  extensions/csv/pom.xml
  extensions/kinesis/pom.xml
  hazelcast/pom.xml
  pom.xml
Labels: Team: Integration, Source: Internal, Add to Release Notes, dependencies, Module: Maven build

#24742 Disable license plugin by default
  distribution/src/main/resources/META-INF/THIRD-PARTY.txt
  pom.xml
Labels: Team: Integration, Type: Cleanup, Source: Internal, Not Release Notes content, Module: Maven build

#24741 Exclude conflicting files from shading
  hazelcast-sql/pom.xml
  pom.xml
Labels: Team: Integration, Type: Cleanup, Source: Internal, Not Release Notes content, Module: Maven build

#24731 Bump jackson.version to 2.15.2 [5.1.z]
  extensions/csv/pom.xml
  extensions/kinesis/pom.xml
  hazelcast/pom.xml
  pom.xml
Labels: Team: Integration, Source: Internal, Add to Release Notes, dependencies, Module: Maven build

#24754 No @Deprecated on package
  hazelcast/src/main/java/com/hazelcast/hotrestart/package-info.java
Labels: Type: Defect, Source: Internal, Not Release Notes content, Team: Platform

#24728 Reduce the size of entries because test is timing out [HZ-2361]
  hazelcast/src/test/java/com/hazelcast/core/PipeliningTest.java
Labels: Team: Integration, Type: Test-Failure, Source: Internal, Module: Jet

#24756 Reduce the size of entries because test is timing out [HZ-2361] (#24728)
  hazelcast/src/test/java/com/hazelcast/core/PipeliningTest.java
Labels: Team: Integration, Type: Test-Failure, Source: Internal, Module: Jet

#24760 Revert "Bump antlr4-runtime from 4.9.3 to 4.13.0"
  pom.xml
Labels: Type: Defect, Team: Integration, Source: Internal, dependencies, Module: Maven build

#24758 [TPC] Ensuring that all tests run on different ports
  hazelcast-tpc-engine/src/test/java/com/hazelcast/internal/tpcengine/net/AsyncServerSocketTest.java
  hazelcast-tpc-engine/src/test/java/com/hazelcast/internal/tpcengine/net/AsyncSocketTest.java
Labels: Module: TPC

#24709 Modify KubernetesClient shutdown behaviour (#24613) [5.2.z]
  hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesClient.java
  hazelcast/src/main/java/com/hazelcast/spi/utils/RestClient.java
  hazelcast/src/test/java/com/hazelcast/kubernetes/StsMonitorTest.java
Labels: Backport

#24710 Modify KubernetesClient shutdown behaviour (#24613) [5.3.z]
  hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesClient.java
  hazelcast/src/main/java/com/hazelcast/spi/utils/RestClient.java
  hazelcast/src/test/java/com/hazelcast/kubernetes/StsMonitorTest.java
Labels: Backport

#24771 Change maven coordinates of MySQL JDBC connector. [HZ-2532]
  extensions/kafka-connect/pom.xml
  extensions/mapstore/pom.xml
  hazelcast-sql/pom.xml
  hazelcast/pom.xml
  pom.xml
Labels: Team: Integration, Type: Cleanup, Source: Internal, Not Release Notes content, Module: Jet

#24785 Fixes after Hamcrest removal
  hazelcast-archunit-rules/src/main/java/com/hazelcast/test/archunit/ArchUnitRules.java
  hazelcast-archunit-rules/src/main/java/com/hazelcast/test/archunit/MatchersUsageCondition.java
  hazelcast-archunit-rules/src/main/java/com/hazelcast/test/archunit/ModuleImportOptions.java
  hazelcast/pom.xml
  hazelcast/src/test/java/com/hazelcast/NoHamcrestInOurTestSourcesTest.java
Labels: Type: Test-Failure, Source: Internal, Not Release Notes content, Team: Integration

#24788 Bump Guava version from 32.0.0-jre to 32.0.1-jre [HZ-2553]
  pom.xml
Labels: Team: Core, Type: Test-Failure, Source: Internal, Not Release Notes content, Module: OSGi

#24790 Move ModulePathTest back to src/test/java
  modulepath-tests/pom.xml
  modulepath-tests/src/main/java/com/hazelcast/test/modulepath/package-info.java
  modulepath-tests/src/test/java/com/hazelcast/test/modulepath/ModulePathTest.java
Labels: Type: Cleanup, Source: Internal, Not Release Notes content, Team: Integration

#24786 Fix test by waiting with interruptible sleep
  hazelcast/src/test/java/com/hazelcast/map/EntryProcessorOffloadableTest.java
Labels: Type: Test-Failure

#24787 Fix test by waiting with interruptible sleep [5.3.z]
  hazelcast/src/test/java/com/hazelcast/map/EntryProcessorOffloadableTest.java
Labels: Type: Test-Failure

#24778 Replace Mockito spy usage in QueryIndexingTest [HZ-2491]
  hazelcast/src/test/java/com/hazelcast/map/impl/query/QueryIndexingTest.java
  hazelcast/src/test/java/com/hazelcast/query/SampleTestObjects.java
Labels: Team: Core, Type: Test-Failure, Source: Internal, Module: IMap, Not Release Notes content

#24692 Bump hadoop.version from 3.3.4 to 3.3.5 [5.1.z]
  extensions/hadoop-dist/pom.xml
  hazelcast-sql/pom.xml
  pom.xml
Labels: Source: Internal, Source: Community, dependencies, jdk8-not-supported

#24693 Bump hadoop.version from 3.3.4 to 3.3.5 [5.0.z]
  extensions/hadoop-dist/pom.xml
  hazelcast-sql/pom.xml
  pom.xml
Labels: Source: Internal, Source: Community, dependencies, jdk8-not-supported

#24802 Bump wildfly-openssl from 1.0.12.Final to 1.1.3.Final [5.1.z]
  pom.xml
Labels: Source: Internal, Source: Community, dependencies

#24803 Bump wildfly-openssl from 1.0.12.Final to 1.1.3.Final [5.0.z]
  pom.xml
Labels: Source: Internal, Source: Community, dependencies

#24668 Prevent sending empty map interceptors information to new members (#24639) [5.1.z]
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/PostJoinMapOperation.java
  hazelcast/src/test/java/com/hazelcast/map/impl/operation/PostJoinMapOperationTest.java
Labels: Source: Community

#24667 Prevent sending empty map interceptors information to new members (#24639) [5.0.z]
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/PostJoinMapOperation.java
  hazelcast/src/test/java/com/hazelcast/map/impl/operation/PostJoinMapOperationTest.java
Labels: Source: Community

#24670 Prevent sending empty map interceptors information to new members (#24639) [5.3.z]
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/PostJoinMapOperation.java
  hazelcast/src/test/java/com/hazelcast/map/impl/operation/PostJoinMapOperationTest.java
Labels: Source: Community

#24669 Prevent sending empty map interceptors information to new members (#24639) [5.2.z]
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/PostJoinMapOperation.java
  hazelcast/src/test/java/com/hazelcast/map/impl/operation/PostJoinMapOperationTest.java
Labels: Source: Community

#24745 Do not try to connect to the old member list after the cluster changes [API-2038]
  hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java
  hazelcast/src/main/java/com/hazelcast/client/impl/spi/ClientClusterService.java
  hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/ClientClusterServiceImpl.java
  hazelcast/src/test/java/com/hazelcast/client/impl/spi/impl/ClientClusterServiceImplTest.java
Labels: Type: Defect, Team: Client, Source: Internal, All Languages Should Check

#24799 Refactor test to adapt tiered storage
  hazelcast/src/test/java/com/hazelcast/map/EntryProcessorBouncingNodesTest.java
  hazelcast/src/test/java/com/hazelcast/map/EntryProcessorOffloadableBouncingNodesTest.java
  hazelcast/src/test/java/com/hazelcast/map/MapPutAllWithBouncingMemberTest.java
Labels: Team: Storage, Module: TStore

#24808 Introduce ClusterState check in ClearExpiredRecordsTask [HZ-2262]
  hazelcast/src/main/java/com/hazelcast/internal/eviction/ClearExpiredRecordsTask.java
Labels: Type: Enhancement, Team: Core, Source: Internal, Module: Cluster, Add to Release Notes

#24807 Fix test by setting driver count to 1
  hazelcast/src/test/java/com/hazelcast/map/EntryProcessorBouncingNodesTest.java
Labels: Type: Test-Failure, Team: Storage

#24784 Wrap TABLE operator in subquery for better scoping [HZ-2453] [5.3.z]
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/HazelcastSqlValidator.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/s2sjoin/SqlStreamToStreamJoinTest.java
Labels: Type: Enhancement, Source: Internal, Team: SQL, Not Release Notes content, SQL-only, Module: SQL

#24816 Add Couchbase start retries - as adviced in their issue
  extensions/kafka-connect/src/test/java/com/hazelcast/jet/kafka/connect/KafkaConnectCouchbaseIntegrationTest.java
Labels: Type: Test-Failure, Source: Internal, Not Release Notes content, Team: Integration

#24794 Improvements to RestClientTest TLS 1.3 support tests [HZ-2541]
  hazelcast/src/test/java/com/hazelcast/spi/utils/RestClientTest.java
  hazelcast/src/test/java/com/hazelcast/test/bounce/ProgressMonitor.java
Labels: Team: Core, Type: Test-Failure, Source: Internal, Not Release Notes content, Module: REST

#24795 CP subsystem diagnostics fix
  hazelcast/src/main/java/com/hazelcast/cp/internal/datastructures/atomiclong/AtomicLongService.java
  hazelcast/src/main/java/com/hazelcast/cp/internal/datastructures/atomicref/AtomicRefService.java
  hazelcast/src/main/java/com/hazelcast/cp/internal/datastructures/countdownlatch/CountDownLatchService.java
  hazelcast/src/main/java/com/hazelcast/cp/internal/datastructures/lock/LockService.java
  hazelcast/src/main/java/com/hazelcast/cp/internal/datastructures/semaphore/SemaphoreService.java
Labels: Priority: Medium, Module: Diagnostics, Module: CP Subsystem

#24792 Fix MongoSourcesWindowedTest [HZ-2558]
  extensions/mongodb/src/test/java/com/hazelcast/jet/mongodb/MongoSourcesWindowedTest.java
Labels: Type: Test-Failure, Source: Internal, Not Release Notes content, Team: Integration

#24829 Enable FetchEntriesOperation as a Step operation [HZ-2574]
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/MapFetchEntriesOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/steps/UtilSteps.java
Labels: Type: Defect, Priority: High, Source: Internal, Estimation: S, Team: Storage, severity:high, Module: TStore

#24833 Use DIRECT_RUN_STEP where possible and javaDoc it
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/steps/IMapStepAwareOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/steps/UtilSteps.java
Labels: Type: Cleanup, Team: SQL, Team: Storage

#24686 Implement scan processor partition pruning [HZ-2497]
  hazelcast/src/main/java/com/hazelcast/jet/core/processor/SourceProcessors.java
  hazelcast/src/main/java/com/hazelcast/jet/impl/connector/HazelcastReaders.java
  hazelcast/src/main/java/com/hazelcast/jet/impl/connector/ReadMapOrCacheP.java
Labels: Type: Enhancement, Source: Internal, Team: SQL, Module: SQL

#24796 CP subsystem diagnostics fix [5.3.z]
  hazelcast/src/main/java/com/hazelcast/cp/internal/datastructures/atomiclong/AtomicLongService.java
  hazelcast/src/main/java/com/hazelcast/cp/internal/datastructures/atomicref/AtomicRefService.java
  hazelcast/src/main/java/com/hazelcast/cp/internal/datastructures/countdownlatch/CountDownLatchService.java
  hazelcast/src/main/java/com/hazelcast/cp/internal/datastructures/lock/LockService.java
  hazelcast/src/main/java/com/hazelcast/cp/internal/datastructures/semaphore/SemaphoreService.java
Labels: Priority: Medium, Module: Diagnostics, Module: CP Subsystem

#24834 Fix K8s service port [CN-894]
  hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesApiProvider.java
  hazelcast/src/test/java/com/hazelcast/kubernetes/KubernetesApiEndpointProviderTest.java
  hazelcast/src/test/java/com/hazelcast/kubernetes/KubernetesApiEndpointSlicesProviderTest.java
  hazelcast/src/test/java/com/hazelcast/kubernetes/KubernetesClientTest.java
Labels: Type: Defect, Source: Internal, Module: Discovery SPI, Add to Release Notes, Module: Kubernetes, Team: Cloud Native

#24842 Fix K8s service port [CN-894] [backport]
  hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesApiProvider.java
  hazelcast/src/test/java/com/hazelcast/kubernetes/KubernetesApiEndpointProviderTest.java
  hazelcast/src/test/java/com/hazelcast/kubernetes/KubernetesApiEndpointSlicesProviderTest.java
  hazelcast/src/test/java/com/hazelcast/kubernetes/KubernetesClientTest.java
Labels: Type: Defect, Source: Internal, Module: Discovery SPI, Module: Kubernetes, Team: Cloud Native

#24780 Fix THIRD-PARTY.txt file in distribution
  distribution/pom.xml
Labels: Type: Defect, Source: Internal, Not Release Notes content, Team: Integration, Module: Maven build

#24772 Introduce a property to control the reconnection behavior of the client [API-2036]
  hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java
  hazelcast/src/test/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManagerTest.java
Labels: Type: Enhancement, Team: Client, Source: Internal, All Languages Should Check

#24855 Allow for dumb terminal when using 'hz-cli sql' with non-terminal input/output
  hazelcast/src/main/java/com/hazelcast/client/console/SqlConsole.java
Labels: Type: Defect, Source: Internal, Not Release Notes content, Module: CLI, Team: Integration

#24863 Update snappy to 1.1.10.1 [HZ-2614]
  pom.xml
Labels: Type: Cleanup, Source: Internal, Add to Release Notes, dependencies, security, Team: Integration

#24864 Update snappy to 1.1.10.1 [HZ-2614] [5.0.z]
  pom.xml
Labels: Type: Cleanup, Source: Internal, Add to Release Notes, dependencies, Team: Integration

#24815 DefaultRecordStore.getStateMessage() rewrite for OpenJ9
  hazelcast/src/main/java/com/hazelcast/internal/util/FutureUtil.java
  hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/DefaultRecordStore.java
Labels: Type: Defect, Source: Internal, Module: IMap, Not Release Notes content, Team: Integration

#24793 Don't throw exception when instance is closed before afterClass
  hazelcast/src/main/java/com/hazelcast/instance/impl/HazelcastInstanceImpl.java
  hazelcast/src/test/java/com/hazelcast/jet/SimpleTestInClusterSupport.java
Labels: Type: Test-Failure, Source: Internal, Not Release Notes content, Team: Integration

#24783 [TPC] Implement nio async storage [HZ-1560]
  hazelcast-tpc-engine-iouring/src/main/java/com/hazelcast/internal/tpcengine/iouring/IOUringEventloop.java
  hazelcast-tpc-engine-iouring/src/main/java/com/hazelcast/internal/tpcengine/iouring/IOUringReactor.java
  hazelcast-tpc-engine-iouring/src/main/java/com/hazelcast/internal/tpcengine/iouring/IOUringReactorBuilder.java
  hazelcast-tpc-engine/src/main/java/com/hazelcast/internal/tpcengine/Eventloop.java
  hazelcast-tpc-engine/src/main/java/com/hazelcast/internal/tpcengine/nio/NioAsyncFile.java
  hazelcast-tpc-engine/src/main/java/com/hazelcast/internal/tpcengine/nio/NioBlockRequestScheduler.java
  hazelcast-tpc-engine/src/main/java/com/hazelcast/internal/tpcengine/nio/NioEventloop.java
  hazelcast-tpc-engine/src/test/java/com/hazelcast/internal/tpcengine/file/FileTestSupport.java
  hazelcast-tpc-engine/src/test/java/com/hazelcast/internal/tpcengine/nio/NioAsyncFileTest.java
  hazelcast-tpc-engine/src/test/java/com/hazelcast/internal/tpcengine/nio/NioFileCopyTest.java
Labels: Team: Alto

#24810 Implement non-caching version of `forceTotalParallelismOne` [HZ-1660]
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/JetSqlSerializerHook.java
  hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/map/LazyDefiningSpecificMemberPms.java
  hazelcast-sql/src/main/java/com/hazelcast/sql/impl/expression/ExpressionEvalContext.java
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/map/LazyDefiningPMSTest.java
  hazelcast/src/main/java/com/hazelcast/jet/core/ProcessorMetaSupplier.java
  hazelcast/src/main/java/com/hazelcast/jet/core/test/TestProcessorMetaSupplierContext.java
Labels: Type: Enhancement, Source: Internal, Team: SQL, Module: Jet, Module: SQL

#24886 Update netty to 4.1.94.Final [5.0.z]
  pom.xml
Labels: Type: Cleanup, Source: Internal, Add to Release Notes, dependencies, Team: Integration

#24830 Consider AbstractJoiner's permanent blacklist in split-brain handling [HZ-2065]
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/TcpIpJoiner.java
  hazelcast/src/test/java/com/hazelcast/cluster/SplitBrainHandlerTest.java
Labels: Type: Defect, Team: Core, Source: Internal, Module: Cluster, Add to Release Notes

#24854 Replace Mockito invocation counter in MetricsCompressorTest (#24773) [5.3.z]
  hazelcast/src/test/java/com/hazelcast/internal/metrics/impl/MetricsCompressorTest.java
Labels: Team: Core, Type: Test-Failure, Backport, Source: Internal, Module: Metrics, Not Release Notes content

#24672 Feature: Improve batching in write-behind processor.
  hazelcast/src/main/java/com/hazelcast/map/impl/mapstore/writebehind/DefaultWriteBehindProcessor.java
  hazelcast/src/test/java/com/hazelcast/map/impl/mapstore/writebehind/WriteBehindCoalescingBatchingTest.java
Labels: Type: Enhancement, Team: Core, Type: Perf. Defect, Source: Community, Module: IMap, Add to Release Notes

#24870 Feature: Improve batching in write-behind processor [5.3.z]
  hazelcast/src/main/java/com/hazelcast/map/impl/mapstore/writebehind/DefaultWriteBehindProcessor.java
  hazelcast/src/test/java/com/hazelcast/map/impl/mapstore/writebehind/WriteBehindCoalescingBatchingTest.java
Labels: Team: Core, Backport, Type: Perf. Defect, Source: Community, Module: IMap, Add to Release Notes

#24888 Consider AbstractJoiner's permanent blacklist in split-brain handling [HZ-2065] [5.3.z] (#24830)
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/TcpIpJoiner.java
  hazelcast/src/test/java/com/hazelcast/cluster/SplitBrainHandlerTest.java
Labels: Type: Defect, Team: Core, Backport, Source: Internal, Module: Cluster, Add to Release Notes

#24893 Improve IO pipelines [5.0.5] [HZ-1884]
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/SqlErrorAbstractTest.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/InboundPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/OutboundPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/server/tcp/MemberChannelInitializer.java
  hazelcast/src/main/java/com/hazelcast/internal/server/tcp/MemberProtocolEncoder.java
  hazelcast/src/main/java/com/hazelcast/internal/server/tcp/SingleProtocolDecoder.java
  hazelcast/src/main/java/com/hazelcast/internal/server/tcp/SingleProtocolEncoder.java
  hazelcast/src/test/java/com/hazelcast/internal/server/tcp/ProtocolNegotiationTest.java
Labels: Type: Defect, Team: Core, Backport, Source: Internal, Module: Security

#24894 Improve IO pipelines [5.0.z] [HZ-1884]
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/SqlErrorAbstractTest.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/InboundPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/networking/OutboundPipeline.java
  hazelcast/src/main/java/com/hazelcast/internal/server/tcp/MemberChannelInitializer.java
  hazelcast/src/main/java/com/hazelcast/internal/server/tcp/MemberProtocolEncoder.java
  hazelcast/src/main/java/com/hazelcast/internal/server/tcp/SingleProtocolDecoder.java
  hazelcast/src/main/java/com/hazelcast/internal/server/tcp/SingleProtocolEncoder.java
  hazelcast/src/test/java/com/hazelcast/internal/server/tcp/ProtocolNegotiationTest.java
Labels: Type: Defect, Team: Core, Backport, Source: Internal, Module: Security

#24860 Fix Discovery SPI cluster join when WAIT_SECONDS_BEFORE_JOIN is 0
  hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/DiscoveryJoiner.java
  hazelcast/src/test/java/com/hazelcast/cluster/impl/DiscoverySPIJoinTest.java
Labels: Type: Defect, Team: Core, Source: Community, Module: Discovery SPI

#24892 Add logging and state check to PartitionMigrationComputeIntensiveTest [HZ-2623]
  hazelcast/src/test/java/com/hazelcast/partition/PartitionMigrationComputeIntensiveTest.java
Labels: Team: Core, Type: Test-Failure, Source: Internal, Module: Partitioning, Not Release Notes content

#24800 Mask license key for LicenseExpirationReminderTask [HZ-2048]
  hazelcast/src/main/java/com/hazelcast/internal/config/LicenseKey.java
Labels: Type: Enhancement, Team: Core, Source: Internal, Module: Security, Add to Release Notes

#24867 Update snappy to 1.1.10.1 [HZ-2614] [5.3.z]
  pom.xml
Labels: Type: Cleanup, Source: Internal, Add to Release Notes, dependencies, Team: Integration

#24866 Update snappy to 1.1.10.1 [HZ-2614] [5.2.z]
  pom.xml
Labels: Type: Cleanup, Source: Internal, Add to Release Notes, dependencies, Team: Integration

#24865 Update snappy to 1.1.10.1 [HZ-2614] [5.1.z]
  pom.xml
Labels: Type: Cleanup, Source: Internal, Add to Release Notes, dependencies, Team: Integration

#24871 Provide LocalMapStats data for invocations from Lite members [HZ-2072]
  hazelcast/src/main/java/com/hazelcast/map/impl/LocalMapStatsProvider.java
  hazelcast/src/main/java/com/hazelcast/map/impl/MapServiceContextImpl.java
  hazelcast/src/test/java/com/hazelcast/map/LocalMapStatsProviderTest.java
Labels: Type: Defect, Team: Core, Source: Internal, Module: IMap, Add to Release Notes

#24889 Update Mockito version to 5.4.0
  pom.xml
Labels: Team: Core, Type: Cleanup, Source: Internal, Not Release Notes content

#24844 Use MapContainer to filter maps to be cleaned up when migrating off a partition [HZ-2643]
  hazelcast/src/main/java/com/hazelcast/map/impl/MapMigrationAwareService.java
  hazelcast/src/main/java/com/hazelcast/map/impl/PartitionContainer.java
  hazelcast/src/test/java/com/hazelcast/map/MapMigrationRecordStoreExistenceTest.java
Labels: Type: Defect, Team: Core, Module: IMap

#24890 Do not use partitioned indexes for tiered store enabled maps [HZ-2624]
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/PartitionWideEntryOperation.java
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/steps/PartitionWideEntryOpSteps.java
Labels: Type: Defect, Team: Storage, Module: TStore

#24689 Implement member pruning based on required partitions [HZ-1659]
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/map/LazyDefiningPMSTest.java
  hazelcast/src/main/java/com/hazelcast/jet/config/JobConfigArguments.java
  hazelcast/src/main/java/com/hazelcast/jet/core/DAG.java
  hazelcast/src/main/java/com/hazelcast/jet/core/ProcessorMetaSupplier.java
  hazelcast/src/main/java/com/hazelcast/jet/core/test/TestProcessorMetaSupplierContext.java
  hazelcast/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlanBuilder.java
  hazelcast/src/test/java/com/hazelcast/jet/core/JetTestSupport.java
  hazelcast/src/test/java/com/hazelcast/jet/core/TestProcessors.java
  hazelcast/src/test/java/com/hazelcast/jet/impl/util/JetJobPrunabilityTest.java
Labels: Type: Enhancement, Source: Internal, Team: SQL

#24909 Fix wrong condition by negating it
  hazelcast/src/main/java/com/hazelcast/map/impl/operation/PartitionWideEntryOperation.java
Labels: Type: Test-Failure

#24927 Bump software.amazon.awssdk:bom from 2.17.121 to 2.20.95 [5.1.z]
  extensions/s3/pom.xml
Labels: Source: Internal, Source: Community, dependencies

#24926 Bump software.amazon.awssdk:bom from 2.17.264 to 2.20.95 [5.2.z]
  extensions/s3/pom.xml
Labels: Source: Internal, Source: Community, dependencies

#24929 Improvements to RestClientTest TLS 1.3 support tests (#24794) [5.3.z]
  hazelcast/src/test/java/com/hazelcast/spi/utils/RestClientTest.java
  hazelcast/src/test/java/com/hazelcast/test/bounce/ProgressMonitor.java
Labels: Team: Core, Type: Test-Failure, Source: Internal, Not Release Notes content, Module: REST

#23756 Add/modify helper methods in SqlTestSupport for use in SQL + TStore integration tests [HZ-1613]
  hazelcast-sql/src/test/java/com/hazelcast/jet/sql/SqlTestSupport.java
Labels: Source: Internal, Module: Integration Tests, SQL-only, Module: SQL

#24913 Exclude reload4j transitive test dependencies
  hazelcast-sql/pom.xml
Labels: Type: Cleanup, Source: Internal, Team: SQL, Not Release Notes content, Module: SQL
